### ISSUE TITLE
SmartRefreshLayout 还是使用android.support吗？ 也没看到你的项目咋把它切换成androidx的

### ISSUE THREAD

**Issue by masite** [liangjingkanji/BRV#100]
## 集成到androix项目中就可复现
建议步骤:
 page.onRefresh {
        // 模拟网络请求2秒后成功
        postDelayed({
            val data = getData()
            addData(data) { index <= 2 }
        }, 1000)
    }.showLoading()

## onRefresh这个api会被画横线，编译不通过

异常堆栈信息或者手机截图/视频

## 版本
- BRV:1.3.51
- Gradle: 6.7.1
- Android Studio:  4.2.2
- Android:7

**Comment by TxcA** [comment]
[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout) 最新版并未迁移到AndroidX。SmartRefreshLayout的README中，也有相关配置说明

解决方法在项目`gradle.properties` 中添加
```
android.enableJetifier=true
android.useAndroidX=true
```

> **android.enableJetifier** Android插件会通过重写其二进制文件来自动迁移现有的第三方库，以使用AndroidX依赖项。
> **android.useAndroidX** Android插件会使用对应的AndroidX库，而非Support库。


![](https://files.catbox.moe/cfgaxq.png)
