### ISSUE TITLE
东哥做的东西还是很牛逼，用完之后非同凡响！！！

### ISSUE THREAD

**Issue by ChinaVolvocars** [liangjingkanji/BRV#101]

**Comment by zhaoxiuyu** [comment]
东哥，有support版本吗

**Comment by zhaoxiuyu** [comment]
分组能支持多少级。

**Comment by zhaoxiuyu** [comment]
庞大的老项目，暂时升级不了Android X，想用你的这个库怎么办

**Comment by liangjingkanji** [comment]
> 分组能支持多少级。

分组无限级

**Comment by liangjingkanji** [comment]
> 庞大的老项目，暂时升级不了Android X，想用你的这个库怎么办

打开 AndroidStudio 查看菜单 -> <kbd>Refactor</kbd> -> <kbd>Migrate to AndroidX...</kbd>

开始一键迁移androidx

**Comment by liangjingkanji** [comment]
有问题可以开个单独的issues.  这个贴建议只用于拍马屁
