### ISSUE TITLE
大佬 用过滤功能要怎么实现呢Filter  这个

### ISSUE THREAD

**Issue by bjy520** [liangjingkanji/BRV#105]
## 问题描述
大佬 用过滤功能要怎么实现呢Filter  把搜索出来得结果进行过滤
### 期望行为
把搜索出来得结果进行过滤，不用每次都请求   不是https://coding-pages-bucket-3558162-8706000-16642-587704-1252757332.cos-website.ap-shanghai.myqcloud.com/debounce/ 这个

**Comment by liangjingkanji** [comment]
过滤集合然后赋值给rv不就行了

**Comment by liangjingkanji** [comment]
另外建议查看 https://liangjingkanji.github.io/BRV/, 这才是最新的文档

**Comment by liangjingkanji** [comment]
这里建议使用kotlin数据流`filter`过滤函数

示例
```kotlin
rv.models = list.filter{ it.code >= 1 } // 过滤掉code小于1的数据
```

**Comment by bjy520** [comment]
辛苦大佬了  ，非常感谢！！
