### ISSUE TITLE
点击控件拖拽排序

### ISSUE THREAD

**Issue by 1Ezreal** [liangjingkanji/BRV#106]
## 问题描述
拖拽扩展
### 期望行为
点击某个控件进行拖拽排序，不需要长按，这种如果实现
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
你这个需求本身来说是有问题的, 因为判断滑动列表和拖拽排序手势有冲突

我这里给你两个建议
1. 你要么长按开启
2. 要么你拖拽item的某个小图标开始拖拽(拖拽item则滑动列表)

关于第二点的示例代码如下
```kotlin
binding.rv.linear().setup {
    addType<DragModel>(R.layout.item_drag)
    onBind {
        findView<View>(R.id.btnDrag).setOnTouchListener { _, event ->
            if (event.action == MotionEvent.ACTION_DOWN) { // 如果手指按下则开始拖拽
                itemTouchHelper?.startDrag(this)
            }
            true
        }
    }
}.models = getData()
```

**Comment by liangjingkanji** [comment]
文档已更新 [点击拖拽](https://liangjingkanji.github.io/BRV/drag/#_2)

**Comment by 1Ezreal** [comment]
对的，我需要的就是点击item中某个控件拖拽item，表达不准确

**Comment by liangjingkanji** [comment]
> 多类型可以拖拽吗

当然支持

**Comment by ALEXLEOHY** [comment]
请教一下我可以实现点击指定控件拖动，但是同时长按拖动也存在，能否将长按拖动禁止

**Comment by liangjingkanji** [comment]
> 请教一下我可以实现点击指定控件拖动，但是同时长按拖动也存在，能否将长按拖动禁止

拦截长按事件
