### ISSUE TITLE
分组展开的二级数据10万条目时折叠卡死

### ISSUE THREAD

**Issue by jjlyt2** [liangjingkanji/BRV#107]
## 问题描述
分组展开的二级数据10万条目时折叠卡死
### 期望行为
二级条目过多不卡死
## 如何复现
建议步骤:
-  是否可以在Sample复现
是，修改一下分组的二级数据条目到10万展开后折叠卡死

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:1.3.52

**Comment by liangjingkanji** [comment]
你最好在fork仓库在demo中复现然后给我地址, 方便我快速定位问题

**Comment by jjlyt2** [comment]
就是demo中复现的，分组展开的二级数据集合，条目加到10万+，展开后再折叠就直接卡死了

**Comment by jjlyt2** [comment]
使用场景，如相册展示，同一目录下的图片，图片数据超过10万张

**Comment by jjlyt2** [comment]
这个主要是折叠问题，分页加载如果加载完全部的数据，折叠还是会把item挨个回收，应该还是会卡很久的

**Comment by liangjingkanji** [comment]
> 这个主要是折叠问题，分页加载如果加载完全部的数据，折叠还是会把item挨个回收，应该还是会卡很久的

我尝试修复下

**Comment by jjlyt2** [comment]
好的，感谢

**Comment by jjlyt2** [comment]
根据我的测试发现主要耗时在 折叠方法 `collapse` 中的
`(this@BindingAdapter.models as MutableList).removeAll(sublistFlat)`
这里使用removeAll会非常耗时，建议修改为使用subList代替removeAll
`(this@BindingAdapter.models as MutableList).subList(layoutPosition + 1, layoutPosition + 1 + sublistFlat.size).clear()`
修改后测试即使几十万也不会卡顿了.

**Comment by liangjingkanji** [comment]
如果你提个PR就更好了, 😆

**Comment by jjlyt2** [comment]
就修改了一行，但是百万条目还是会稍微卡一下

**Comment by jjlyt2** [comment]
百万以上卡顿是动画执行导致的卡顿

**Comment by liangjingkanji** [comment]
> 百万以上卡顿是动画执行导致的卡顿，直接使用notifyDataSetChanged()是没卡顿的

`collapse`默认情况下是不使用动画的, 默认情况下不卡是吧

**Comment by jjlyt2** [comment]
是的改为subList删除数据后，百万数据不使用动画不会卡顿，使用动画会卡一下

**Comment by liangjingkanji** [comment]
为什么我还没有收到你的Pull Request

**Comment by Roc-egg** [comment]
提交了，换了个账号，那个是刷JD的账号

**Comment by liangjingkanji** [comment]
那你可以继续摸鱼上班了
