### ISSUE TITLE
最小的改动，实现无限循环滚动，需要怎么实现

### ISSUE THREAD

**Issue by weizhizhu** [liangjingkanji/BRV#109]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
依赖一个第三方的`LayoutManager`库然后赋值给`rv.layoutManager`

https://github.com/BeksOmega/looping-layout

**Comment by weizhizhu** [comment]
好咧 感谢 感谢
