### ISSUE TITLE
能增加一个接受 View参数的方法？

### ISSUE THREAD

**Issue by YumikoAzu** [liangjingkanji/BRV#11]
之前项目用的baserecyclerviewadapterhelper(adapter可以传View参数，而不是R.layout.xxxx 布局参数)，项目没有xml，都是addview创建布局的。

**Comment by liangjingkanji** [comment]
好，我今天研究下。 如果你觉得有合适的方案也可以修改后PR

**Comment by liangjingkanji** [comment]
因为换了M1的MacBookPro13导致无法正常运行AndroidStudio, 需求进度有所拖慢 ...
