### ISSUE TITLE
重写侧滑回调同时使用divider设置分隔线，删除item时候它的分隔线会错位

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#110]
https://user-images.githubusercontent.com/54784104/155872524-318c5a22-7a6b-4496-9b49-a82f27b2d71b.mp4

但是我用了一个自定义的RecyclerView分割线，给rv的addItemDecoration设置上，就没有这个问题🤔

话说老哥，加载后面item的动画有没有啊😗就像BRVAH一样`setAnimationWithDefault(AnimationType.ScaleIn)`

**Comment by SaltedFish-Extreme** [comment]
> 

好吧😂

**Comment by liangjingkanji** [comment]
- [列表动画文档](https://liangjingkanji.github.io/BRV/animation/)
- [分割线文档](https://liangjingkanji.github.io/BRV/divider-linear/)
  > 由于网格分割线是动态计算的, 所以在RecyclerView中假设你添加新的数据使用局部刷新函数(notifyItem*等函数)以后可能需要使用rv.invalidateItemDecorations()刷新分隔物, 否则可能会分割线宽高错乱

**Comment by liangjingkanji** [comment]
DefaultItemTouchCallback可能需要自动调用`invalidateItemDecorations()`更好

**Comment by SaltedFish-Extreme** [comment]
> DefaultItemTouchCallback可能需要自动调用`invalidateItemDecorations()`更好

好像不是这个，我数据是一次全设置进去的，我在onSwiped里面调用`rv?.invalidateItemDecorations()`好像没有用😂

**Comment by liangjingkanji** [comment]
侧滑不就删除了item吗? 侧滑源码就是调用的`notifyItemRemoved`

**Comment by liangjingkanji** [comment]
你在demo复现个问题给我看下吧

**Comment by SaltedFish-Extreme** [comment]
> 侧滑不就删除了item吗? 侧滑源码就是调用的`notifyItemRemoved`

我以为你说的添加新数据😂

> 你在demo复现个问题给我看下吧, 我没复现出来你视频效果

那我试试吧，复现不了的话，我就还是用addItemDecoration做好了😂

**Comment by SaltedFish-Extreme** [comment]
克隆了半小时拉不下来仓库，还是算了吧，我继续用自定义分隔线了😥麻烦老哥了
