### ISSUE TITLE
上拉

### ISSUE THREAD

**Issue by swanfly** [liangjingkanji/BRV#111]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
问的什么

**Comment by swanfly** [comment]
抱歉，提交错了，无法上拉，我再研究一下

**Comment by liangjingkanji** [comment]
可以看看demo

**Comment by swanfly** [comment]
已经解决了，这个库很强大👍，可以节省大量代码，感谢作者无私贡献

**Comment by liangjingkanji** [comment]
一起用一起维护就好了

**Comment by swanfly** [comment]
好的
