### ISSUE TITLE
实现接口填充数据

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#112]
````kotlin
rv.linear().setup {
            addType<HistoryRecordDB>(R.layout.item_history_record_list)
            onBind { SimpleModel(getModel()) }
        }
````

````kotlin
override fun onResume() {
        super.onResume()
        rv.models = ......
    }
````

````kotlin
class SimpleModel(var model: HistoryRecordDB) : ItemBind {

    override fun onBind(holder: BindingAdapter.BindingViewHolder) {
        holder.findView<TextView>(R.id.item_history_title).text = model.title
        holder.findView<TextView>(R.id.item_history_date).text = model.date
    }
}
````

这样写对吗？我刚才试了下实现接口的方式，但是没有显示数据，只有分隔线😂

**Comment by liangjingkanji** [comment]
要求数据类型实现`ItemBind`接口, 你数据类型是HistoryRecordDB

你这里随便创建一个对象你觉得可能会自动执行`onBind`吗?
```kotlin
onBind { SimpleModel(getModel()) }
```

**Comment by SaltedFish-Extreme** [comment]
> 有问题先看完Demo, Demo才几十行代码而已并不难看

emmm我看你文档这么写的就直接复制用了的😂也没看出来是在数据类里实现这个接口，还以为是个类就行，也没看着在哪使用SimpleModel的😂之前看过你demo里这个类，没看清楚是数据类，而且注释掉了，也是在onBind回调里写的数据绑定操作，我还以为是和BRVAH一样弄的adapter，当时没看懂就没再看了😅

**Comment by liangjingkanji** [comment]
不知道你看了demo里面的 `复杂列表` 示例代码没
使用MVVM形式可以以最少的代码实现最复杂的功能.  数据库类不代表无法实现接口. 接口本身就是多实现

另外我并不推荐你使用litePal. 我只推荐使用谷歌官方的room

**Comment by liangjingkanji** [comment]
首先
1. Adapter本身存在视图和数据在一起无法在迭代版本中快速复用. 你删除UI控件你可能就报错了. 
2. Room比LitePal好在可以监听数据库(这是大杀器). 可以SQL语法高亮. 而且他的形式更加解耦
4. 不是代码挪个位置就叫做解耦, 也不是抽取就叫做优雅. 你这简单代码复杂写法. 我很不喜欢看代码跳来跳去的
5. 你Activity什么都不放是用来干什么的? 你仿佛就像某些人C盘什么软件都不放但是空着100多个G永远不用一样. Activity属于UI层放UI事件很正常

**Comment by SaltedFish-Extreme** [comment]
1、确实是item里的控件删了在adapter中的数据绑定也要删除，虽然我基本也没这么做过，毕竟也没更过几次版本😂

2、我做了安卓以后基本就没写过sql了，数据库也没大用过，也没监听过，只是普通的增删改查，这样比较下来还是litepal方便

3、其实我就想每个文件里的代码少一点，方法再分出来，加上注释方便看，跳来跳去其实就是每个控件跳转相应的页面罢了，我最不喜欢databinding的一点就是activity/fragment不能和对应的xml文件互相跳转，然后属性也不知道在哪定义的，xml和数据太耦合了，看起来太费力了

4、我Activity确实只设置外层的控件属性，以及相应的事件，就像我C盘确实啥都不放一样😂

![image](https://user-images.githubusercontent.com/54784104/155878985-dd507bfb-6d50-49fa-af11-575dfb104e41.png)
