### ISSUE TITLE
期望同时支持列表上下分页预加载

### ISSUE THREAD

**Issue by CosmicRayLucky** [liangjingkanji/BRV#114]
## 问题描述

看代码，当前的预加载跟预拉取是互斥的，预拉取只是把View反转，并不能向上向下加载共存

### 期望行为

预加载、预拉取可以共存

**Comment by liangjingkanji** [comment]
一般场景只是聊天记录列表拉取更多记录罢了. 我不清楚你要的上下都是拉取更多记录需求要在什么场景使用

BRV是集成的SmartRefreshLayout来实现的, 你这个需求可以自己自定义刷新头RefreshHeader实现

**Comment by CosmicRayLucky** [comment]
消息搜索定位到中间位置，这个时候上下都还有未同步的数据，需要上下都进行加载。

**Comment by liangjingkanji** [comment]
这种需求不需要刷新头. 
你这个需求肯定是根据记录的ID去查询下一页. 所以我建议你使用`addOnScrollListener`监听滚动位置. 然后去查询到滚动倒数第几个再去请求列表数据.

**Comment by CosmicRayLucky** [comment]
对的，PageRefreshLayout基本是用不上的

**Comment by CosmicRayLucky** [comment]
> 这种需求不需要刷新头 你这个需求肯定是根据记录的ID去查询下一页, 无法使用BRV中的`onLoadMore`加载下一页. 所以我建议你使用`addOnScrollListener`监听滚动位置. 然后去查询到滚动倒数第几个再去请求列表数据

老哥，你这回复真快

**Comment by CosmicRayLucky** [comment]
> 这种需求不需要刷新头 你这个需求肯定是根据记录的ID去查询下一页, 无法使用BRV中的`onLoadMore`加载下一页. 所以我建议你使用`addOnScrollListener`监听滚动位置. 然后去查询到滚动倒数第几个再去请求列表数据

**Comment by liangjingkanji** [comment]
希望未来你和我一起为爱发电维护开源!

> 秒回是一个舔狗的基本素养 --- 郭楠

**Comment by CosmicRayLucky** [comment]
> 希望未来你和我一起为爱发电维护开源!
> 
> > 秒回是一个舔狗的基本素养 --- 郭楠

向老哥学习，添购也要做狗王！
