### ISSUE TITLE
如何复用BindingAdapter

### ISSUE THREAD

**Issue by 1Ezreal** [liangjingkanji/BRV#115]
## 问题描述
如果正确复用BindingAdapter,项目中很多相似的列表
### 期望行为
```kotlin
class TestAdapter: BindingAdapter() {

    init {
        addType<FlexTagModel>(R.layout.item_flex_tag)
    }

    override fun onViewDetachedFromWindow(holder: BindingViewHolder) {
        //TODO 
        super.onViewDetachedFromWindow(holder)
    }

}
```
大佬，这种是否可行
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
使用databinding
1. 业务逻辑在Model
2. ui在xml
你完全不需要写什么Adapter. 如果列表相似直接注册一样的xml不就行了吗?

**Comment by liangjingkanji** [comment]
为了你我更新了个文档

**Comment by 1Ezreal** [comment]
有些情况需要在Adapter的生命周期里面去处理，onViewRecycled(),onViewDetachedFromWindow（）,直接在Activity里面调用又是一堆代码
