### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by XXiaoQing** [liangjingkanji/BRV#116]
功能的确强大，但是好多功能是不需要的，可以拆分成不同的 lib ，按需依赖

**Comment by liangjingkanji** [comment]
都是常见需求, 我不可能按函数为单位拆分

**Comment by XXiaoQing** [comment]
意义在于：
1、成熟的项目里面已经有各种的框架了，只需要某一个功能，
2、做包体积优化的时候，甚至会把三方sdk 中没有用的功能全部删除了再次打包，有时候就是为了优化出 1k 的体积

**Comment by liangjingkanji** [comment]
很多功能都是一个自定义Adapter类, 怎么拆分

举个例子你不可能说要一个选择功能我就能拆分, 我也不可能一个文件一个依赖库. 
另外分依赖太多会更增加apk体积, 因为依赖本身还包含一些依赖描述文件, 最后描述文件比源码本身体积还大
sdk和框架定义就有很大的区别. 比如okHttp你不使用拦截器你能让他把拦截器删掉吗? 

最后我是不可能做成优化1kb体积去二次打包的事, 对于这种特殊需求你可以直接下载源码文件导入, BRV本身耦合度不高

**Comment by liangjingkanji** [comment]
实际上BRV可以和Net联动自动化请求, 但是是可选依赖
