### ISSUE TITLE
对比数据刷新条目白屏动画

### ISSUE THREAD

**Issue by BLOODMAGEBURT** [liangjingkanji/BRV#117]
## 问题描述
使用setDifferModels对比刷新时, 相同item刷新有白屏动画，getChangePayload返回true也不行
### 期望行为
关闭白屏动画
## 如何复现
使用brvsample,将条目背景色改成黑色时，条目刷新出现白屏动画
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图
![image](https://user-images.githubusercontent.com/16059706/156483483-a9e11f3a-fc18-44bd-a79d-d2f2df408463.png)

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
首先你得确定是相同item

ItemDifferCallback的其他两个函数你是否确定你数据能相等? 默认使用的是`oldItem == newItem`

```kotlin
/**
 * 判断新旧数据是否相等
 *
 * @param oldItem 旧数据
 * @param newItem 新数据
 * @return 新旧数据是否相等
 */
fun areItemsTheSame(oldItem: Any, newItem: Any): Boolean {
    return oldItem == newItem
}

/**
 * 检查新旧数据内容是否相等
 * 例如同一个对象, 但是其属性发生变化需要触发RecyclerView更新列表时应当该方法返回true
 *
 * 该方法只有在[areItemsTheSame]返回true时才会调用
 *
 * @param oldItem 旧数据
 * @param newItem 新数据
 * @return 新旧数据的内容是否相等
 */
fun areContentsTheSame(oldItem: Any, newItem: Any): Boolean {
    return oldItem == newItem
}
```

**Comment by BLOODMAGEBURT** [comment]
是我表述错了，是item变了，我想去掉改变的这个item的白屏动画
![image](https://user-images.githubusercontent.com/16059706/156487128-26d5eccf-4ee7-4e98-94a3-e59751a1b181.png)
加了以上方法也不行

**Comment by BLOODMAGEBURT** [comment]
![image](https://user-images.githubusercontent.com/16059706/156488130-b5d980b0-e4f0-457e-9b98-806924bc29f9.png)

https://user-images.githubusercontent.com/16059706/156488265-b30de8bf-80eb-4c3a-931e-6eabd94633ed.mp4

最后一个item在更新数值，白屏很明显

**Comment by liangjingkanji** [comment]
areItemsTheSame 返回TRUE   areContentsTheSame 返回FALSE getChangePayload 返回不为空 情况下才能不白屏更新

我上面的内容你没看吧, 你都改变了data class的字段值了, `==`肯定返回FALSE啊

**Comment by liangjingkanji** [comment]
```kotlin
private val randomData = getRandomData(true) // 保存集合

override fun initView() {
    setHasOptionsMenu(true)

    binding.rv.linear().setup {
        addType<SimpleModel>(R.layout.item_simple)
        onBind {
            findView<TextView>(R.id.tv_simple).text = getModel<SimpleModel>().name
        }
        itemDifferCallback = object : ItemDifferCallback {

            /** gain */
            override fun areItemsTheSame(oldItem: Any, newItem: Any): Boolean {
                return oldItem === newItem // 判断是否为一个对象
            }

            override fun areContentsTheSame(oldItem: Any, newItem: Any): Boolean {
                return oldItem != newItem // 判断内容不一致
            }

            override fun getChangePayload(oldItem: Any, newItem: Any): Any? {
                return true // 返回不为null即可
            }
        }
    }.models = randomData

}
```

然后更新集合中的元素数据
```
R.id.menu_random_data -> {
    (randomData[3] as SimpleModel).name = System.currentTimeMillis().toString()
    binding.rv.setDifferModels(randomData)
}
```

**Comment by liangjingkanji** [comment]
如果kotlin的`data class`和`==`和`===`符号区别都不明白, 建议学习以后再来写这个需求

**Comment by BLOODMAGEBURT** [comment]
嗯感谢，看懂了上面的itemcallback,
现在目的是：改变了item的值，也想去掉这个item的白屏动画
(Objects.requireNonNull(binding.rv.itemAnimator) as SimpleItemAnimator).apply {
            changeDuration = 0
            supportsChangeAnimations = false
        }
之前我使用局部更新的时候，加上上面的去掉item动画的代码就可以了，不知道为啥这个没起作用

**Comment by liangjingkanji** [comment]
@BLOODMAGEBURT 你改下判断逻辑不就行了吗? 我上面不有示例代码吗? 如果你看懂了不存在不知道修改吧

**Comment by liangjingkanji** [comment]
你那个无效我不清楚什么情况, 你可以按照你之前自己的写法去写增量更新也行, 我并没有自定义RecyclerView

**Comment by liangjingkanji** [comment]
`ItemDifferCallback`是RecyclerView的基础知识, 不属于BRV的内容

**Comment by BLOODMAGEBURT** [comment]
非常感谢，
areItemsTheSame 返回TRUE
areContentsTheSame 返回FALSE
getChangePayload 返回不为空
这三个条件我现在真正看懂了，学习到了，感谢，目前可以正常更新不闪屏了

**Comment by liangjingkanji** [comment]
我已经更新DifferDataChangeFragment的代码示例
