### ISSUE TITLE
分组：展开全部或者折叠全部

### ISSUE THREAD

**Issue by CosmicRayLucky** [liangjingkanji/BRV#118]
## 问题描述

1. 看代码里面，分组展开与关闭是通过holder处理，未bind过的并不会处理。        val holder = rv?.findViewHolderForLayoutPosition(position) as? BindingViewHolder ?: return 0
2.  一键展开或者折叠全部怎么处理比较好
![image](https://user-images.githubusercontent.com/20819344/156686585-1f9ba5b1-a3a9-4682-8629-4e3d113b321b.png)

### 期望行为

1. 原位（保持顶部位置不变）展开全部分组
4. 原位（当前顶部位置所在的分组）折叠全部分组

**Comment by liangjingkanji** [comment]
不是有个参数`depth`吗?

```kotlin
/**
 * 折叠子项
 * @param depth 递归折叠子项的深度, 如等于-1则代表展开所有子项, 0表示仅展开当前
 * @return 折叠后减少的条目数量
 */
fun collapse(@IntRange(from = -1) depth: Int = 0): Int
```

**Comment by liangjingkanji** [comment]
未onBindViewHolder处理过的Item的确展开折叠失效

**Comment by CosmicRayLucky** [comment]
> 不是有个参数`depth`吗?
> 
> ```kotlin
> /**
>  * 折叠子项
>  * @param depth 递归折叠子项的深度, 如等于-1则代表展开所有子项, 0表示仅展开当前
>  * @return 折叠后减少的条目数量
>  */
> fun collapse(@IntRange(from = -1) depth: Int = 0): Int
> ```

depth是展开深度，并不会展开同级别的分组。你的意思是把所有数据的都放到一个分组里面？

**Comment by liangjingkanji** [comment]
@CosmicRayLucky 

目前建议将列表的数据模型`ItemExpand.itemExpand`属性默认设置为true. 然后再赋值给列表. 这样默认就是展开全部

如果需要折叠全部就遍历数据集合将数据模型`ItemExpand.itemExpand`属性全部设置为false, 然后重新赋值给列表



> 未onBindViewHolder处理过的Item的确展开折叠失效

关于这个问题请等待修复, 也欢迎你的PR

**Comment by CosmicRayLucky** [comment]
👌，那我就按老方法法直接处理数据然后刷新了。

**Comment by liangjingkanji** [comment]
PR #121
