### ISSUE TITLE
我刚才发现BRV介绍里的三方组件有俩一样的，可以把其中一个换成SwipeLayout

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#122]
![image](https://user-images.githubusercontent.com/54784104/156913661-45996aa4-8e24-43c9-a170-5fe282e0a43e.png)

https://github.com/daimajia/AndroidSwipeLayout

**Comment by liangjingkanji** [comment]
提议不错, 如果你能发起一个PR就更好了

**欢迎共同维护**

**Comment by SaltedFish-Extreme** [comment]
不过那个也挺久没更新了，kotlin用起来要重写的方法也很多，挺麻烦的，我只需要一个简单的侧滑删除按钮，就直接用了一个老哥封装的侧滑布局了 [SwipeItemLayout](https://github.com/SaltedFish-Extreme/WanAndroid/blob/master/app/src/main/java/com/example/wanAndroid/widget/layout/SwipeItemLayout.kt)
