### ISSUE TITLE
可以支持瀑布流布局吗

### ISSUE THREAD

**Issue by Wang-Yumin** [liangjingkanji/BRV#123]

**Comment by liangjingkanji** [comment]
当然支持, Demo里面就有`StaggeredDividerFragment`: 交错列表-网格分割线

**Comment by Wang-Yumin** [comment]
完美了，感谢大牛，厉害

**Comment by liangjingkanji** [comment]
我竟然发现你没follow我, 伤心了

**Comment by Wang-Yumin** [comment]
follow you！刚了解这个项目就 star了呀，为了用这个框架，专门去恶补了kotlin，现在项目已经用上了

**Comment by liangjingkanji** [comment]
kotlin世界上最好的编程语言! 配合我的框架解放摸鱼时间
