### ISSUE TITLE
没有Java使用文档

### ISSUE THREAD

**Issue by 1244752609** [liangjingkanji/BRV#124]

**Comment by TxcA** [comment]
❌ ~~没有Java使用文档。~~

✔ 不支持Java。或者说在Java下使用，扩展函数、高阶函数的调用，会让你头皮发麻。

👍 **已经2022年了，做Android还是推荐学习Kotlin。至少，得了解。**

**Comment by liangjingkanji** [comment]
> 旧时代的残党终将被淘汰 - 海贼.王路飞

**Comment by SaltedFish-Extreme** [comment]
> 旧时代的残党终将被淘汰 - 海贼.王路飞

(Java)已没有能带你前往新时代的船了 -不死鸟.马尔高
