### ISSUE TITLE
BR.m 生成不了

### ISSUE THREAD

**Issue by GuangNian10000** [liangjingkanji/BRV#126]
## 问题描述
我已经按文档配置了，可是不管是make project还是clean project 重启 都生成不了对应文件
### 期望行为
生成BR文件
## 如何复现
-  是否可以在Sample复现
- Sample正常

## 截图
![image](https://user-images.githubusercontent.com/44353535/157367344-6b1c88d6-9282-4dc0-b501-6a9d118e00b3.png)
![image](https://user-images.githubusercontent.com/44353535/157367369-c18249df-f5bc-471e-b481-99aab62b3fab.png)
![image](https://user-images.githubusercontent.com/44353535/157367451-97aadb74-d218-454e-bc27-00b0cec5a0df.png)
![image](https://user-images.githubusercontent.com/44353535/157367507-fba7605e-b0b1-4846-91a2-4aa74f103a37.png)

## 版本
- BRV: 1.3.54
- Gradle: 7.1
- Android Studio:  MAC Android Studio Bumblebee | 2021.1.1 Patch 1 
- Android: 12

**Comment by TxcA** [comment]
是否已引入 kapt?
```
apply plugin: 'kotlin-kapt'
```

**Comment by GuangNian10000** [comment]
> 是否已引入 kapt?
> 
> ```
> apply plugin: 'kotlin-kapt'
> ```
引入了
![image](https://user-images.githubusercontent.com/44353535/157380433-90b5776c-a760-4f45-a983-fc9875403d44.png)

**Comment by GuangNian10000** [comment]
重新创建工程没出现这个情况，倒入到实际项目中有问题，我怀疑有什么冲突了，正在寻找中

**Comment by TxcA** [comment]
我这边使用了相同的环境，做了一个空工程，是能正常的生成BR的。

- build.gradle
```groovy
plugins {
    id 'com.android.application' version '7.1.1' apply false
    id 'com.android.library' version '7.1.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.10' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

- build.gradle(app)
```groovy
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 31

    // 新开工程，只对以下4行做了添加
    buildFeatures {
        dataBinding = true
        viewBinding = true
    }

    defaultConfig {
        applicationId "com.itxca.myapplication"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

......省略
```

- activity_main.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>
        <variable
            name="m"
            type="String" />
    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Hello World!"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>
```
![1](https://user-images.githubusercontent.com/15992858/157384926-8113caaf-ec35-4643-949b-ba59cdac93c5.jpg)
![2](https://user-images.githubusercontent.com/15992858/157384943-852e217d-09dc-435f-a0b6-25e056fee243.png)

---

@GuangNian10000 BR是DataBinding生成的，不是BRV生成的。
由于DataBinding不生成BR的情况我个人没遇到过。这里推荐新开一个测试工程，只开启dataBinding，看看能否正常生成BR。

**Comment by GuangNian10000** [comment]
> 

感谢回复，我新开一个测试工程没有任何问题，不过我发现原因了：
BRV.modelId = BR.m   这段代码我是复制文档粘贴过去的，这时候编译器会报BR红色，你option+return 是导入不了的。
如果把BR单独先敲出来就会提示需要导入的文件，然后再敲.m 就可以了
我用的是MAC Android Studio Bumblebee | 2021.1.1 Patch 1  不知道其它版本的编译器会不会有这样的问题

**Comment by TxcA** [comment]
> 重新创建工程没出现这个情况，倒入到实际项目中有问题，我怀疑有什么冲突了，正在寻找中

还在贴代码，你已经尝试了... 👍

---

由于个人项目存在差异，又没有报错信息，这里估计只有靠你自己 google &stackoverflow :

[https://stackoverflow.com/questions/39483094/data-binding-class-not-generated](https://stackoverflow.com/questions/39483094/data-binding-class-not-generated)
