### ISSUE TITLE
错误: 找不到符号 import androidx.databinding.DataBindingComponent;

### ISSUE THREAD

**Issue by mcxinyu** [liangjingkanji/BRV#127]
大家好，第一次接入，也是第一次使用 databinding，发现一个错误，google和stackoverflow都没用，不清楚是不是我搜索的不对。

`
\build\generated\source\kapt\njfBetaArm64Debug\com\sxmd\tornado\intelli\DataBinderMapperImpl.java:7: 错误: 找不到符号
import androidx.databinding.DataBindingComponent;
                           ^
  符号:   类 DataBindingComponent
  位置: 程序包 androidx.databinding
`

![image](https://user-images.githubusercontent.com/9566116/157421374-8b8f2a9a-3e18-467d-b805-cd9adf63769a.png)

**Comment by liangjingkanji** [comment]
你这个错误估计是你在xml里面写了错误的用法或者符号

点开源码可以看到具体什么符号缺失

**Comment by mcxinyu** [comment]
你好，我还没有开始写代码，只是添加了贵库的依赖和开启databinding设置。

**Comment by mcxinyu** [comment]
![image](https://user-images.githubusercontent.com/9566116/157564337-670236d1-f37a-40b1-9d09-1958c757436c.png)

**Comment by mcxinyu** [comment]
![image](https://user-images.githubusercontent.com/9566116/157564655-a9e7680a-b6fe-4e2c-96de-1d2f6c25ab49.png)
感觉是 databinding-runtime-4.2.2 版本不对，他的版本跟 viewbinding 一致了，可能是与 viewdingding 冲突

**Comment by TxcA** [comment]
**`Terminal` -> `gradlew assembleDebug --stacktrace`
完成后贴详细日志。**

![_3`PC }%ES2YXOOX5@ODDW7](https://user-images.githubusercontent.com/15992858/157565310-7fb1f57e-761d-48ce-8b7f-8889cd0362be.png)
