### ISSUE TITLE
希望能新增四个Adapter的回调

### ISSUE THREAD

**Issue by keternity** [liangjingkanji/BRV#129]
## 问题描述
     在业务特殊场景下用需要重写Adapter的onViewAttachedToWindow、onAttachedToRecyclerView、onViewDetachedFromWindow、onDetachedFromRecyclerView
### 期望行为
    希望大佬能够提供该4个方法的invoke回调
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
目前就支持，可能你用的不是最新版本

**Comment by liangjingkanji** [comment]
理解有误, 你这种需求文档有提及建议通过继承或者匿名BindingAdapter类来实现(可以覆写所有Adapter函数回调)

**Comment by keternity** [comment]
好的，谢谢大佬[狗头]
