### ISSUE TITLE
大佬，setDifferModels没有处理有header的情况，导致拥有header的列表出现刷新错误

### ISSUE THREAD

**Issue by keternity** [liangjingkanji/BRV#130]
## 问题描述
    setDifferModels没有处理有header的情况，导致拥有header的列表出现刷新错误
## 如何复现
建议步骤:
-  是否可以在Sample复现    
- 如果不能在Sample复现建议Fork本仓库然后复现 
   Fork代码后，修改demo，新增header，可以复现列表刷新错误
- 主要代码
```kotlin
 fun setDifferModels(newModels: List<Any?>?, detectMoves: Boolean = true, commitCallback: Runnable? = null ) {
  val oldModels = _data
  _data = newModels
  val diffResult = DiffUtil.calculateDiff(ProxyDiffCallback(newModels, oldModels, itemDifferCallback), detectMoves)
  val mainLooper = Looper.getMainLooper()
  if (Looper.myLooper() != mainLooper) {
      Handler(mainLooper).post {
          diffResult.dispatchUpdatesTo(this)
          commitCallback?.run()
      }
  } else {
      diffResult.dispatchUpdatesTo(this)
      commitCallback?.run()
  }
}
```
## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV: 1.3.45
- Gradle: 
- Android Studio:  
- Android:

**Comment by keternity** [comment]
手机录制视频

**Comment by liangjingkanji** [comment]
视频呢?

**Comment by keternity** [comment]
。。。。点上传了。。。居然没出来。。。[吐血]
视频地址：https://raw.githubusercontent.com/keternity/BRV/master/Screenrecorder-2022-03-13-18-10-59-905.mp4

**Comment by liangjingkanji** [comment]
我的意思是fork仓库并复现问题. 并且你视频没有发出来. 不是让你fork仓库上传视频....

视频在输入框内粘贴就会自动上传并显示了

**Comment by keternity** [comment]
可能网速不行，框子里面显示了，但是提交了，没显示。。。。[捂脸]
仓库地址：https://github.com/keternity/BRV（测试代码已上传）。
辛苦大佬了。

**Comment by liangjingkanji** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/21078112/158055853-9a55e3bb-c826-4430-b749-8170a46874ba.png">

**Comment by liangjingkanji** [comment]
你添加头布局用错了/ 头布局只是一个特殊的item罢了, 你在setup创建Adapter的时候就添加等于无用. 
1. 你要在setup的时候`addType<头布局数据>(头布局布局)`
1. 你要在构建数据的时候`addHeader(头布局数据对象)`
