### ISSUE TITLE
無法同時執行下拉刷新和上拉加載更多

### ISSUE THREAD

**Issue by b2468623437132** [liangjingkanji/BRV#132]
## 问题描述
不好意思，不知道是不是我哪裡寫法有問題

當我在同時使用page.onRefresh 和 page.onLoadMore時，若先執行下拉刷新，而後會無法進行上拉加載更多（執行onRefresh內的第一行程式時mEnableLoadMore屬性會直接被變成false）。

但若先執行上拉加載更多則後續不會有mEnableLoadMore和mEnableRefresh屬性被更改為false的問題

### 期望行为
在使用下拉刷新後，mEnableLoadMore屬性應該還要保持true(即還是可以進行上拉加載更多)

## 程式截图
![image](https://user-images.githubusercontent.com/29422378/159540291-48dbf1bb-e02c-48e0-b0cc-950b36c395d9.png)

## 版本
- BRV:1.3.54
- Gradle: 7.0.0
- Android Studio:  2021.1.1 Patch2
- Android:11

**Comment by liangjingkanji** [comment]
特地如此设计的

下拉刷新成功才会开启上拉加载功能,  一个页面都无法刷新出来你显示上拉加载合适吗? 有什么大型app如此吗?

**Comment by b2468623437132** [comment]
懂了，我剛發現問題是出在加載完成後調用成
page.finishRefresh()、page.finishLoadMore()了
原來還有一個finish()！
這樣看起來就非常合理了，感謝您的迅速解答。

**Comment by liangjingkanji** [comment]
关于你这个问题我觉得影响到SmartRefreshLayout自带的函数也不是太好, 有空我会兼容下`finishRefresh`等函数

**Comment by liangjingkanji** [comment]
这个问题在最新版本得到了改进
```groovy
implementation 'com.github.liangjingkanji:BRV:1.3.55'
```
