### ISSUE TITLE
关于自动分页加载初始化index问题

### ISSUE THREAD

**Issue by qq570026938** [liangjingkanji/BRV#133]
## 问题描述
后台的分页要求不是按照常规1，2，3这种分页计算的数据，而是按照拉取到的数据个数计算的，比如每次拉取15条数据，我的index传0，15，30，在我手动刷新额时候，index数值没有地方做初始化，监听刷新状态是在请求之后回调的也处理不了
### 期望行为
能不能把状态监听放在触发请求之前回调，这样，在刷新数据的时候我可以初始化一下index或其他请求之前的数据处理，或者是否有其他实现方式
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:1.3.54
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
`PageRefreshLayout.index`这个字段只是在你使用`addData`函数内部自增+1罢了, 你调用addData函数之后自己再`+14`不行吗?

或者你自己复制addData函数重新写个扩展函数(比如叫`addPage`)给PageRefreshLayout, 在里面修改下即可

**Comment by TxcA** [comment]
这个需求还是比较简单的
```kotlin
 private const val PAGE_SIZE = 15
 
 scope {
   ...
   load(index * PAGE_SIZE)
 }
```

---
eg. 遇到过时间戳分页的, 也就是数据最后一条带的时间戳，做为下一个分页的值传入。
kotlin 有很强的扩展性，建议适当扩展发挥使用。
框架如果做全业务适配，1.不现实 2.太臃肿

**Comment by qq570026938** [comment]
> 这个需求还是比较简单的
> 
> ```kotlin
>  private const val PAGE_SIZE = 15
>  
>  scope {
>    ...
>    load(index * PAGE_SIZE)
>  }
> ```
> 
> eg. 遇到过时间戳分页的, 也就是数据最后一条带的时间戳，做为下一个分页的值传入。 kotlin 有很强的扩展性，建议适当扩展发挥使用。 框架如果做全业务适配，1.不现实 2.太臃肿

作者说的+14，跟你这个用×去做都能实现，确实是我想的复杂了，把index先初始化成0，用×或者+14都可以做，觉得乘法不错，谢谢指点

**Comment by liangjingkanji** [comment]
> > 这个需求还是比较简单的
> > ```kotlin
> >  private const val PAGE_SIZE = 15
> >  
> >  scope {
> >    ...
> >    load(index * PAGE_SIZE)
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > eg. 遇到过时间戳分页的, 也就是数据最后一条带的时间戳，做为下一个分页的值传入。 kotlin 有很强的扩展性，建议适当扩展发挥使用。 框架如果做全业务适配，1.不现实 2.太臃肿
> 
> 作者说的+14，跟你这个用×去做都能实现，确实是我想的复杂了，把index先初始化成0，用×或者+14都可以做，觉得乘法不错，谢谢指点

不要叫我作者. 这是开源项目人人都是作者, 他也是作者, 你也可以是

**Comment by qq570026938** [comment]
> > > 这个需求还是比较简单的
> > > ```kotlin
> > >  private const val PAGE_SIZE = 15
> > >  
> > >  scope {
> > >    ...
> > >    load(index * PAGE_SIZE)
> > >  }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > eg. 遇到过时间戳分页的, 也就是数据最后一条带的时间戳，做为下一个分页的值传入。 kotlin 有很强的扩展性，建议适当扩展发挥使用。 框架如果做全业务适配，1.不现实 2.太臃肿
> > 
> > 
> > 作者说的+14，跟你这个用×去做都能实现，确实是我想的复杂了，把index先初始化成0，用×或者+14都可以做，觉得乘法不错，谢谢指点
> 
> 不要叫我作者. 这是开源项目人人都是作者, 他也是作者, 你也可以是

哈哈，好的，前辈(*^_^*)
