### ISSUE TITLE
列表加载1000条数据卡顿问题

### ISSUE THREAD

**Issue by qq570026938** [liangjingkanji/BRV#135]
## 问题描述
在加载本地数据的时候，需要一次性显示，如果本地数据比较庞大，目前发现加载1000条数据的时候，页面就有卡顿现象，之前用到的一个库好像一千条数据并没有卡顿，不知道它是不是内部有什么处理
### 期望行为
BRV有提供什么好的处理方式吗，自动分页处理网络数据挺好，但这种本地数据是需要我自己先处理一下，在分页吗
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
一次性加载大量数据RV本身有提供工具类`AsyncListUtil`(原理也是分页加载). 本框架只是自定义Adapter没有限制RV自带功能

我建议你本地分页加载, 对内存抖动或者视图渲染都会相对更好. 也比`AsyncListUtil`方便

**Comment by qq570026938** [comment]
> 一次性加载大量数据RV本身有提供工具类`AsyncListUtil`(原理也是分页加载). 本框架只是自定义Adapter没有限制RV自带功能
> 
> 我建议你本地分页加载, 对内存抖动或者视图渲染都会相对更好. 也比`AsyncListUtil`方便

好，明白了

**Comment by liangjingkanji** [comment]
有更好的处理方式可以告诉我或者发起PR请求
