### ISSUE TITLE
多布局中有嵌套recyclerview布局显示不全问题

### ISSUE THREAD

**Issue by qq570026938** [liangjingkanji/BRV#137]
## 问题描述
NestedScrollView嵌套recyclerview添加大量数据时候界面卡顿，换成用rcyclerview实现多布局嵌套recyclerview数据显示又不全了
### 期望行为
实现这种复杂布局包括横向，纵向和网格的页面，用BRV多布局嵌套，数据显示不全，用NestedScrollView嵌套recyclerview加载大量数据容易卡顿，我该怎么处理
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
首先你说的问题都是rv问题, 和本框架无关

NestedScrollView嵌套rv会一次性加载rv所有视图(失去复用特性)导致卡顿

rv嵌套rv理论上是正常的, 显示不全不清楚你是什么情况, 你可以画个布局示意图给我看下

**Comment by qq570026938** [comment]
> 首先你说的问题都是rv问题, 和本框架无关
> 
> NestedScrollView嵌套rv会一次性加载rv所有视图(失去复用特性)导致卡顿
> 
> rv嵌套rv理论上是正常的, 显示不全不清楚你是什么情况, 你可以画个布局示意图给我看下

我在BRV的item里面有两个recycleview,一个设置横向滑动，一个设置网格布局，加载完数据之后，页面只显示当前一屏的数据，上滑也滑不了

**Comment by liangjingkanji** [comment]
理论上不存在这个问题, 我不清楚你怎么设置的. 

不过rv嵌套存在一个滑动惯性丢失的问题, 你这个问题我在现有的信息上无法解决, 建议你网上搜索下

但是可以肯定这不属于brv的问题, brv没有自定义rv

**Comment by qq570026938** [comment]
> 理论上不存在这个问题, 我不清楚你怎么设置的 不过rv嵌套存在一个滑动惯性丢失的问题, 你这个问题我在现有的信息上我无法解决, 建议你网上搜索下或者加群问 但是可以肯定这不属于brv的问题, brv没有自定义rv
> 
> 如果你还不能提供更多的信息稍后我会关闭此问题

**Comment by liangjingkanji** [comment]
如果无法解决欢迎和群友共同探讨问题

**Comment by qq570026938** [comment]
> > 理论上不存在这个问题, 我不清楚你怎么设置的 不过rv嵌套存在一个滑动惯性丢失的问题, 你这个问题我在现有的信息上我无法解决, 建议你网上搜索下或者加群问 但是可以肯定这不属于brv的问题, brv没有自定义rv
> > 如果你还不能提供更多的信息稍后我会关闭此问题

好的，我那部分代码删除了，界面也没了，又换了种方式
