### ISSUE TITLE
建议改成 "可能是Android上最强大的RecyclerView库 " 小心广告法盯上你，哈哈

### ISSUE THREAD

**Issue by daiji168** [liangjingkanji/BRV#14]

**Comment by liangjingkanji** [comment]
描述事实而已, 不算广告

**Comment by liangjingkanji** [comment]
期待给我推荐更好的

**Comment by zqr95518** [comment]
你这个sample工程有点东西啊，虽然第一次用kt，但是你这工程我都可以直接框架改改拿去用了。(狗头)

**Comment by liangjingkanji** [comment]
最好的地方还是有我当技术客服

**Comment by zqr95518** [comment]
但是我这个现有工程是java的改不了kt，只能用混合的，全家桶估计用不上了

**Comment by 025nju** [comment]
啊？不支持java项目吗？部分功能用不了是吗

**Comment by liangjingkanji** [comment]
> 啊？不支持java项目吗？部分功能用不了是吗

1. 可能存在语法问题, 比如会要求你lambda返回null
2. 如果项目中存在部分java可以在kotlin写函数返回adapter给java调用解决
3. 如果你完全不打算使用kotlin, 那么我不是那么推荐你使用该库
