### ISSUE TITLE
关于最新版1.3.57默认加载更多行为

### ISSUE THREAD

**Issue by qq570026938** [liangjingkanji/BRV#140]
## 问题描述
最新版默认加载更多导致很多不用上拉加载的页面，在上拉过程中重新刷新页面问题，甚至导致了数据重复，因为上拉加载走onRefresh()，反而影响了正常使用，并且这种页面还要去主动添加不上拉加载的代码，工作量还提升了
### 期望行为
上拉加载还是完全由个人去判断是否开启就很合理啊，需要分页加载的长列表毕竟就那几个，而用到PageRefreshLayout的页面有很多，都默认加载很难受
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
一般情况下不需要你手动使用showContent

如果你使用showContent有参数指定是否有更多页

**Comment by qq570026938** [comment]
> 一般情况下不需要你手动使用showContent
> 
> 如果你使用showContent有参数指定是否有更多页

嗯，我没有手动调用showContent，比如我的详情页面，外侧是PageRefreshLayout包裹的，
 pageRecord.onRefresh {
                scope {
                    *****
                }
            }.refresh()
            一些数据，加载完其实就可以了，之前是上拉加载的时候有个“没有更多数据的提示”,现在上拉直接是“加载完成”，可以上拉了，而且数据还会刷新一边，这样我是不是还要添加代码控制不要上拉加载，类似的页面还有很多，比如搜索提示固定的，比如收藏记录本地数据也是固定的，现在上拉反而导致数据重复加载了

**Comment by liangjingkanji** [comment]
这种页面我认为应该手动xml里面关闭加载很多功能吧

**Comment by liangjingkanji** [comment]
因为SmartRefreshLayout是默认开启上拉加载的, 我showContent默认禁用加载更多不合适吧?

**Comment by liangjingkanji** [comment]
如果你认为大部分列表都不需要加载更多, 那应当直接关闭`PageRefreshLayout`的默认加载更多行为

因为有些page如果不使用showContent而是使用`refresh/autoRefresh`那依然会导致超出开发者预期产生上拉加载

**Comment by liangjingkanji** [comment]
关于默认禁用上拉加载是属于我的历史问题, 后期会更加谨慎避免此类问题. 

主要是SmartRefreshLayout的设计如此, 很多开发者从SM迁移过来或者去SM查看代码示例, 我只能尽可能符合`预期行为`

**Comment by qq570026938** [comment]
> 这种页面我认为应该手动xml里面关闭加载很多功能吧

好吧，之前也没考虑PageRefreshLayout自身默认加载问题，因为我使用的时候默认是不加载的，现在很多页面出现了上拉加载的问题，PageRefreshLayout和showContent相互独立是合理的，后面使用的人应该就不会出现这种问题了

**Comment by liangjingkanji** [comment]
是我的严重失误, 后续会避免, 建议每次更新前查看下更新日志. 我每次都会明确标注改动

后续针对危险变更行为我会在[更新日志](https://liangjingkanji.github.io/BRV/updates/)中框选标注出来

> 对于文档或代码你也可以进行审阅修改

**Comment by qq570026938** [comment]
> 是我的严重失误, 后续会避免, 建议每次更新前查看下更新日志. 我每次都会明确标注改动
> 
> 后续针对危险变更行为我会在[更新日志](https://liangjingkanji.github.io/BRV/updates/)中框选标注出来
> 
> > 对于文档或代码你也可以进行审阅修改

嗯嗯

**Comment by liangjingkanji** [comment]
为什么不close issue
