### ISSUE TITLE
请教关于自定义adapter

### ISSUE THREAD

**Issue by boboqun** [liangjingkanji/BRV#142]
我想在列表里添加一个选图片的功能，想直接用 https://github.com/LuckSiege/PictureSelector 提供的adapter（下边称呼adapter1） 。
我按照您的demo创建了一个新的ViewModel类型 其中一个 mediaData 用于存储这一项的媒体信息
我现在在onBind里初始化adapter1并为其提供data，这个data是由 mediaData 处理转化而来的。

现在面临的问题是滑动列表时会导致媒体数据重复。
想请教一下如何正确的使用自定义adapter 并合理保存数据。
提前感谢大佬 /鞠躬

**Comment by liangjingkanji** [comment]
既然PictureSelector提供Adapter你别用BindingAdapter了

**Comment by liangjingkanji** [comment]
onBind是每次滑动列表都会反复执行的, 对应`RecyclerView.Adapter`的`onBindViewHolder`函数, 你在这里创建视图就会反复创建

**Comment by boboqun** [comment]
嗯那，那，，怎么用他这个呢 代码应该写到哪个位置？

> 既然PictureSelector提供Adapter你别用BindingAdapter了

**Comment by liangjingkanji** [comment]
```kotlin
rv.adapter = PictureSelector的Adapter
```

**Comment by liangjingkanji** [comment]
原来你在item里面插入一个嵌套的rv, 我估计你没有把这个嵌套rv的数据映射到item. 导致列表复用的时候错乱了.

请每次更新item都要保存数据到item中, 因为rv的itemView是复用的, 如果你不保存就会复用上一次的数据

**Comment by boboqun** [comment]
嗯那，这里有一个新的问题。如果我想保存PictureSelector提供的Adapter到Item的数据模型里面，但是这个数据模型是用kotlin Serialization﻿进行的序列化，而那个adapter并没有这样序列化。我应该怎样给他提供一个序列化方法呢？
报错是这样的
 Serializer has not been found for type 'GridImageAdapter?'. To use context serializer as fallback, explicitly annotate type or property with @Contextual
我没有找到自定义serializer或者其他 的方法。您可以帮忙给一个教程之类的地址吗？我甚至没有搜到一点demo。。

**Comment by liangjingkanji** [comment]
使用注解`@Transient`让Serialization忽略这个字段

**Comment by liangjingkanji** [comment]
建议你使用另一个框架 [Net](https://github.com/liangjingkanji/Net/), 里面有使用ks的demo也有提供教程

**Comment by boboqun** [comment]
问题找到了。我我在添加数据时犯了错误。
我的错误代码大概如下：
我用一个hashMap存储数据源类型


 ```kotlin
    private val modelsFromServer: HashMap<String, Any> = HashMap()
         val items = mutableListOf<Any>()
        // 类型A
        val mediaViewDef = SuperTableMediaGridViewModel(
            "viewDef.title",
            ArrayList(),
            null
        )
        modelsFromServer["a"] = mediaViewDef
        // 类型B
        val superTableDividerViewModel = SuperTableDividerViewModel("sss")
        modelsFromServer["b"] = superTableDividerViewModel
        for (index in 1..100) {
            val any = modelsFromServer["a"]
            if (any is SuperTableMediaGridViewModel) {
                items.add(any)
            }
        }
        val any = modelsFromServer["b"]
        if (any is SuperTableDividerViewModel) {
            items.add(any)
        }
        binding.rv.models = items
 ```

这样会导致数据错乱。解决方案时 不要这样直接使用hashMap内取出的对象 `items.add(any)` 而是新建一个对象 `items.add(SuperTableDividerViewModel("xxx"))`。
