### ISSUE TITLE
侧滑删除的分组->删除分组0内的item后收缩分组，分组[-]被删除,删除到最后一个分组时点击闪退

### ISSUE THREAD

**Issue by Wudelin** [liangjingkanji/BRV#145]
## 问题描述
侧滑删除的分组->删除分组0内的item后收缩分组，分组[-]被删除,删除到最后一个分组时点击闪退

## 如何复现
建议步骤:
-  可以在Sample复现
- 主要代码

## 截图
<img width="1233" alt="3C2141F0EEA5362951AE9901DAF80E43" src="https://user-images.githubusercontent.com/32236003/163138469-8bfe5215-efce-4255-a24f-90a65a9a6365.png">

https://user-images.githubusercontent.com/32236003/163139019-854abcd0-7a51-4744-80d0-f0029b6be15c.mp4

异常堆栈信息或者手机截图/视频

## 版本
- BRV: 最新版

**Comment by Wudelin** [comment]
选择模式下，当item全移除时，toggle失效

**Comment by liangjingkanji** [comment]
fork仓库给我复现问题, demo本身没有为分组子列表启用侧滑删除. 我不清楚你是如何侧滑删除的

**Comment by liangjingkanji** [comment]
因为你侧滑删除的时候没有删除当前分组item的`itemSublist`里面的数据
