### ISSUE TITLE
XML加载图标不显示

### ISSUE THREAD

**Issue by BaiMingxu** [liangjingkanji/BRV#146]
大佬为什么我在数据类里这么写不显示图片？而您的就显示。
<img width="1106" alt="截屏2022-04-13 18 49 08" src="https://user-images.githubusercontent.com/22886455/163165006-b601fb67-fdf5-4bb9-bb5c-c9c75f6cf355.png">
<img width="443" alt="截屏2022-04-13 18 49 17" src="https://user-images.githubusercontent.com/22886455/163165023-cd93bb53-b81c-4ee6-a70f-bfdc395b37de.png">

**Comment by liangjingkanji** [comment]
应该是demo里面用的是[Engine](https://github.com/liangjingkanji/Engine)库里面的[DataBindingComponent](https://github.com/liangjingkanji/Engine/blob/HEAD/engine/src/main/java/com/drake/engine/databinding/DataBindingComponent.kt#L5)里面定义的`android:src`

**Comment by liangjingkanji** [comment]
不对, 我点击属性并没有跳转到对应的函数

你应该是抄代码但是没有抄DataBinding相关代码吧?

**Comment by liangjingkanji** [comment]
你这是什么字体啊?

**Comment by BaiMingxu** [comment]
Operator Mono Lig 字体，可以了，是因为没那个文件，但是我在您的xml里点击就是跳转到GroupModel里，好奇怪。我还有两个问题大佬，
1.  rv{}.models = getData()获取后台数据是不是不能这么写，只能成功获取数据后在rv.models = it
2.折叠吸顶的情况我必须
it.forEach { it1 ->
                it1.itemExpand = true
                it1.itemHover = true
}才可以，我下午遇到了这两个问题。
大佬方便加您一下微信么？或者有群么？以后可以像大佬们学习。

**Comment by liangjingkanji** [comment]
README就有群号

**Comment by liangjingkanji** [comment]
1. 如果你使用的是协程网络请求[Net](https://github.com/liangjingkanji/Net/)可以这么写, 否则不行
2. 如果你使用的Gson会导致默认值无效, 的确需要这么做. 如果你使用的[kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization)完全可以直接设置字段默认值为true

[kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization)是我最推荐的序列化框架, 在Net中有做详细介绍

**Comment by BaiMingxu** [comment]
谢谢您，明白了。

**Comment by liangjingkanji** [comment]
我说的点击跳转到方法, 是点击属性`android:src`等xml属性
