### ISSUE TITLE
分组模式下，怎么使用ViewBinding呢

### ISSUE THREAD

**Issue by Weightang** [liangjingkanji/BRV#149]
在分组模式下，不使用DataBinding,使用ViewBinding，怎么分别绑定视图

**Comment by Weightang** [comment]
应该使用实现接口方式，在model 实现onBind 的方式使用？

**Comment by liangjingkanji** [comment]
分组模式和你使用什么来绑定数据没关系吧, 三种绑定方式都可以写分组

demo里面不是有演示如何使用ViewBinding绑定视图吗? 你找到view然后bind一下就可以了

无论是写onBind函数还是实现ItemBind接口都可以用ViewBinding

**Comment by Weightang** [comment]
在分组模模式下，有多个itemView 怎么区分绑定
<img width="454" alt="image" src="https://user-images.githubusercontent.com/19605094/163512940-7495fbb8-8659-43b0-b12c-0efd42e0a1a6.png">

**Comment by Weightang** [comment]
我试试看，用getItemViewType

**Comment by liangjingkanji** [comment]
onBind的`this`是`BindViewHolder`, 里面有个字段itemViewType

demo里面的多类型不是有演示

**Comment by liangjingkanji** [comment]
onBind就是Adapter的`onBindViewHolder`方法的简化版本

**Comment by Weightang** [comment]
感谢回答，从brvah 过来的

**Comment by liangjingkanji** [comment]
如果从brvah迁移可以直接实现ItemBind复制原有代码(当然没必要一定迁移旧的页面)

但是我更推荐使用DataBinding的形式, 代码更少更安全, 且MVVM方便版本迭代
