### ISSUE TITLE
datadingding自动刷新item

### ISSUE THREAD

**Issue by q3920687** [liangjingkanji/BRV#15]
大佬问下使用databinding修改完item子控件的数据之后，只刷新item的子控件要怎么实现？

**Comment by liangjingkanji** [comment]
DataBinding自己就会去刷新绑定的控件, 不需要你手动刷新Item, 这也是DataBinding做局部刷新的强大之处

具体请看: [选择模式](https://github.com/liangjingkanji/BRV/blob/master/sample/src/main/java/com/drake/brv/sample/ui/fragment/CheckModeFragment.kt)

**Comment by liangjingkanji** [comment]
如果不知道如何使用DataBinding数据绑定刷新, 请阅读: [DataBinding最全使用说明
](https://juejin.cn/post/6844903549223059463)

**Comment by q3920687** [comment]
好的 感谢大佬

**Comment by liangjingkanji** [comment]
有任何使用问题可以提issues, 如果觉得回复不够及时可以点击QQ群图标进群问
