### ISSUE TITLE
代码下载在本地无法跑报如下错误

### ISSUE THREAD

**Issue by douya40** [liangjingkanji/BRV#150]
import com.drake.brv.utils.BRV

**Comment by liangjingkanji** [comment]
你发的什么东西?

**Comment by douya40** [comment]
import com.drake.brv.utils.BRV  这个路径找不到

**Comment by liangjingkanji** [comment]
你自己搜下这个文件是否存在于你下载的项目中, 在Git仓库中明显存在这个文件的

**Comment by liangjingkanji** [comment]
本问题将开启关闭倒计时....

**Comment by liangjingkanji** [comment]
3

**Comment by liangjingkanji** [comment]
2

**Comment by XuHX** [comment]
![1650012052(1)](https://user-images.githubusercontent.com/25903912/163547992-8f9bac8e-ae3a-41b7-b907-ff51cae859b4.png)

**Comment by douya40** [comment]
直接跑跑步起来

**Comment by liangjingkanji** [comment]
> ![1650012052(1)](https://user-images.githubusercontent.com/25903912/163547992-8f9bac8e-ae3a-41b7-b907-ff51cae859b4.png)

你怎么不单独开个问题

**Comment by liangjingkanji** [comment]
检查文件不用运行项目

另外备注下你的AS和Gradle版本

**Comment by douya40** [comment]
AS 3.6.3和Gradle 版本5.6.4

**Comment by liangjingkanji** [comment]
> AS 3.6.3和Gradle 版本5.6.4

你的AS过于古老, 建议你升级最新正式版本

**Comment by douya40** [comment]
我的项目在这个版本上，升级很多要更新

**Comment by liangjingkanji** [comment]
> 我的项目在这个版本上，升级很多要更新

新版本AS兼容旧项目, 我也用最新AS打开过gradle3.2的项目. 另外你要是不升级AS可能经常遇到此类问题. 我不可能兼顾到每个版本

**Comment by liangjingkanji** [comment]
你的AS版本起码落后了2年

**Comment by XuHX** [comment]
> 

和标题结果一样，代码跑不起来

**Comment by liangjingkanji** [comment]
> > 
> 
> 和标题结果一样，代码跑不起来

你是Demo无法运行是吗? 可能是国内访问仓库慢的问题吧

**Comment by XuHX** [comment]
> > > 
> > 
> > 
> > 和标题结果一样，代码跑不起来
> 
> 你是Demo无法运行是吗? 请备注你的AS和Gradle版本. 你也可能是国内访问仓库慢的问题吧, 多试几次或者使用镜像库

改成最新的0.0.58可以，demo里的0.0.51就不行

**Comment by liangjingkanji** [comment]
> > > > 
> > > 
> > > 
> > > 和标题结果一样，代码跑不起来
> > 
> > 
> > 你是Demo无法运行是吗? 请备注你的AS和Gradle版本. 你也可能是国内访问仓库慢的问题吧, 多试几次或者使用镜像库
> 
> 改成最新的0.0.58可以，demo里的0.0.51就不行

既然如此那我更新下

**Comment by liangjingkanji** [comment]
看样子你不想发起PR那我就马上更新了

**Comment by liangjingkanji** [comment]
本问题长期没有回复将被自动关闭
