### ISSUE TITLE
PageRefreshLayout调用刷新方法出现循环调用

### ISSUE THREAD

**Issue by Wang-Yumin** [liangjingkanji/BRV#151]
## 问题描述
使用PageRefreshLayout包裹RecyclerView，在代码中调用PageRefreshLayout的refresh()方法，会出现循环调用的情况，导致PageRefreshLayout的onRefresh回调方法不断触发，无休止请求接口，使用autoRefresh()方法没有此问题。

### 期望行为
调用refresh()方法使得onRefresh仅回调一次

## 版本
- BRV: 1.3.58

**Comment by liangjingkanji** [comment]
本来就是一次，你能否fork仓库复现问题发我

**Comment by Wang-Yumin** [comment]
非常感谢，排查了，是我的问题，是因为在接口请求结束时渲染列表调用了PageRefreshLayout的showContent()方法，该方法没有传参数导致触发了onRefresh回调方法。

**Comment by liangjingkanji** [comment]
`showContent`并不会触发onRefresh
