### ISSUE TITLE
CoordinatorLayoutFragment布局无数据时显示样式问题

### ISSUE THREAD

**Issue by Wang-Yumin** [liangjingkanji/BRV#152]
## 问题描述
CoordinatorLayoutFragment布局在下方使用多个fragment，加载无数据时默认状态图片不能居中，部分遮挡并且无法向上滑动导致视图不够美观

### 期望行为
优化视图

## 截图
截图无法上传，可尝试将仓库代码CoordinatorLayoutFragment页面getData()方法返回空数组后运行查看

## 版本
- BRV: 1.3.58

**Comment by liangjingkanji** [comment]
这是CoordinatorLayout的问题. 你可以将缺省页使用`NestedScrollView`包裹住即可正常滑动

**Comment by liangjingkanji** [comment]
我还以为文档中有提及此处, 可能是被忽略了
