### ISSUE TITLE
分组列表如何获取选中的一级列表的position。

### ISSUE THREAD

**Issue by guy621** [liangjingkanji/BRV#154]
## 问题描述
点击展开之后能get到的position长度是加了展开数据之后的位置。能否直接获取在原Datalist中的position即不曾加已展开的二级列表长度的position
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
Model会实现`ItemExpand`, 其有属性`itemGroupPosition`即为你需要的值

**Comment by guy621** [comment]
好的，感谢大佬回复
