### ISSUE TITLE
大佬 有个使用smartfreshlayout的问题

### ISSUE THREAD

**Issue by Demonhuang** [liangjingkanji/BRV#155]
## 如何复现
建议步骤:
-  fragment里通过navagation跳转fragment 
- 跳转的fragment里有列表，现在跳转这fragment里的列表无法下拉刷新
- 但我发现如果给rv 不设置layoutManager就可以下拉刷新 ，但设置就无法下拉刷新了

期待您的回复

**Comment by liangjingkanji** [comment]
能fork仓库用demo复现问题吗

**Comment by Demonhuang** [comment]
可以加个联系方式吗 我代码给你 我的qq 515386338

**Comment by liangjingkanji** [comment]
不能fork本仓库来复现吗?

**Comment by Demonhuang** [comment]
是公司项目。。所以

**Comment by liangjingkanji** [comment]
那你还发我...

**Comment by liangjingkanji** [comment]
你可以加群或者上传GitHub私有仓库然后邀请我权限

**Comment by Demonhuang** [comment]
群给我一个吧

**Comment by liangjingkanji** [comment]
本仓库主页不够明显吗

**Comment by Demonhuang** [comment]
添加了 麻烦您通过下

**Comment by liangjingkanji** [comment]
解决了吗
