### ISSUE TITLE
请教侧滑背景实现思路

### ISSUE THREAD

**Issue by boboqun** [liangjingkanji/BRV#158]
## 问题描述
<img width="769" alt="Snipaste_2022-04-23_15-52-15" src="https://user-images.githubusercontent.com/20718624/164885715-a3d9eac6-0444-4160-a460-bf766fe1c097.png">
类似截图里这样，侧滑有一个“删除”字样的背景。请问大佬可以提供个实现思路嘛？
再更进一步，如果这个背景不只是背景而是个可选的菜单呢？

**Comment by liangjingkanji** [comment]
为Item添加整个自定义View

[文档说明](https://liangjingkanji.github.io/BRV/swipe/)

> Android建议你不要抄袭iOS的效果, 你这样会容易和Android手机的全屏手势冲突. Android一般是长按弹出菜单

**Comment by boboqun** [comment]
好的，谢谢大佬
