### ISSUE TITLE
可以将APK一起提交GitHub吗？有些依赖不能下载，demo就不能查看

### ISSUE THREAD

**Issue by yuandoudou928** [liangjingkanji/BRV#159]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
GitHub的安装包都在Release页面显示, 不过貌似很多人不知道, 那我放主页链接吧

**Comment by liangjingkanji** [comment]
README已经提供下载地址
