### ISSUE TITLE
怎么更新单条的数据？

### ISSUE THREAD

**Issue by Alexxiaopang** [liangjingkanji/BRV#16]
如题，我修改了rv的某个item的数据，怎么更新单个item，不全局notify

**Comment by liangjingkanji** [comment]
BRV继承RecyclerViewAdapter.  支持其所有局部刷新函数. 不过我更推荐使用DataBinding的自动刷新UI功能
具体请阅读: [刷新数据](https://liangjingkanji.github.io/BRV/refresh-data/)

**Comment by boboqun** [comment]
现在 models 里是一个 List<Any?>?，是不可变的，请问怎么做才能比较优雅地修改单个item的数据呢？

**Comment by liangjingkanji** [comment]
> 现在 models 里是一个 List<Any?>?，是不可变的，请问怎么做才能比较优雅地修改单个item的数据呢？

1. 使用`mutable`而不是`models`
2. 你为models赋值的是一个MutableList, 那么你直接使用这个`MutableList`更新不就好了吗?
3. 使用DataBinding, 直接取出Model修改值会自动更新View
