### ISSUE TITLE
看了下文档，能提个建议吗？

### ISSUE THREAD

**Issue by JsonCooler** [liangjingkanji/BRV#160]
### 文档中未看到直接使用binding.xx.setOnclilListener 或者binding.xxx.setText() 都使用了DataBinding我觉得可以改改不需要findViewBind来设置点击事件或者数据了

**Comment by liangjingkanji** [comment]
有的人很抗拒DataBinding, 甚至不允许依赖, 坚持使用ViewBinding. 我只是演示下而已

**Comment by liangjingkanji** [comment]
根据业务场景我也是提供了三种方式来实现数据的绑定

**Comment by liangjingkanji** [comment]
如果全用DataBinding, 项目示例可以更加简短, 不过现在也完爆所有同类型框架的Demo
