### ISSUE TITLE
PageRefreshLayout是否支持创建一个base_empty_layout.xml，然后里面的元素内容自定义

### ISSUE THREAD

**Issue by LeonShannon** [liangjingkanji/BRV#162]
### 期望行为
创建一个base_empty_layout.xml，然后里面的元素内容自定义，比如图片的内容，文字的内容。
因为，一个项目里面，大概率是统一的风格，只是不同的模块，缺省图/文字内容不一致。
我们目前的方式貌似只可以定义不同的xml，或者说我没有找到

## 版本
- BRV:1.3.57

**Comment by liangjingkanji** [comment]
文档中有提及到使用的是StateLayout

xml属性: `app:empty_layout="@layout/layout_empty"`
kt代码: `emptyLayout = R.layout.layout_empty`

[自定义缺省页使用文档](https://liangjingkanji.github.io/StateLayout/#_2)

**Comment by LeonShannon** [comment]
多谢
