### ISSUE TITLE
使用statelayout报No StateLayout emptyLayout is set

### ISSUE THREAD

**Issue by sdjwj1118** [liangjingkanji/BRV#163]
## 问题描述
使用statelayout报No StateLayout emptyLayout is set
## 如何复现

- 主要代码
- 请问 我在xm中设置了emptylayout 为什么showempty的时候报了一个No StateLayout emptyLayout is set错误
<com.drake.statelayout.StateLayout
        android:id="@+id/state"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:empty_layout="@layout/view_statelayout_empty">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </com.drake.statelayout.StateLayout>

view?.rv?.linear()?.setup {
            addType<CountryCodeResponse>(R.layout.item_country_code)
            onBind {

            }
        }?.models = null
        val state = state()
        state.showEmpty()
## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by sdjwj1118** [comment]
已解决 找了半天才发现要在baseapplication里配置 感觉文档里可以显示的补充上这个

**Comment by liangjingkanji** [comment]
你对state()方法可能有误解，建议看下方法注释，这不是findViewById类似的方法

**Comment by liangjingkanji** [comment]
> 已解决 找了半天才发现要在baseapplication里配置 感觉文档里可以显示的补充上这个

已经补充到[缺省页](https://liangjingkanji.github.io/BRV/state/)
