### ISSUE TITLE
分组展开,子项目在屏幕上可视的问题

### ISSUE THREAD

**Issue by x200516** [liangjingkanji/BRV#164]
如展开底部分组的子项目时,recyclerView不会自动向上滑动,导致子项目屏幕上不可视

象ExpandableListView自动屏幕上可视展开的子项目

 版本
- BRV:1.3.62
- Gradle: 6.7.1
- Android Studio:  4.2.2
- Android:11

**Comment by liangjingkanji** [comment]
这种需求应该是`scrollTop`展开同时当前条目滑动到顶部, 但是似乎没有真的到顶部而是保证分组自己显示
```
/**
 * 展开子项
 * @param scrollTop 展开同时当前条目滑动到顶部
 * @param depth 递归展开子项的深度, 如等于-1则代表展开所有子项, 0表示仅展开当前
 * @return 展开后新增的条目数量
 */
fun expand(scrollTop: Boolean = false, @IntRange(from = -1) depth: Int = 0): Int
```

**Comment by liangjingkanji** [comment]
请使用最新版本修复此问题
