### ISSUE TITLE
大佬 你这个框架什么时候能加上各种酷炫动画效果

### ISSUE THREAD

**Issue by xuxinjiang** [liangjingkanji/BRV#167]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
一般应用都不会在列表做"酷炫动画", 建议你自己实现, 有提供动画接口和常见动画
