### ISSUE TITLE
大佬有QQ群吗 解决问题那种 如果没有 我愿贡献800个人的安卓群给你群主转给你

### ISSUE THREAD

**Issue by xuxinjiang** [liangjingkanji/BRV#168]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
README有提到群号, 你可以推荐群友加入, 会有人解决问题的
