### ISSUE TITLE
添加头布局和尾部局是是否支持添加View

### ISSUE THREAD

**Issue by Sunyuwumengsheng** [liangjingkanji/BRV#169]
## 问题描述
一、我在使用时需要添加头布局banner，所以我在接口请求成功后使用了addHeader方法添加头布局，但是造成了一个问题当我执行刷新后会重复执行addHeader,我只能先移除在添加header
二、是否可以直接addHeaderView()
### 期望行为
可以先设置header ，后续通过setHeaderData()类似方法刷新Header数据

## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
直接给models判断下是否已存在就行了, 或者使用`if(!page.loaded)`才执行添加

**Comment by liangjingkanji** [comment]
另外由于添加View无法获取到和layoutId一样的唯一Id所以不是很方便, 考虑到没有什么View是无法在xml中声明所以暂时不考虑

我更推荐使用`ContactAdapter`来实现头布局和脚布局
