### ISSUE TITLE
第一次进入列表 下拉刷新圈圈一直转不消失 如果是先上拉加载更多再下拉刷新则正常

### ISSUE THREAD

**Issue by sdjwj1118** [liangjingkanji/BRV#170]
## 如何复现
这是我的源码 在第一次进入列表的时候 如果先下拉刷新 刷新动画会一直存在，此时通过log发现已经发起请求了但是没有关闭动画，如果第一次进来是先上拉加载更多 再下拉刷新则正常消失动画 不知道是这段代码哪里写的有误
```kotlin
page.onRefresh {
    scope {
        val result =
            Post<BaseResponse<BasePageResponse<UserRunPointResponse>>>("userRunPoint/findUserRunPointPage"){
                json(
                    "page" to index,
                    "limit" to 10,
                    "userId" to CacheUtil.getUser()?.userId,
                    "deviceNo" to CacheUtil.getDeviceNo()
                )
            }.await()

        addData(result.data!!.data) {
            result.data!!.hasNext
        }
    }
}.showLoading()
```
## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:最新版
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
你的示例代码没有问题, 能否fork仓库来复现问题?

**Comment by sdjwj1118** [comment]
我在scope{}后增加了一个toast打印 发现是正常在scope结束后打印 但动画依旧没有消失，我把showloading换成了.refresh()就正常了 ，这是我activity里的代码，brv版本1.3.62
val page = view.rv.page()
        view.rv.linear().setup {
            addType<UserRunPointResponse>(R.layout.item_historical_track)
            onBind {
                val binding = ItemHistoricalTrackBinding.bind(itemView)
                val userRunPointResponse: UserRunPointResponse = getModel();
                binding.tvMileage.text = userRunPointResponse.mileage.toString()
                binding.tvStartAddress.text = userRunPointResponse.beginAddress.toString()
                binding.tvEndAddress.text = userRunPointResponse.endAddress.toString()
                binding.tvStartTime.text = userRunPointResponse.beginTime?.formatDate()
                binding.tvEndTime.text = userRunPointResponse.endTime?.formatDate()

            }
            onClick(R.id.btn_detail) {

            }
        }
        view.rv.addItemDecoration(ItemDecoration(me, 20.dp))
        page.onRefresh {
            scope {
                val result =
                    Post<BaseResponse<BasePageResponse<UserRunPointResponse>>>("userRunPoint/findUserRunPointPage")
                    {
                        json(
                            "page" to index,
                            "limit" to 10,
                            "userId" to CacheUtil.getUser()?.userId,
                            "deviceNo" to CacheUtil.getDeviceNo()
                        )
                    }.await()

                addData(result.data!!.data) {
                    result.data!!.hasNext
                }
            }
            toast("执行完scope")
        }.refresh()

**Comment by liangjingkanji** [comment]
scope是回调执行的, 你在scope里面的最后一行打日志才是正确的
```
scope{

  Log.i("日志", "结束")
}
```

**Comment by sdjwj1118** [comment]
scope {
                val result =
                    Post<BaseResponse<BasePageResponse<UserRunPointResponse>>>("userRunPoint/findUserRunPointPage")
                    {
                        json(
                            "page" to index,
                            "limit" to 10,
                            "userId" to CacheUtil.getUser()?.userId,
                            "deviceNo" to CacheUtil.getDeviceNo()
                        )
                    }.await()
                addData(result.data!!.data) {
                    result.data!!.hasNext
                }
                Log.i("日志", "结束")
            }

也是正常打印的，整个请求流程应该是已经结束的。如果不用.showloading()用.refresh()是没问题的

**Comment by liangjingkanji** [comment]
请你使用```包裹住代码, 可以参考我给你重新编辑的内容, 不然可读性太差我看不懂

**Comment by liangjingkanji** [comment]
你fork仓库在sample里面复现这个问题吧, 我也很难看出来问题所在

**Comment by sdjwj1118** [comment]
好的 抱歉 
``
val page = view.rv.page()
        view.rv.linear().setup {
            addType<UserRunPointResponse>(R.layout.item_historical_track)
            setAnimation(AnimationType.SLIDE_LEFT)
            onBind {
                val binding = ItemHistoricalTrackBinding.bind(itemView)
                val userRunPointResponse: UserRunPointResponse = getModel();
                binding.tvMileage.text = userRunPointResponse.mileage.toString()
                binding.tvStartAddress.text = userRunPointResponse.beginAddress.toString()
                binding.tvEndAddress.text = userRunPointResponse.endAddress.toString()
                binding.tvStartTime.text = userRunPointResponse.beginTime?.formatDate()
                binding.tvEndTime.text = userRunPointResponse.endTime?.formatDate()

            }
            onClick(R.id.btn_detail) {

            }
        }
        view.rv.addItemDecoration(ItemDecoration(me, 20.dp))
        page.onRefresh {
            scope {
                val result =
                    Post<BaseResponse<BasePageResponse<UserRunPointResponse>>>("userRunPoint/findUserRunPointPage")
                    {
                        json(
                            "page" to index,
                            "limit" to 10,
                            "userId" to CacheUtil.getUser()?.userId,
                            "deviceNo" to CacheUtil.getDeviceNo()
                        )
                    }.await()
                addData(result.data!!.data) {
                    result.data!!.hasNext
                }
                Log.i("日志", "结束")
            }
        }.showLoading()
 ``

**Comment by sdjwj1118** [comment]
![image](https://user-images.githubusercontent.com/33438073/167530192-b4e7e69d-4746-45a3-a44a-70bee07bbf90.png)

**Comment by liangjingkanji** [comment]
有fork仓库吗?

**Comment by liangjingkanji** [comment]
找到`PageCoroutineScope`在

```kotlin
override fun finally(e: Throwable?) {
    super.finally(e)
    if (e == null || e is CancellationException) {
        page.showContent() // 这个位置打断点看是否执行到
    }
    page.trigger()
}
```

**Comment by zhuzhutai** [comment]
我提供一个奇特的思路，
我他么项目依赖复杂，用的
compileOnly("io.github.scwang90:refresh-layout-kernel:2.0.6")      //核心必须依赖
也出现无法回弹的问题了...
恢复成implementation就好了
