### ISSUE TITLE
请更新使用例子

### ISSUE THREAD

**Issue by mdddj** [liangjingkanji/BRV#172]
## 问题描述
<img width="501" alt="image" src="https://user-images.githubusercontent.com/29020213/167780170-fe7bfee3-acb9-4f01-a1c3-8b97c6912b8e.png">
无法下载apk

### 期望行为

正常下载apk
## 如何复现

点击链接没有触发下载

建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
已解决
