### ISSUE TITLE
选择模式 如果下拉刷新 期望保持模式不变

### ISSUE THREAD

**Issue by z876335662** [liangjingkanji/BRV#173]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
你自己对比下请求的数据是否一致即可, 一致就不更新数据
