### ISSUE TITLE
关于无网络情况下的使用showLoading问题

### ISSUE THREAD

**Issue by kinghom** [liangjingkanji/BRV#174]
## 问题描述
我这边有个需求：
在有网络状态下，进来 执行showLoading——判断有网络——访问接口——接口返回数据 (这是正常的)
在没有网络状态下，进来 执行showLoading——判断无网络——查询本地数据库——返回数据 (这里不正常了，加载圈圈一直转)
### 期望行为
是否有强制关闭loading状态的函数
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
这个问题是因为开启了网络检查，稍等我更新下

**Comment by kinghom** [comment]
已经收到你的飞鸽传书啦....

**Comment by liangjingkanji** [comment]
我查看了下源码并没有检查网络状态, 你没有提供BRV版本, 建议你升级到最新版本

**Comment by kinghom** [comment]
之前1.3.62 现在升级到1.3.63  问题依然存在

**Comment by liangjingkanji** [comment]
Demo能复现吗?

**Comment by liangjingkanji** [comment]
等到花儿都快谢了~

**Comment by kinghom** [comment]
![微信图片_20220512140208](https://user-images.githubusercontent.com/23691629/168002641-85ec18b0-3a7f-49fc-8c5a-c4541751d487.png)
不好意思 来晚了
我加了个runable 就可以解决了 如果不加还是一直转圈圈 目前不知道什么原因

**Comment by liangjingkanji** [comment]
那你在demo复现吧

**Comment by kinghom** [comment]
我晚点复现了 再传上来

**Comment by liangjingkanji** [comment]
我尝试去除`RefreshFragment`onRefresh中的延迟也是显示正常

**Comment by kinghom** [comment]
没能复现，应该是我数据接口问题

**Comment by liangjingkanji** [comment]
这种非崩溃的业务问题建议还是demo复现排查, 否则很难发现问题

**Comment by kinghom** [comment]
好的 非常感谢
