### ISSUE TITLE
请问多布局使用Viewbinding的问题

### ISSUE THREAD

**Issue by lhj1079947827** [liangjingkanji/BRV#175]
## 问题描述

请问如果我使用单类型多布局，多类型多布局时候，不同的布局的viewbinding如果获取到，demo中值提供了单布局一种类型的例子

## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
你说demo没有提供多类型的例子是吗?  MultiTypeFragment不就是多类型吗? 

多类型和单一类型获取viewBinding没有区别, 只是多类型需要获取之前判断下类型而已

**Comment by lhj1079947827** [comment]
是的

**Comment by lhj1079947827** [comment]
你的demo中，值一中数据类型获取一个viewbinding的，没有多个数据获取多个不同布局的viewbinding和一个数据类型多布局的viewbinding。

**Comment by liangjingkanji** [comment]
判断下itemViewType即可, 我不可能把所有可能情况写一个遍

**Comment by lhj1079947827** [comment]
我在你的onCreate方法中来获取viewbinding是可以的吧

**Comment by lhj1079947827** [comment]
我看你的例子是在onBind中获取

**Comment by liangjingkanji** [comment]
可以的
onCrate对应onCreateViewHolder, 文档中有提及[生命周期](https://liangjingkanji.github.io/BRV/lifecycle/)

**Comment by lhj1079947827** [comment]
我在你的dome中试试

**Comment by liangjingkanji** [comment]
我写了多类型有人又会问怎么写单一类型, 而且支持三种数据绑定方式, 我不可能围绕ViewBinding写六种示例

而且我并不推荐ViewBinding这种原始写法

**Comment by lhj1079947827** [comment]
databinding我也想用。项目不允许

**Comment by liangjingkanji** [comment]
你直接使用ViewBinding来赋值数据的话, 我推荐你去实现`itemBind`(这是也就是在数据模型中为视图赋值), 避免在onBind这种回调方法里面代码太厚重

**Comment by lhj1079947827** [comment]
等会我去弄弄

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/168245743-742ca535-6586-49e2-a618-993ffaf10e6e.png)
](url)
你好我这种获取viewbinding在onBind中使用获取到的Viewbinding就会null，上图我获取的有问题吗

**Comment by liangjingkanji** [comment]
> 可以的, 但是注意多类型要判断类型 onCrate对应onCreateViewHolder, 文档中有提及[生命周期](https://liangjingkanji.github.io/BRV/lifecycle/)

我这里发的文档中有提及, onCreate中it才是itemViewType

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/168246303-d448512d-e008-478a-a6f9-356549026968.png)
](url)
[
![image](https://user-images.githubusercontent.com/20966610/168246466-4ce0a4b0-3785-4beb-9255-b4ba08282351.png)
](url)

**Comment by lhj1079947827** [comment]
请问是我获取的viewbinding有问题吗？

**Comment by liangjingkanji** [comment]
> > 可以的, 但是注意多类型要判断类型 onCrate对应onCreateViewHolder, 文档中有提及[生命周期](https://liangjingkanji.github.io/BRV/lifecycle/)
> 
> 我这里发的文档中有提及, onCreate中it才是itemViewType

我这里不是回复了吗

**Comment by liangjingkanji** [comment]
而且你把item的ViewBinding你给一个外部变量? 每个item都有自己唯一的ViewBinding, 因为他们都有自己的itemView对象

你这样反复覆盖获取的值都是错误的

**Comment by lhj1079947827** [comment]
强哥牛逼，谢谢了啊
