### ISSUE TITLE
关于BRV上拉加载更多的问题与添加适配器级别的上拉加载更多的建议

### ISSUE THREAD

**Issue by atwillhhh123** [liangjingkanji/BRV#176]
## 问题描述
SmartRefreshLayout在某些场景下上拉加载不是太好用（下拉刷新没什么问题），比如手指滑动上拉加载时，加载更多的View出现，此时按住并上下滑动有几率RecyclerView会被底部的加载完成上拉头挡住

或者在某些后台数据不合格（比如item中有图片但是没有返回宽高数据，需要加载后设置宽高），这种item高度不确定会变更场景下上拉加载更多结束后多半RecyclerView会被加载完成的上拉头给挡住

再就是比如BRV的DEMO中的预加载，当加载更多数据无延迟时，快速上划抛掷列表（一定是抛掷快速滚动时），在刚好触发了加载更多并将数据填充到RecyclerView后，此时手指按住RecyclerView，滚动不会停止，必须手指触碰Recycler View两次才会停下，造成了RecyclerView的失灵，并且有几率加载更多时，列表会停住不动，也需要滑动两次

建议参考BRVAH这种本身Adapter添加item来当作加载更多的话，不会受到列表的Item高度变化影响，也不会遮住RecyclerView

## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:1.3.65
- Gradle: 7.1.3
- Android Studio:  Chipmunk
- Android:10

**Comment by atwillhhh123** [comment]
顺便说一下，BRV真好用，东哥牛逼，就是这个上拉加载更多真心建议加一下这种方式的

**Comment by liangjingkanji** [comment]
1. 你说的上拉刷新视图覆盖列表问题可以通过配置`setEnableFooterTranslationContent`和`setEnableFooterFollowWhenLoadFinished`避免

2. 你说的第二点可以通过配置`setDisableContentWhenLoading`在加载时禁止滑动

最后我要说的是目前没有比SmartRefreshLayout更好的刷新实现了, 使用item来做有很强的侵入性.  而且对于现代应用我其实推荐不做上拉刷新视图, 直接预加载就好了

**Comment by atwillhhh123** [comment]
> 

了解了东哥，但是加载时禁止滑动体验稍微差一点，不做上拉刷新视图总感觉用户体验的流畅性上缺了一点，可能是我太吹毛求疵了😂，顺便感谢东哥回复

**Comment by liangjingkanji** [comment]
你说的第二点操作起来感觉也是挺复杂的, 一般情况下根本不存在吧

**Comment by atwillhhh123** [comment]
> 你说的第二点操作起来感觉也是挺复杂的, 一般情况下根本不存在吧

是存在的东哥，我之前写了一个小demo，快速抛掷的话，有4/1的概率，坦白说有点高了，我就有点强迫症了，就和滑动失灵差不多，咱们的Demo也可以复现（加载数据无延时的情况下），总是不经意的时候就出现，如果=需要的话我可以明天写的demo提上来给你看一下

**Comment by liangjingkanji** [comment]
我暂时比较忙, 这个smartRefresh问题你给作者提或者你pr修复下更好

**Comment by atwillhhh123** [comment]
> 我暂时比较忙, 这个SmartRefresh问题你给作者提或者你pr修复下更好

好的东哥，我明天给SmartRefresh提一下，感谢回复，早休息
