### ISSUE TITLE
请教item点击事件如何设置

### ISSUE THREAD

**Issue by boboqun** [liangjingkanji/BRV#178]
## 问题描述
RecyclerView 里 有多种类型的view，但是不需要区分类型 也不需要传递R.id.xx 只是去设置对这个item的点击事件
setOnItemClickListener（）
点击事件里可以获取model类型

请问可以如何设置？

## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by boboqun** [comment]
;```kotlin
        binding.rv.setup {
            addType<SuperTableCaseListModel>(R.layout.item_home_case_list)
            addType<SuperTableDividerViewModel>(R.layout.item_super_table_divider)
            onBind {
              // ...
            }
            onClick {
                val model = getModel<SuperTableCaseListModel>()
                // 不关心 SuperTableDividerViewModel 类型
                // do something
            }
        }
```
我试着这样设置是无效的

**Comment by liangjingkanji** [comment]
因为你没有传入控件id, 建议你看下demo或者文档是如何设置的

```kotlin
rv.linear().setup {
    addType<SimpleModel>(R.layout.item_simple)

// 多个id
    onClick(R.id.item, R.id.image) {
        // Item设置点击事件, 就要给Item的根布局设置一个id, 这里设置的是R.id.item
    }

// 单个id
    R.id.item.onLongClick {
        toast("点击Item")
    }
}.models = getData()
```

**Comment by boboqun** [comment]
我看了demo是您这样写的。但是可不可以不传id ，只是对 rv 的 itemView 设置点击事件？

**Comment by liangjingkanji** [comment]
1. 发我位置看下
2. 设置id很简单, 为了减少学习成本(减少方法)没有直接对itemView本身设置点击事件的

**Comment by boboqun** [comment]
1. 发我位置看下 原谅我这句没看懂
2. 嗯那，是不难，，，但是，，我试试

**Comment by liangjingkanji** [comment]
> 我看了demo是您这样写的。但是可不可以不传id ，只是对 rv 的 itemView 设置点击事件？

我看你说你在demo中看到没有加id的配置点击事件

**Comment by liangjingkanji** [comment]
不过我全局搜索发现文档的确有一处错误

**Comment by boboqun** [comment]
我试了给父View加id的方法
有一个新的问题是，如果子view可以被点击。（其实子view并没有设置点击事件）
点击事件看起来会被分发到子view
如果子view没有设置点击事件 可不可以设置父view消费掉当前点击事件？
<img width="405" alt="Snipaste_2022-05-16_19-13-20" src="https://user-images.githubusercontent.com/20718624/168580687-413a7cd3-6bfa-414d-a691-71e3029eb2bb.png">
像我截图里这样 点击图片区域是子view点击触发 可以去预览图片，其他区域就是父view的点击事件（跳转到案件详情了）

**Comment by liangjingkanji** [comment]
`onClick`就是直接根据id来findViewById, 然后`setOnClickListener`

你给子view配置点击事件然后父view收不到(这不属于本框架的范畴)

**Comment by boboqun** [comment]
嗯那 子view配置了点击事件父view收不到是符合期望的。 但是除了图片区域其他子view都没有设置点击事件，父view也收不到事件吗？
嗯，确实不是框架范畴的问题了，，请您见谅

**Comment by liangjingkanji** [comment]
可能你配置了`clickable`属性, 或者其他拦截点击事件的处理

**Comment by boboqun** [comment]
嗯 不是配置的clickable 是子view本身是clickable的

**Comment by liangjingkanji** [comment]
view默认clickable是false, 你设置为true就会导致拦截父view

**Comment by boboqun** [comment]
我试了别的子view 比如textview 都不影响父view收事件
只有这个子view是个RecyclerView时候 父view就不能收事件了

嗯那 我去搜搜

**Comment by liangjingkanji** [comment]
你怎么不早说是子view是recyclerView, recyclerView默认就被设置了点击事件, 也无法setOnClickListener

所以说不要"云排查"浪费时间, 重要信息你一个不说靠别人猜

**Comment by boboqun** [comment]
嗯 我试了这样是可行的

```kotlin
        binding.rv.setup {
            addType<SuperTableCaseListModel>(R.layout.item_home_case_list)
            addType<SuperTableDividerViewModel>(R.layout.item_super_table_divider)
            onBind {
                // ...
                val rvCase = findView<RecyclerView>(R.id.rv_super_table_case_list_item)
                rvCase.setOnTouchListener { view, motionEvent ->
                if (motionEvent.action == MotionEvent.ACTION_UP) {
                    toast("点击了")
                }
                false
            }
          }

        }
```

**Comment by XiaoRanLiu3119** [comment]
我也遇见此类型问题,感谢此issue和作者解答才解决,我子view是三方自定义的view,内部设置了clickble,学到了
