### ISSUE TITLE
如果GridLayoutManager 添加header   header 没办法全宽 

### ISSUE THREAD

**Issue by z876335662** [liangjingkanji/BRV#179]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
谷歌搜索: `GridLayoutManager SpanSizeLookup`
