### ISSUE TITLE
网格分割线有个bug

### ISSUE THREAD

**Issue by hegaojian** [liangjingkanji/BRV#18]
在网格列表中，使用网格分割线，均布间隔，但是在累加数据时会出现分割线间隔不一致的bug 如图：
![Screenshot_20210610_143042](https://user-images.githubusercontent.com/18655288/121475843-84156880-c9f8-11eb-8010-8a403810e4c7.jpg)

**Comment by hegaojian** [comment]
累加数据时代码：

```
rv.addModels(getData())
```

**Comment by liangjingkanji** [comment]
好的, 我看看问题

**Comment by hegaojian** [comment]
刚升级到最新版重试了一下，还是会出现错乱的问题
![QQ截图20210611181209](https://user-images.githubusercontent.com/18655288/121671013-a387c080-cae0-11eb-903d-697515e20883.png)

**Comment by liangjingkanji** [comment]
兄弟你这就让我很尴尬了.  我更新了上面的回答请使用`1.3.24`

**Comment by hegaojian** [comment]
666，完美修复bug，不尴尬，我更新了上面的回答  :smile::smile:
