### ISSUE TITLE
使用ViewBinding 出现view must have a tag，有遇到过么？

### ISSUE THREAD

**Issue by yzhg-ux** [liangjingkanji/BRV#181]
在使用的时候遇到view must have a tag

**Comment by liangjingkanji** [comment]
是否是在其中使用了Glide

**Comment by yzhg-ux** [comment]
> 没有使用Glide

**Comment by liangjingkanji** [comment]
我也无能为力，你谷歌搜索下吧，和Brv没什么关系，虽然我不使用ViewBinding不过应该和ViewBinding应该也没什么关系

**Comment by zpliang94** [comment]
请问你解决了吗

**Comment by liangjingkanji** [comment]
我估计是你ViewBinding绑定的布局被layout标签包裹了, 即你用ViewBinding去绑定DataBinding布局文件导致的问题
