### ISSUE TITLE
大佬，这个分组功能+header好像会导致展开后子列表插入的位置不对，偏移量和header的数量有关，是我用的有问题吗

### ISSUE THREAD

**Issue by pyj831** [liangjingkanji/BRV#182]
## 问题描述
如题
## 如何复现
建议步骤:
-  可以在Sample复现
- 给GroupGridFragment的列表加入一个header
- 
![企业微信截图_16530156395990](https://user-images.githubusercontent.com/19635211/169441965-986842a7-8dff-4b7a-a470-2bd806e04352.png)

**Comment by liangjingkanji** [comment]
你可以尝试使用ContactAdapter或者CoordinatorLayout来构建Header可以完全不干扰BindingAdapter的分组

关于具体此问题我排查下

**Comment by pyj831** [comment]
> 你可以尝试使用ContactAdapter或者CoordinatorLayout来构建Header可以完全不干扰BindingAdapter的分组
> 
> 关于具体此问题我排查下

好的，我试下ConcatAdapter，大佬居然对这个做了兼容的嘛，我以前用brvah的时候，带了header再用ConcatAdapter就会崩溃

**Comment by liangjingkanji** [comment]
brv使用的是很单纯的自定义adapter, 不存在不兼容问题

如果你不想缺省页覆盖rv请使用CoordinatorLayout实现header
如果只是不想干扰分组使用ContactAdapter

**Comment by liangjingkanji** [comment]
已修复问题, 同时更新文档: [头脚布局](https://liangjingkanji.github.io/BRV/header_footer/)

**Comment by liangjingkanji** [comment]
好兄弟你成功丧失一次pr机会

**Comment by pyj831** [comment]
> 好兄弟你成功丧失一次pr机会

东哥真快

**Comment by liangjingkanji** [comment]
有仇必报, 有bug必改, bug只需一东

其实很简单你自己看下也能很快改掉
