### ISSUE TITLE
分页加载问题

### ISSUE THREAD

**Issue by boboqun** [liangjingkanji/BRV#183]
## 问题描述

```kotlin
binding.page.onRefresh {
    scope {
        val data = Get<List<UserModel>>("list") {
            param("page", index)
        }.await()
        addData(data) {
            index < 100 // 最多加载100个
        }
    }
}.autoRefresh()
```

类似demo里这样请求，如果新返回的data是个空列表，那addData方法路会直接判定为isEmpty，自动展示成缺省的空页面了，

```kotlin
            if (isEmpty()) {
                showEmpty()
                return
            }
```
感觉不太对，上滑加载添加data时候应该先判断一下是不是已经有数据了，如果新请求的是空，可以认为是没有更多数据，后者抛出这个异常让程序员自己判断这种情况是异常还是只是没更多数据了

## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
你看清楚一点, 只有下拉刷新才会进入这个判断, 上拉加载并不会

```kotlin
if (isRefreshState) { // 是下拉刷新
    // ...
    if (isEmpty()) {
        showEmpty()
        return
    }
}
```

**Comment by boboqun** [comment]
嗯，是我自己的问题，原因是是我在自己定义的异常里自己调用了 ```binding.page.showContent()``` 导致刷新状态判断都成了刷新完成，最终导致了错误。

**Comment by liangjingkanji** [comment]
`PageRefreshLayout.scope`会自动在作用域完成后`showContent`

**Comment by liangjingkanji** [comment]
我现在将在`addData`方法中`index=startIndex`也判断为下拉刷新数据
