### ISSUE TITLE
菜鸟寻求帮助

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#187]
BVR 我已经使用上了，很强大。但因为自己菜，有个问题还请教一下大佬。

我需要增加一个头部布局。头部布局比较复杂，其中包含一个轮播图，一个横向的RV。请问这个如何优雅的处理呢。
请指点一二，万分感谢

**Comment by zkzk7749** [comment]
我是结合Net使用的

**Comment by liangjingkanji** [comment]
大概能猜到什么样的页面, 建议用CoordinatorLayout+RecyclerView配合使用, 只有横向rv和轮播图都在CoordinatorLayout的Header中

**Comment by zkzk7749** [comment]
万分感谢大佬，我试试去，弄出来给您汇报

**Comment by liangjingkanji** [comment]
demo中有CoordinatorLayout示例

**Comment by zkzk7749** [comment]
我是两个fragment 嵌套。  主Fragment中，根布局是，CoordinatorLayout，头部是AppBarLayout包裹toolbar,TabLayout.，下面是ViewPager2。toolbar有scroll|enterAlways。ViewPager2有app:layout_behavior="@string/appbar_scrolling_view_behavior"


在ViewPager2，中第一个Fragment,里边，一个主rv,需要加一个头部，头部是一个横向的rv,还有一个轮播图。现在这个rv,加了   app:layout_behavior="@string/appbar_scrolling_view_behavior"，滑动冲突了，我现在考虑解决这个问题。我基础太差了

**Comment by zkzk7749** [comment]
demo中有CoordinatorLayout示例
---------------------------
我看见了，我现在考虑一下两个app:layout_behavior="@string/appbar_scrolling_view_behavior"的问题

**Comment by liangjingkanji** [comment]
建议你问题描述更清晰一点

**Comment by zkzk7749** [comment]
再次感谢。主要是我太菜。这个问题的确和框架无关
