### ISSUE TITLE
可以实现抖音评论的效果吗

### ISSUE THREAD

**Issue by luhuanxml** [liangjingkanji/BRV#188]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
这和框架本身不矛盾吧

**Comment by liangjingkanji** [comment]
1. 嵌套rv (推荐)
2. 多类型

**Comment by zkzk7749** [comment]
这个问题具有代表性和挑战性，强烈建议东哥示范一个

**Comment by liangjingkanji** [comment]
> 这个问题具有代表性和挑战性，强烈建议东哥示范一个

我本意是希望你们来示范的, 如果我仅有的精力都用来写示例代码, 谁来写需求和修复bug
我要维护的不仅仅是这一个开源项目, 而且我的工作也是很繁忙的

**Comment by liangjingkanji** [comment]
新增抖音评论列表示例: [DouyinCommentFragment](https://github.com/liangjingkanji/BRV/blob/a3e73368ee41ae3cf129531a9a2944cb95c29422/sample/src/main/java/com/drake/brv/sample/ui/fragment/DouyinCommentFragment.kt#L27)
