### ISSUE TITLE
想請問BRV支援DifferCallback的單個Item中的部分刷新嗎

### ISSUE THREAD

**Issue by IamCheng5** [liangjingkanji/BRV#189]
## 问题描述
印象中在傳統的RecyclerView要做到item中的部分資料改變時只執行單個item的部分刷新可以利用getChangePayload回傳信息後在onBindViewHolder(RecyclerView.ViewHolder holder, int position, List<Object> payloads) 這個函數中做部分介面刷新，不知道是否支援此功能，謝謝您！

**Comment by liangjingkanji** [comment]
我建议你先看下文档或者demo再提问

1. 首先brv没有自定义rv, 完全支持任何rv的组件或功能
2. brv有简化`DifferCallback`的方法, 见文档[对比数据刷新](https://liangjingkanji.github.io/BRV/refresh-data/#_3)
3. demo中有`对比数据更新`示例
4. 另外如果你强调的是`局部刷新`我更推荐你使用databinding, 性能更优更简单
