### ISSUE TITLE
二级item展开问题

### ISSUE THREAD

**Issue by Bruce8hou** [liangjingkanji/BRV#190]
## 问题描述
在用setDifferModels更新数据时，把itemExpand设置为true 不能展开二级item，只能通过直接设置models来更新数据才会打开二级item。
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
`setDifferModels`目前不支持分组

**Comment by Bruce8hou** [comment]
用setDifferModels 更新数据的时候 可以避免闪烁。定量更新。如果直接通过设置models更新数据 一般都会闪烁。是不是还有其他更好的办法呢

**Comment by liangjingkanji** [comment]
通过models设置并不会闪烁吧, 我没有发生过闪烁

**Comment by liangjingkanji** [comment]
如果你发生闪烁请录屏给我看下

**Comment by Bruce8hou** [comment]
后台是有一个flow，通过网络数据 不定时刷新RV，在用models明显出现了闪烁 在用setDifferModels可以做到指定item上某个控件刷新。setDifferModels还是很有用的

**Comment by liangjingkanji** [comment]
1. 如果你可以fork仓库在sample中复现此问题我可以来研究下如何处理, 或者欢迎你pr修复此问题(问题大致是新的数据没有使用`flat`方法处理)
2. 关于你说的闪烁希望能录屏给我看下
