### ISSUE TITLE
东哥的库很好用，希望能精简一下上拉下拉这种

### ISSUE THREAD

**Issue by shenhuxi92** [liangjingkanji/BRV#191]
## 问题描述
库里面直接集成了SmartRefreshLayout库，但有时候项目中并不需要用到，希望东哥能把SmartRefreshLayout抽取出来，就像SmartRefreshLayout的样式库一样，需要的人可以自己引入相关功能

**Comment by liangjingkanji** [comment]
那你上拉加载方案选择是什么?

**Comment by liangjingkanji** [comment]
我也想过很多人可能使用官方的SwipeRefreshLayout, 然后上垃加载不使用动画

但是那样我需要为其实现缺省页功能

**Comment by shenhuxi92** [comment]
目前上拉加载方案是官方的SwipeRefreshLayout，下拉使用的是官方的Paging3。
如果是考虑到缺省页功能的话，能不能这样，缺省页是否可以抽离出来，以接口调用的形式进行控制，这样子的话，不管使用的是哪种上拉下拉方案，只要调用相关接口就行，虽然这样会导致需要手动控制缺省页

**Comment by liangjingkanji** [comment]
长时间没有回复该问题将会被关闭
