### ISSUE TITLE
选择模式方面的问题，小弟寻求帮助

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#194]
小弟寻求帮助。

选择模式，如何设置最大选择数的问题。
比如说，可选择条目有若干个，但只能选三条，多了不让选，如果强行选择的话，就取消已选择的第一条

**Comment by liangjingkanji** [comment]
1. 自己在选择事件回调中判断下已选数量
2. 判读超过最大选择数量自动为第一条置取消选择

> brv只提供选择监听事件`onChecked`, 选中索引通过`checkedPosition`集合可以获取

**Comment by zkzk7749** [comment]
真香！！！
感谢东哥

**Comment by liangjingkanji** [comment]
可以试试Net
