### ISSUE TITLE
东哥请教一个问题

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#196]
我的rv,里边有多个EditText， 我在提交前如何批量获取EditText的值，并且将值判断后，如果符合格式要求才提交呢

**Comment by liangjingkanji** [comment]
### 批量获取EditText值
将EditText的值映射到列表的model中的某个字段(`例如inputText`), 你遍历下集合数据即可获取到全部


```kotlin
val inputs:List<String> = models.map{ it.inputText }
```
### 判断格式要求
如果你使用的mvvm架构建议判断逻辑在界面对应的model中处理
```kotlin
fun checkSubmit():Boolean{
  val result:Boolean = models.all{ it.inputText >= "某个值" } // all即为要求`{}`全部返回true最终才会才返回null
  return result
}
```

**Comment by liangjingkanji** [comment]
不要总是有把业务/数据相关的问题套在视图控件上的想法

**Comment by zkzk7749** [comment]
东哥，我这个废柴求助。
我第一步不太会。没研究出来
----------------------------------------------------------------------------

批量获取EditText值
将EditText的值映射到列表的model中的某个字段(例如inputText), 你遍历下集合数据即可获取到全部

**Comment by liangjingkanji** [comment]
用databinding吗?

**Comment by liangjingkanji** [comment]
将EditText的内容赋值到Model的字段上都不会吗?

**Comment by liangjingkanji** [comment]
1. 使用dataBinding监听输入框变化并且自动赋值到某个字段: [ChatFragment](https://github.com/liangjingkanji/BRV/blob/a82ca250bfb90f154e796ec83bb9c232ee443ccf/sample/src/main/res/layout/fragment_chat.xml#L65)
2. 给EditText设置一个变化监听器, 自动复制给Model的字段

无关brv的问题尽量不要提, 建议你搜索问题或者加群去问

**Comment by zkzk7749** [comment]
感谢东哥
