### ISSUE TITLE
关于分组显示的bug

### ISSUE THREAD

**Issue by tanzhihao1qaz** [liangjingkanji/BRV#197]
也就是ItemExpand的使用，我先直接说一下遇到什么bug。
假如我有这么一个list：
```
val list = mutableList(A(),A(),A(),A())
class A : ItemExpand {
// 忽略A的成员变量
override var itemExpand: Boolean = true
override var itemGroupPosition: Int = 0
override var itemSublist: List<Int> = mutableList(1,2,3,4)
}
```
当我重复设置给rv，比如rv.models = list，效果则是list的size不变，但是每个itemSublist的长度都会翻倍，也就是第一次赋值，itemSublist是4，然后是8，然后是12，用过最近版本也是这样；
但如果我是这样赋值：rv.models = list.toList()，这样就反而没事

**Comment by liangjingkanji** [comment]
BRV不会改变`itemSublist`的内容, 只会读取里面的List作为子列表

你应该是自己为itemSublist写的逻辑导致重复添加了, 如果依旧无法排查出问题请fork仓库复现问题然后告诉我

**Comment by liangjingkanji** [comment]
长时间没有回复问题将关闭问题
