### ISSUE TITLE
请教东哥，分组的问题

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#198]
东哥你好，我的RV需要分组。

我的主item和子item，需要分别请求接口。

主item点击展开的时候，带着这个item的id来请求网络数据，等数据回来以后才展开，而且主tiem和子item对应的javabean是不同的。

我这个废柴不会了

**Comment by liangjingkanji** [comment]
点击主item触发请求, 请求成功将返回的List赋值给itemSublist, 然后将整个集合重新赋值给rv.models即可触发刷新

**Comment by zkzk7749** [comment]
搞出来了，数据添加以后，调用expandOrCollapse()，就展开了。
我这里只对当前主item进行了刷新。

  getModel<PartyDetailsModle.Data.Comment>().itemSublist =
                                childComment.data.list
                            notifyItemChanged(modelPosition)
