### ISSUE TITLE
关于网格布局请教

### ISSUE THREAD

**Issue by sdjwj1118** [liangjingkanji/BRV#199]
## 问题描述
请问网格布局rv.grid(2)能否通过参数或者api给每个item手动设置边距
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
这不是最基础的吗? 

你给数据模型设置个字段用于保存边距, 然后在onBind或者通过dataBinding配置边距即可

这个需求和根据数据字段显示或隐藏某个View没有任何区别
