### ISSUE TITLE
PageRefreshLayout有个bug

### ISSUE THREAD

**Issue by lacuz** [liangjingkanji/BRV#20]
PageRefreshLayout的showLoading函数中，stateLayout?.showLoading(tag, refresh)有误，应该是stateLayout?.showLoading(tag, refresh=refresh)

**Comment by liangjingkanji** [comment]
的确有错误
请查看 https://github.com/liangjingkanji/BRV/commit/3197b9b3ecdbb7c307366c62889aca3e54c1f7e6 的修复处理
