### ISSUE TITLE
拖动排序问题，点击拖动第一个item往下移动的时候，recyclerview会自己滑动到底部。

### ISSUE THREAD

**Issue by ALEXLEOHY** [liangjingkanji/BRV#200]
## 问题描述
拖动排序问题，点击拖动第一个item往下移动的时候，recyclerview会自己滑动到底部。
### 期望行为
是否可以一个一个慢慢移动
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 可以复现，将禁用拖拽的几个item移到最下方
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

Uploading 1654765906472885.mp4…

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by ALEXLEOHY** [comment]
![1654765906472885_](https://user-images.githubusercontent.com/23455100/172813820-7c72d7b3-cd41-4b74-959c-fbe27b8f1a6d.gif)

**Comment by RebornQ** [comment]
东哥可否 Reopen 一下这个 issue，目前我也遇到了，一模一样的问题，百分百复现，两台不同 Android 版本不同厂商的测试机都复现了，东哥无法复现不知道是否跟 Android 版本或者 RecyclerView 版本有问题，我可以补充一下问题说明：

### 问题描述

- 当 Item 数超出 RecycleView 可见区域时，第一个且仅第一个 item 拖动往下移会导致一次越过多个 Item 下移，而不是一个一个下移
- 当 Item 数没超出 RecycleView 可见区域或者第二个开始的 Item 拖动就没这个问题

### 如何复现

Sample 什么都不用改就可以复现这个问题

### 版本

- BRV: 1.3.90
- Gradle: 7.4
- Android Studio: 2022.1.1 Patch 2
- Android: Vivo Z5 OriginOS 1.0 Android 10 和 红米 Note 10 MIUI 14.0.5 Android 13

**Comment by liangjingkanji** [comment]
该问题已经在新版本中被修复

**Comment by RebornQ** [comment]
> 该问题已经在新版本中被修复

好耶！~
