### ISSUE TITLE
建议将使用文档的字体调大两号

### ISSUE THREAD

**Issue by lindroy** [liangjingkanji/BRV#201]
使用文档的字体太小了，看得眼睛有点累，可否调大两个字号呢？

**Comment by liangjingkanji** [comment]
软件设置界面可以调整字体大小, 具体看常见问题吧

**Comment by liangjingkanji** [comment]
回复太快串题了... 

你可以使用浏览器放大功能(并且只会针对文档), 
比如Chrome使用快捷键<kbd>CMD</kbd>+<kbd> + </kbd>(Mac), <kbd>Ctrl</kbd> + <kbd>+</kbd>(Windows)

**Comment by lindroy** [comment]
好家伙，这么快就回复了。我一开始也是缩放网页，但是这样整体放大后网页会左右滑动，感觉有点奇怪，如果能只把字号调大一点就没有这个问题。整体看起来也舒服一点。不过要是文档本身限制了无法设置，那就算了吧。

**Comment by liangjingkanji** [comment]
也没有限制, 我自己觉得看起来比较合适而已, 也许你可能是Windows

你可以截图给我看下效果吗

> 如果我有空以后文档会重构

**Comment by lindroy** [comment]
> 也没有限制, 我自己觉得看起来比较合适而已, 也许你可能是Windows
> 
> 你可以截图给我看下效果吗
> 
> > 如果我有空以后文档会重构

我用的Mac，字体倒是清晰，但就是觉得小了点，代码的字体还好，就是正文的字体，比代码块的字体还要小。要是再大一点会更好阅读。

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/22363769/172821270-64c0fdc7-78c6-4fa6-8953-06d6e8e65b42.png">

**Comment by liangjingkanji** [comment]
正文和代码字体大小是一致的, 可能视觉效果导致看起来小点吧

难道改成14px你觉得更合适吗

**Comment by lindroy** [comment]
一样的吗？可能是黑色背景显得文字大。现在的字体大小是多大呢？我用语雀时感觉15px和16px会好一点（语雀默认是15px）。

**Comment by liangjingkanji** [comment]
现在是12px

**Comment by lindroy** [comment]
12px确实有点小了，至少我自己感觉是这样，或者其他人看到这个issue的话也进来说说自己的感受。

**Comment by liangjingkanji** [comment]
你看下现在文档字体大小是否合适, 我调整成14px了, 说实话我觉得太大

**Comment by lindroy** [comment]
感觉确实大了一点，没之前那么容易累眼睛了。要是我的话，应该会 15px 往上，哈哈，不过你觉得太大的话 14px 就行了。

**Comment by liangjingkanji** [comment]
一个屏幕看的内容太少不利于阅读理解

**Comment by lindroy** [comment]
其实足够的，屏幕中间的正文面积跟一张A4纸差不多的，一页纸上的文字也不会很多，信息量太过密集的话反而会使眼睛和大脑都感到疲惫。

**Comment by liangjingkanji** [comment]
经过考量我决定使用JetBrainsMono官方推荐字号: 13

**Comment by lindroy** [comment]
> 经过考量我决定使用JetBrainsMono官方推荐字号: 13
> 
> 你觉得如何, 应该还是能接受的吧

嗯……可以吧，这东西众口难调的，要是看不清我再放大一下页面。谢谢了。

**Comment by liangjingkanji** [comment]
字体就像男女朋友吧, 看久了觉得不好看了都是毛病, 换一个看又会觉得不习惯太大了, 重新看回来又会觉得很好看了

**Comment by tanranran** [comment]
> 字体就像男女朋友吧, 看久了觉得不好看了都是毛病, 换一个看又会觉得不习惯太大了, 重新看回来又会觉得很好看了

😄
