### ISSUE TITLE
我在一个java kt混编的项目里 使用这个库 会报这个错 object not locked by thread before notify()  请问有人见过吗

### ISSUE THREAD

**Issue by anberwei** [liangjingkanji/BRV#202]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
没见过, 确定是这个库导致的吗?

**Comment by anberwei** [comment]
之前使用一直没问题 这次可能存在多个因素影响  我在一个旧的项目里使用的 这个项目中还有butterknife 我使用kapt编译后 跳转到使用这个库的列表页面 就会报这个错 稍后我会贴出错误 我也不清楚是什么原因 就冒昧的来问下

**Comment by liangjingkanji** [comment]
你可以尝试在旧项目中写个简单的列表页面来测试, 理论上这个错误不太可能和brv有关系

**Comment by anberwei** [comment]
![image](https://user-images.githubusercontent.com/32103566/172825893-2bb6f454-17f3-4f65-bbd8-eccbd2439062.png)
![image](https://user-images.githubusercontent.com/32103566/172826340-c64d38b1-6cc0-4a4a-bab4-d3f07629eb29.png)
没有头绪 乱问的 不好意思

**Comment by anberwei** [comment]
![image](https://user-images.githubusercontent.com/32103566/172826617-1c7c8628-10b2-42cf-97bc-121d59cee434.png)
![image](https://user-images.githubusercontent.com/32103566/172826732-589a28ee-6578-4208-96e2-65c4ac7f3475.png)
没有头绪 瞎问的 请大家帮助一下

**Comment by anberwei** [comment]
感谢 问题解决了
