### ISSUE TITLE
第一页加载项没有占满整个页面时，自动加载第二页

### ISSUE THREAD

**Issue by bobskycn** [liangjingkanji/BRV#206]
## 

## 版本
- BRV:1.3.77
- Android:
- Gradle: 
- Android Studio:

**Comment by bobskycn** [comment]
经过测试，发现BRV有这个功能。但是有个bug，就在viewpager中有多个fragment，每个fragment都使用BRV。第一个fragment不会触发自动加载第二页，其他的fragment却会触发自动加载。测试了很多次发现可能是因为PageRefreshLayout在加载完第一页后RefreshState没有变成RefreshState.NONE造成的。希望能修复这个bug

**Comment by liangjingkanji** [comment]
你们接口配置一页数据竟然这么少, 本身这就是非常不合理的, 我建议你直接去让接口改下每页数量

**Comment by liangjingkanji** [comment]
> 经过测试，发现BRV有这个功能。但是有个bug，就在viewpager中有多个fragment，每个fragment都使用BRV。第一个fragment不会触发自动加载第二页，其他的fragment却会触发自动加载。测试了很多次发现可能是因为PageRefreshLayout在加载完第一页后RefreshState没有变成RefreshState.NONE造成的。希望能修复这个bug

这个`if`是为了避免在刷新过程中去触发加载下一页的请求, 避免并发执行请求列表数据, 我不认为这属于bug, 我认为这属于不支持该功能

**Comment by liangjingkanji** [comment]
自动在第一页预加载会导致视图显示异常(一页数据会分成两次显示出来), 我不赞同此做法, 我上面已经提供了解决方案, 而且是我认为最合适的解决方案, 就是手动加载两次请求组装成一个更长的单页数据
