### ISSUE TITLE
快速滑动会多加载一页

### ISSUE THREAD

**Issue by zengss** [liangjingkanji/BRV#207]
## 问题描述
测试总共43条数据，每页加载10条数据，正常滑动为5页，快速拖动会产生第6页数据；测试为本地数据库查询没有延
<img width="443" alt="微信截图_20220615120219" src="https://user-images.githubusercontent.com/31001263/173734307-bd83656c-c601-4df9-8f58-d2af3881cae5.png">
迟
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:最新
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
能否fork仓库复现问题

**Comment by liangjingkanji** [comment]
使用数据库复现问题可能比较难, 但是实际上数据库和网络请求没有区别

我认为你可能是没有判断是否存在更多页, 导致触发了加载下一页
