### ISSUE TITLE
上次提的ItemExpand问题找到了

### ISSUE THREAD

**Issue by tanzhihao1qaz** [liangjingkanji/BRV#208]
## 问题描述
当使用分组ItemExpand，重复给rv赋同样的list时，就会出现出现itemSub数量增加的bug，原因是大佬你把传进来list的值给替换了，核心代码在BindingAdapter的这个方法里：
```
private fun flat(list: MutableList<Any?>,expand: Boolean? = null,@IntRange(from = -1) depth: Int = 0,): MutableList<Any?> {
// 中间逻辑省略
}
```
我传的list只有一个对象，一下是我对象的结构：
```
class TestInfo : ItemExpand {
    private val TAG = "TestInfo"
    var name = "1"

    override var itemExpand: Boolean = true
    override var itemGroupPosition: Int = 0
    override var itemSublist: List<Any?>? = mutableListOf(1, 2)
}
```
我看了flat方法的逻辑，我第一次传的list size = 1，只有一个TestInfo，那么flat方法会先把list清空，然后返回一个长度为3的list，第一次是没错的，但这样就改变了我原来的list的size了，我第二次传list进来的时候因为不知道size已经变成3了（由原本的里面只有一个TestInfo，变成里面有一个TestInfo和两个Int），再走flat就变成list size = 5了，我建议还是不要修改开发者传进来的list的数据体，一下是我断点时的截图：

<img width="888" alt="image" src="https://user-images.githubusercontent.com/28348014/173983048-b5b0116b-a1b3-42e0-b594-031af4893e83.png">

<img width="451" alt="image" src="https://user-images.githubusercontent.com/28348014/173983070-99b75c94-473f-46d3-a0b1-fea064713692.png">

<img width="544" alt="image" src="https://user-images.githubusercontent.com/28348014/173983087-04407c87-02f4-4447-8e08-c1abad44b22d.png">

**Comment by tanzhihao1qaz** [comment]
或者使用文档里特别说明一下这个问题，需要使用者toList()一下生成一个新对象赋值

**Comment by liangjingkanji** [comment]
List是不可变集合, 不修改怎么改变数据集合? 你如果不想改变你可以传入`MutableList`

**Comment by tanzhihao1qaz** [comment]
我传的是mutableList，flat方法把我传进来的mutableList数据清空重新赋值了

**Comment by liangjingkanji** [comment]
> 我传的是mutableList，flat方法把我传进来的mutableList数据清空重新赋值了

对的, 这是为了保持rv内部和外部共用一个List对象

**Comment by liangjingkanji** [comment]
因为数据和视图本身就不是耦合, 我修改数据然后触发视图更新这是rv很正常的操作

**Comment by tanzhihao1qaz** [comment]
> 

主要是不知道内部会修改我原本list的数据，也不知道会改成咋样，不知情的情况下变了总觉得觉得不太友好。那没事啦谢谢

**Comment by liangjingkanji** [comment]
可以完善方法注释

**Comment by liangjingkanji** [comment]
注释已更新, 没问题你就关闭此问题吧
