### ISSUE TITLE
大佬！想請問下Databinding是否有支援多個variable的方法呢？

### ISSUE THREAD

**Issue by IamCheng5** [liangjingkanji/BRV#209]
## 问题描述
您好，想請問下databinding的參數只允許有一個嗎？
假設想引入兩個model我目前的方式是把兩個mode包成一個model指定進去，想知道有無支援同時使用兩個以上variable的方法呢，謝謝大佬！
![image](https://user-images.githubusercontent.com/29422378/173998646-011db282-2bca-466c-ae65-392ab501a059.png)

**Comment by liangjingkanji** [comment]
支持两个有什么实际作用? 我建议你不要做无关的事, 也不要随意命名
但是支持单例, 你可以为每个BindingAdapter单独配置

**Comment by liangjingkanji** [comment]
你遍历数据集合, 通过时间条件判断, 在消息中间插入`消息类型item`, 最好赋值给`models`即可
