### ISSUE TITLE
感谢东哥！！！

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#210]
东哥啊，小弟感激涕零，您终于出了仿抖音评论了！！！！
太感谢了，我卡在这里卡的都快便秘了

**Comment by zkzk7749** [comment]
大佬我看了下demo， 仿抖音和分组，您用的是多类型的思路。 评论列表用的是嵌套思路。

我菜鸟，前几天用的是嵌套模式，展开和折叠的效果不是很好，晚上我按照新的方式试一试

**Comment by liangjingkanji** [comment]
抖音评论列表的子评论可能长达上千条所以使用多类型item实现避免滑动卡顿

**Comment by liangjingkanji** [comment]
具体实现细节欢迎你补充

**Comment by zkzk7749** [comment]
请教大佬，点击子评论的时候，如何获取它父评论的位置呢

**Comment by zkzk7749** [comment]
我现在需要追加子评论，但是追加后提示类型错误，原来 子评论的位置，和主评论的位置是不一样的，所以请教一下大佬，点击子评论的时候，如何获取它父评论的位置

**Comment by zkzk7749** [comment]
好的，这个复杂列表真的是一环套一环，稍有不注意就出问题

**Comment by zkzk7749** [comment]
我发现demo 有个问题。
比如第三条主评论，显示只有1条子评论，但点击展开的时候，怎么展开了多条数据

**Comment by zkzk7749** [comment]
展开状态下，增加了子评论的数据，如何刷新列表啊

**Comment by liangjingkanji** [comment]
阅读demo

**Comment by liangjingkanji** [comment]
> 我发现demo 有个问题。 比如第三条主评论，显示只有1条子评论，但点击展开的时候，怎么展开了多条数据

因为是模拟数据每次都返回固定数量
