### ISSUE TITLE
能否添加个底部自动加载更多 不用包裹SmartRefreshLayout实现

### ISSUE THREAD

**Issue by z876335662** [liangjingkanji/BRV#213]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
可以, 你自己判断下添加个就行了

**Comment by liangjingkanji** [comment]
如果要求brv包含这个逻辑, 这个我认为没有必要这么设计

**Comment by liangjingkanji** [comment]
PageRefreshLayout提供预加载/预拉取/分页/下拉/上拉/缺省页各种加载相关, 不仅仅是加载footer

如果有更好的实现方式欢迎pr
