### ISSUE TITLE
文档国际化问题

### ISSUE THREAD

**Issue by boboqun** [liangjingkanji/BRV#214]
大佬我想帮你翻译英文文档。请问我该如何组织目录结构。
您用的这个文档框架是什么？有没有个国际化的小 demo 或者其他注意事项？
第一次想做这个事，还请大佬指教。

**Comment by boboqun** [comment]
踩坑记录
brew 安装 mkdocs 仿佛有问题，官方推荐使用 pip 安装。

本仓库内的 material 主题需要先安装一下 不然无法编译成功
```pip install mkdocs-material```

**Comment by liangjingkanji** [comment]
直接安装`mkdocs-material`会自动安装`mkdocs`
```kotlin
python3 -m pip install mkdocs-material
```

**Comment by boboqun** [comment]
我翻译好了一个文档，想要给你看看的话 应该怎么操作？我看创建 PR 的话 只能往mater合并，感觉不太对。

**Comment by liangjingkanji** [comment]
`site`目录不需要提交, 你把`docs`里面的`.md`文件翻译一遍提交上来, 然后我拉取你的仓库帮你pr

生成的英文文档会在你的仓库下生成`Pages`地址, 就和BRV官方仓库地址一样

比如你的是`https://boboqun.github.io/BRV/`

**Comment by boboqun** [comment]
https://github.com/boboqun/BRV/blob/pages-en/docs/index.md
这是我最近翻译的，大佬你看一眼。觉得还可以接受的话，我就继续翻译。

**Comment by liangjingkanji** [comment]
很不错

**Comment by liangjingkanji** [comment]
希望你可以让更多国外开发者来贡献高质量代码

**Comment by shenbengit** [comment]
> `site`目录不需要提交, 你把`docs`里面的`.md`文件翻译一遍提交上来, 然后我拉取你的仓库帮你pr
> 
> 生成的英文文档会在你的仓库下生成`Pages`地址, 就和BRV官方仓库地址一样
> 
> 比如你的是`https://boboqun.github.io/BRV/`

大佬，我这边使用chatgpt 做了英文文档，https://shenbengit.github.io/BRV/，仓库：https://github.com/shenbengit/BRV/tree/pages-en，是我提pr，还是你自己拉呢。

**Comment by liangjingkanji** [comment]
@shenbengit 
好的多谢贡献，等我检查下翻译内容

**Comment by shenbengit** [comment]
> > > `site`目录不需要提交, 你把`docs`里面的`.md`文件翻译一遍提交上来, 然后我拉取你的仓库帮你pr
> > > 生成的英文文档会在你的仓库下生成`Pages`地址, 就和BRV官方仓库地址一样
> > > 比如你的是`https://boboqun.github.io/BRV/`
> > 
> > 
> > 大佬，我这边使用chatgpt 做了[英文文档](https://shenbengit.github.io/BRV/)，[仓库地址](https://github.com/shenbengit/BRV/tree/pages-en)，是我提pr，还是你自己拉呢。
> 
> 可以将README也翻译一遍吗? 我会在本仓库直接指向你仓库的Pages页面, 所以不需要Pr

看下[README.md](https://github.com/shenbengit/BRV/blob/pages-en/README.md)，有啥需要调整的再修改。

**Comment by liangjingkanji** [comment]
@shenbengit  非常谢谢你贡献的英文文档, 你让这个项目寿命更加长久

为了遵守你的劳动贡献成功建议你[发起pr](https://liangjingkanji.github.io/document/)

1. 将你翻译的README.md重命名为`README_EN.md`移动到本仓库根目录(因为README更新可能比较频繁方便后续维护)


2. 添加以下代码到本仓库`README.md`最上面
```markdown
<p >
    <a href="http://liangjingkanji.github.io/BRV/">中文</a>
    | <a href="https://github.com/liangjingkanji/BRV/blob/master/README_EN.md">English</a>
</p>
```

**Comment by shenbengit** [comment]
> @shenbengit 非常谢谢你贡献的英文文档, 你让这个项目寿命更加长久
> 
> 为了遵守你的劳动贡献成果建议你[发起pr](https://liangjingkanji.github.io/document/)
> 
> 1. 将你翻译的README.md重命名为`README_EN.md`移动到本仓库根目录(因为README更新可能比较频繁方便后续维护)
> 2. 添加以下代码到本仓库`README.md`最上面
> 
> ```gfm
> <p >
>     <a href="http://liangjingkanji.github.io/BRV/">中文</a>
>     | <a href="https://github.com/liangjingkanji/BRV/blob/master/README_EN.md">English</a>
> </p>
> ```

https://github.com/liangjingkanji/BRV/pull/366  提了。
