### ISSUE TITLE
多布局下，不同的layout中相同id控件的点击事件问题

### ISSUE THREAD

**Issue by HeJingWei** [liangjingkanji/BRV#215]
## 问题描述
我添加了2个多布局layout，分别是item_simple和item_simple_2
2个layout中都include了一个共同的layout，其中有一个id为tv_simple的TextView控件
在2个布局中，tv_simple的点击事件是触发不同的业务，因为库里的扩展方法只有id的点击事件，所以我只能如下写：
<img width="465" alt="image" src="https://user-images.githubusercontent.com/16362351/175226868-0d7c6587-25c8-4876-9da9-f6798599629c.png">

但是这种有一个问题就是，我会写2个when的语句来分别处理数据显示和点击事件：
<img width="687" alt="image" src="https://user-images.githubusercontent.com/16362351/175226285-81d1a9d5-8b4f-4f87-af70-fd8961380160.png">

其实我更期望，能在一个case里，就把该类型的UI显示和点击事件都处理了，更好的封装不同type的代码，比如：

<img width="529" alt="image" src="https://user-images.githubusercontent.com/16362351/175226489-c8a8446c-84ae-42a1-ada6-0b315e948f50.png">

对此请问作者你是如何考虑的呢？我想的是给view提供点击事件就能方便解决，希望得到你的建议

**Comment by liangjingkanji** [comment]
既然id相同你在`onClick`里面判断`itemViewType`不就行了

**Comment by liangjingkanji** [comment]
原来你是想在一个case里面同时处理点击和数据绑定? 

你可能不太熟悉rv, 数据绑定会在每次item滑动时候都会执行, 所以你会反复设置点击事件监听, 这本身就是不推荐的

但是并没有禁止你在onBind里面找到View来设置点击事件, 你不用onClick即可

如果你以前使用的BRVAH而不想使用MVVM架构你可以实现ItemBind接口和BRVAH一样在数据模型中处理View(请仔细阅读文档)

**Comment by HeJingWei** [comment]
多谢回复,我目前项目使用的是BRVAH+MVVM架构，但是没有使用databinding（因为部分业务需求，需要多种判断才渲染到控件上去，本身也不熟练databinding，所以没有使用）
是我没有考虑到反复设置点击事件监听这个原因，只考虑了相同业务的代码放在一起

**Comment by liangjingkanji** [comment]
我认为点击事件属于View, 你不要和业务掺杂比较好, 因为追踪代码执行的时候会快速定位View然后查找点击事件, 点击事件应当尽可能清晰简练

业务逻辑你尽可能放到Model中, 业务和视图避免耦合是常识, 也是方便你版本迭代

**Comment by liangjingkanji** [comment]
本框架其实致力于View和Model的分离的无Adapter模式, 所以并不是很推荐BRVAH的MVC模式: 视图和业务全部集中在他的`Data`里面

当然如果你想保持以前的BRVAH写法可以通过实现`ItemBind`接口来做

我还是比较推荐DataBinding的使用的, 相信你也看到sample无论什么业务都非常简单

**Comment by HeJingWei** [comment]
多谢回复， 还有一个疑问点，你说的BRVAH的MVC模式: 视图和业务全部集中在他的Data里面，这个data是指adapter的实体类吗？
我目前的习惯写法是，列表数据由后端返回一个data列表，这个data也用于adapter，然后在onbindholder中进行逻辑判断和视图显示
你说的View和Model的分离，我的理解是，model实现ItemBind接口，在onbind中进行逻辑判断，data添加一个showName的字段，用于视图显示，我有一个疑问是，如果UI显示的数据过多，data中就会加很多字段。请教这种情况如何考虑呢
<img width="842" alt="image" src="https://user-images.githubusercontent.com/16362351/175251229-ee2fa348-cc47-404c-bb86-e33088fbc0fc.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/16362351/175251249-e313e317-463d-4f8b-a6d1-5fa9a7e6bf9e.png">

**Comment by HeJingWei** [comment]
name是服务端返回的字段，我需要进行一系列判断，然后赋值给一个showName用于textView显示

如果说服务端返回的字段有5个，类似的写法我就会在data中又添加5个字段，感觉会不便于代码阅读和维护

**Comment by liangjingkanji** [comment]
你可能理解错误了, Model就是数据类, 在正式项目中他的数据一般是直接解析json生成的, 不是你一个一个字段传入的(当然也可以传入)

**Comment by HeJingWei** [comment]
了解了。谢谢
