### ISSUE TITLE
setDifferModels 对比数据刷新  存在位置跳来跳去的问题

### ISSUE THREAD

**Issue by finddreams** [liangjingkanji/BRV#216]
## 问题描述
setDifferModels 对比刷新存在 位置跳动的问题，在列表顶部的时候，调用setDifferModels  刷新发现位置跳到了中间，在底部调用setDifferModels 也会存在离开底部的情况；
### 期望行为
希望在顶部刷新数据，一直在顶部，底部也是如此。
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.3.77
- Android:11
- Gradle: 
- Android Studio:

**Comment by finddreams** [comment]
你的sample.apk 也是这个效果，在列表顶部的时候，点随机排列，数据发生变化，位置却不在第一个了，跑到其他位置去了，需要手动滑动第一个。

**Comment by liangjingkanji** [comment]
那就更不好修复此问题, 这个应该是和他的动画先后执行顺序有关

**Comment by finddreams** [comment]
使用DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(new DiffCallBack(mDatas, newDatas), true);
diffResult.dispatchUpdatesTo(mAdapter);

**Comment by liangjingkanji** [comment]
你试下`setDifferModels(getRandomData(), false)`, 就不会存在你说的问题了. 建议你发生问题可以点开方法看下尝试自我修复

**Comment by liangjingkanji** [comment]
> 使用DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(new DiffCallBack(mDatas, newDatas), true); diffResult.dispatchUpdatesTo(mAdapter); 这种方式就不会

我也是受到你的提醒想到`setDifferModels`还有默认参数

**Comment by finddreams** [comment]
setDifferModels(getRandomData(), false) 试了 依然存在 问题

**Comment by liangjingkanji** [comment]
但是我在demo测试不存在问题了

**Comment by liangjingkanji** [comment]
的确设置false只能保证位于第一条的时候不会变化, 但是滑动到中间还是会变化

**Comment by liangjingkanji** [comment]
这个问题属于官方问题, 建议自己记录位置然后跳转

**Comment by liangjingkanji** [comment]
我认为完全要求位置不变化应该直接使用`notifyDataChanged`而不是`setDeifferModels`
