### ISSUE TITLE
分组列表类型转换出错

### ISSUE THREAD

**Issue by cjcj125125** [liangjingkanji/BRV#221]
## 自定义数据类型赋值给二级列表，如下示例：
 (item.itemSublist as ArrayList).add(SecondItem("文本信息"))

SecondItem 类为自定义数据解析类，并且已经实现：ItemExpand, ItemHover, ItemPosition

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
![QQ截图20220628115120](https://user-images.githubusercontent.com/20206579/176088181-376a75ad-8397-4d25-9d91-6ba9f63927ee.png)
![QQ截图20220628115024](https://user-images.githubusercontent.com/20206579/176088216-af829fa6-fc69-4ae6-a34d-bb3cd09a3e84.png)
![QQ截图20220628113805](https://user-images.githubusercontent.com/20206579/176088215-7a3e9b92-7d1c-470a-95f6-7b904b135a63.png)

您好，都是按照文档shi'xian'de实现的，请教一下，这里的数据类型转换是在哪里出错的？
 

## 版本
- BRV: 1.3.79
- Android: 7.0.1
- Gradle:  6.5
- Android Studio: 2021.2.1 patch 1

**Comment by liangjingkanji** [comment]
我没看到你的`itemSubList`怎么实现的

**Comment by liangjingkanji** [comment]
未及时回复问题将被关闭

**Comment by zilong-zZ** [comment]
我也遇到了,分组列表展开的时候会把itemSubList的数据加到父列表数据中,再获取list的数据就存在多类型.导致类型转换错误

**Comment by liangjingkanji** [comment]
> 我也遇到了,分组列表展开的时候会把itemSubList的数据加到父列表数据中,再获取list的数据就存在多类型.导致类型转换错误

list是什么? 
我觉得这属于语言基础的类型转换问题, 不是框架抛出来的错误
建议fork仓库复现问题否则只能自己检查错误

**Comment by zilong-zZ** [comment]
![image](https://user-images.githubusercontent.com/10513068/177147499-c0d53a48-1084-4d3a-8df1-9e817eb32a61.png)
跟分组展开的实现方式有关,list是adapter.models

**Comment by liangjingkanji** [comment]
> ![image](https://user-images.githubusercontent.com/10513068/177147499-c0d53a48-1084-4d3a-8df1-9e817eb32a61.png) 跟分组展开的实现方式有关,list是adapter.models

这是预期行为, 分组本身就是使用多类型Item实现, 在需要判断类型的地方得自己处理好类型问题(和多类型一致)
