### ISSUE TITLE
我发现了你demo里面的一个小bug

### ISSUE THREAD

**Issue by Dboy233** [liangjingkanji/BRV#222]
在你demo里发现一个小bug。
分组3展开，把分组2拖拽到分组3下方。然后关闭分组3.分组2就消失了、

https://user-images.githubusercontent.com/37604230/176105063-1d2b73e6-5532-4038-ab79-e2bd48ffff96.mp4

**Comment by liangjingkanji** [comment]
的确存在该问题, 并且目前没有跨组拖拽示例, 你要是最近在用就pr修复下吧
