### ISSUE TITLE
三级分组列表singleExpandMode失效

### ISSUE THREAD

**Issue by cjcj125125** [liangjingkanji/BRV#224]
## 1. 多级列表
      2. 设置其中一个分组itemExpand=true 且singleExpandMode=true
      3. 点击其他分组后上一个默认打开的分组未折叠

**Comment by liangjingkanji** [comment]
本项目遵守社区开源准则, 能否fork仓库复现问题或者发起pr修复, 敬请体谅

**Comment by cjcj125125** [comment]
在demo中已复现，复现更改代码如下图所示：
![微信截图_20220701152219](https://user-images.githubusercontent.com/20206579/176845290-28706ed2-cb16-4f38-8abb-1a9415ccbe0c.png)
![微信截图_20220701152252](https://user-images.githubusercontent.com/20206579/176845301-62a09ef4-5188-427f-b8f5-52373c5a4c68.png)
