### ISSUE TITLE
使用成本看起来有点高 使用方式整体通用dataBinding吗

### ISSUE THREAD

**Issue by Danniel-yan** [liangjingkanji/BRV#228]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
仅有三行代码，方法全有注释，文档细无巨细，我只能做到如此，有更好的方案或者框架欢迎pr

文档有提到三种数据绑定方式，databinding只是其中一种

**Comment by Danniel-yan** [comment]
网格吸顶条目 宽度benign全屏设置而且会遮挡底部gridview的布局 请问怎么修复 谢谢

**Comment by liangjingkanji** [comment]
demo中有网格悬停示例, 不清楚你说的什么问题
和框架无关的问题建议上网搜索, 我维护项目时间比较紧张, gridView和本框架无关

**Comment by Danniel-yan** [comment]
> 这是RecyclerView的基础知识, 请自行搜索: `GridLayoutManager.SpanSizeLookup`使用

感谢大神指点 已处理好

**Comment by liangjingkanji** [comment]
处理好就行
