### ISSUE TITLE
东哥，小弟有问题求助一下

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#230]
我一个fragment 中有两个RadioButton. 两个rv.

点击左边的，显示左边的rv（右边的rv默认隐藏），点击右边的显示右边的rv,左边的隐藏。亲测可以用。
但是加了com.drake.brv.PageRefreshLayout以后，左边的正常，右边的一直在转圈不显示。如果这时候点击左边的RadioButton，就退了。
报这个错
E/AndroidRuntime: FATAL EXCEPTION: main
,PID: 5502
    android.util.NoSuchPropertyException: please add item model type : addType<com.zhongnanwenlv.zhongnanshan.model.ZhongNanVideoList$Data$ZhongNanVideo>(R.layout.item)

**Comment by zkzk7749** [comment]
这是布局文件
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white_b"
    android:orientation="vertical">

    <RadioGroup
        android:id="@+id/mRadioGroup"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_29"
        android:layout_marginLeft="@dimen/dp_16"
        android:layout_marginTop="@dimen/dp_16"
        android:layout_marginRight="@dimen/dp_16"
        android:orientation="horizontal">


        <RadioButton
            android:id="@+id/mRadioButton_0"
            android:layout_width="@dimen/dp_0"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="@drawable/selector_fextagmodel1"
            android:button="@null"
            android:checked="true"
            android:gravity="center"
            android:text="@string/photo" />

        <RadioButton
            android:id="@+id/mRadioButton_1"
            android:layout_width="@dimen/dp_0"
            android:layout_height="match_parent"
            android:layout_marginLeft="@dimen/dp_16"
            android:layout_weight="1"
            android:background="@drawable/selector_fextagmodel1"
            android:button="@null"
            android:gravity="center"
            android:text="@string/video" />


    </RadioGroup>


    <com.drake.brv.PageRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/page"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="@dimen/dp_16"
        app:stateEnabled="true">


        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/mRecyclerViewPhoto"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />


    </com.drake.brv.PageRefreshLayout>


    <com.drake.brv.PageRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/page_video"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="@dimen/dp_16"
        android:visibility="gone"
        app:stateEnabled="true">


        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/mRecyclerViewVideo"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />


    </com.drake.brv.PageRefreshLayout>

   


</LinearLayout>

**Comment by liangjingkanji** [comment]
> 我一个fragment 中有两个RadioButton. 两个rv.
> 
> 点击左边的，显示左边的rv（右边的rv默认隐藏），点击右边的显示右边的rv,左边的隐藏。亲测可以用。 但是加了com.drake.brv.PageRefreshLayout以后，左边的正常，右边的一直在转圈不显示。如果这时候点击左边的RadioButton，就退了。 报这个错 E/AndroidRuntime: FATAL EXCEPTION: main ,PID: 5502 android.util.NoSuchPropertyException: please add item model type : addType<com.zhongnanwenlv.zhongnanshan.model.ZhongNanVideoList$Data$ZhongNanVideo>(R.layout.item)

你的错误已经提示了, 没有调用`addType`添加正确的类型, 导致无法匹配models里面的元素

**Comment by zkzk7749** [comment]
感谢东哥。 我犯了一个低级错误。目前处理好了
