### ISSUE TITLE
瀑布流分割线

### ISSUE THREAD

**Issue by zjie1595** [liangjingkanji/BRV#231]
## 问题描述
瀑布流分割线设置间距会把视图给裁剪掉，虽然文档里提到了只支持GridLayoutManager，但我想这里应该不对吧。

## 如何复现

> fork仓库并复现
问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
<img width="895" alt="image" src="https://user-images.githubusercontent.com/66541098/179469868-15919ae5-4e1a-4cde-84c9-2eb0dfcb551e.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/66541098/179469924-d5791539-6f6b-4780-b247-80264bdca68a.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/66541098/179470094-efb46854-5439-4167-b872-4df6ed13cf47.png">

异常堆栈信息

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
文档有提到只支持`GridLayoutManager`? 官方LayoutManager应当都支持的吧

**Comment by zjie1595** [comment]
> 文档有提到只支持`GridLayoutManager`? 官方LayoutManager应当都支持的吧

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/66541098/179474588-9dcf1e53-4156-4536-9ceb-fe6b4cafea80.png">
是这个文档

**Comment by zjie1595** [comment]
> 说的是支持不是`只支持`, 而且下一章就是`瀑布流分割线文档`

好吧，是我理解错了
