### ISSUE TITLE
问题求助

### ISSUE THREAD

**Issue by zjie1595** [liangjingkanji/BRV#232]
## 问题描述
想问下东哥，BindingAdapter怎么清空数据？我这里是搜索页，如果下拉的话传itemCount作为offset是可以的，但是执行搜索的话这里的offset应该是0，就是这里应该怎么写才对呢？放在onRefresh里写应该不对

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/66541098/179643413-21feea7f-7b02-4d01-b45f-71aef5e92b3d.png">

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by zjie1595** [comment]
应该直接setModels吧？撤回这个白痴问题..

**Comment by zjie1595** [comment]
> 是的
> 
> 1. `bindingAdapter.models = null`
> 2. 不知道你说的`offset`是什么, 尽量不要问我业务问题, 因为我也不清楚

offset是分页时候的数据偏移量

**Comment by liangjingkanji** [comment]
一般情况这个由后端计算偏移量(这是针对数据库的), 客户端一般传page(页面索引)和size(页面数量)即可
