### ISSUE TITLE
请教 XML 中出现的 imgCircle holder 怎么来的？

### ISSUE THREAD

**Issue by cipchk** [liangjingkanji/BRV#233]
## 问题描述

我尝试编译得到的是：

```xml
Cannot find a setter for <android.widget.ImageView holder> that accepts parameter type 'android.graphics.drawable.Drawable'
```

**Comment by liangjingkanji** [comment]
点击可以跳转到源码, 这是DataBinding自定义属性实现的, 实现代码在[Engine](https://github.com/liangjingkanji/Engine/blob/HEAD/engine/src/main/java/com/drake/engine/databinding/DataBindingComponent.kt#L5)框架中
