### ISSUE TITLE
在不同类型分组的item中点击子item的时候如何获取父级item数据？

### ISSUE THREAD

**Issue by cjcj125125** [liangjingkanji/BRV#235]

**Comment by liangjingkanji** [comment]
在文档[分组](https://liangjingkanji.github.io/BRV/group/)中最后两行有提到

**Comment by cjcj125125** [comment]
好的，感谢强哥

**Comment by liangjingkanji** [comment]
注意`findParentViewHolder`可能会返回null, 所以最好用findParentPosition, 然后根据返回索引去models里面查询

**Comment by liangjingkanji** [comment]
不用vx, 有和框架无关的问题你可以加群问

**Comment by cjcj125125** [comment]
好的，感谢

**Comment by cjcj125125** [comment]
你好强哥，点击非当前打开的item，如何使当前已经打开的全部折叠？目前只折叠了打开的二级item，没有折叠一级item，试了很多方法都不行，麻烦指点，感谢
