### ISSUE TITLE
singleExpandMode 只允许一个分组展开，不能折叠一级item

### ISSUE THREAD

**Issue by cjcj125125** [liangjingkanji/BRV#236]

**Comment by liangjingkanji** [comment]
目前只是记录了上一个被折叠position, 然后在展开当前item的时候折叠上一个, 所以singleExpandMode不支持嵌套的

由于BRV如果想折叠同级别的其他item需要记录depth(这会导致递归性能差), 所以请自己记录位置然后自己收缩(collapse)

**Comment by liangjingkanji** [comment]
如果有更好的实现方式欢迎Pr

**Comment by cjcj125125** [comment]
我尝试了记录当前点击的一级item，然后再点击其他的item时候将上一次记录的item的itemExpand改为false并刷新item，但是发现并没有效果，请教哪里的问题？

**Comment by liangjingkanji** [comment]
不太清楚，估计是刷新item无效，item要折叠不是刷新，你可以去阅读下源码或者搜下rv实现

**Comment by cjcj125125** [comment]
折叠不就是把itemExpand改为false吗？是我考虑的太简单了么
