### ISSUE TITLE
请教关于如何拦截item的长按事件

### ISSUE THREAD

**Issue by ALEXLEOHY** [liangjingkanji/BRV#237]
### 期望行为

######请教一下如何拦截item的长按事件，已经指定控件拖拽，但是同时存在item的长按拖拽事件，想把item的长按事件拦截掉，或者是动态开启和关闭拖拽功能

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
自定义ItemTouchHelper或者拦截View的长按事件

**Comment by liangjingkanji** [comment]
如果不需要长按拖拽, 你直接交互数据不就好了, 为什么要配置拖拽手势

**Comment by ALEXLEOHY** [comment]
感谢指点，已解决问题，大佬太牛了！！！
