### ISSUE TITLE
文档----选中模式---示例代码小瑕疵

### ISSUE THREAD

**Issue by ALuoBo** [liangjingkanji/BRV#238]
## 问题描述
无脑复制代码，导致无效果，需要花费一点点时间去凑凑代码
### 期望行为
1.文档更完善 ，在` setChecked(xxx)` 前加一行注释：这里修改处理是否选中
2.说明databinding 模式下，需要将model 的 checked 关联到 XML
## 截图
![image](https://user-images.githubusercontent.com/45779049/182507713-d5fe64c3-82c9-432b-8a38-a1e6e5d18cdb.png)

**Comment by liangjingkanji** [comment]
如果你有空也许你可以点击右上角编辑文档然后发起pr, 本项目欢迎任何人随时修改文档

**Comment by liangjingkanji** [comment]
你的pr经过代码审查有瑕疵请及时修改下

**Comment by ALuoBo** [comment]
> 你的pr经过代码审查有瑕疵请及时修改下

东哥，是两个commit 需要 合成一个么？ 我没给开源项目提过PR，所以不太明白🤣

**Comment by liangjingkanji** [comment]
1. 的确需要合成一个(强推你的分支就行不需要重新创建新的pr)
2. 我有给你代码标记有歧义地方, 你打开pr就可以看到

学会使用`git pr`代码审查很重要
