### ISSUE TITLE
希望增加onTouch事件

### ISSUE THREAD

**Issue by Keryyyy** [liangjingkanji/BRV#241]
现在item只有onClick事件，希望增加onTouch事件封装

**Comment by liangjingkanji** [comment]
自己获取View对象去设置`onTouch`, 不可能为所有事件都封装一次, 这会增加框架学习成本

**Comment by Keryyyy** [comment]
> 自己获取View对象去设置`onTouch`, 不可能为所有事件都封装一次, 这会增加框架学习成本

在onBind里面获取？

**Comment by liangjingkanji** [comment]
1. 是的
2. 看文档, 有三种方式获取
