### ISSUE TITLE
kotlin-android-extensions导致StateLayout:showStatus空指针

### ISSUE THREAD

**Issue by the6nnoo** [liangjingkanji/BRV#242]
## 问题描述
1.view的引用使用的是kotlin-android-extensions
2.在showLoading的过程中对Content view进行的操作而出现的空指针
3.在StateLayout.kt的312行对之前的缺省页进行删除了

### 期望行为
ContentView是不是不应该称为缺省页，当然在Loading过程中对view进行操作逻辑上是不对的。
但是保不齐一些逻辑需要这么搞。

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
<img width="999" alt="image" src="https://user-images.githubusercontent.com/13672968/183046454-1580dbea-b6cb-444c-bca2-adf51dbd86b3.png">

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.3.79
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
1. 没看到空指针异常
2. content也属于缺省页的一种状态, 也需要被stateChangeHander处理, 例如很多动画同样需要对内容页生效

**Comment by liangjingkanji** [comment]
StateChangeHander是我对于缺省页自由扩展的一种接口设计, 保证自由度

**Comment by the6nnoo** [comment]
如图
<img width="847" alt="image" src="https://user-images.githubusercontent.com/13672968/183056295-ea0bcc6e-835d-4dec-aedc-45a0c419167c.png">
<img width="624" alt="image" src="https://user-images.githubusercontent.com/13672968/183056501-fa6a99b7-bcd9-4153-b6fe-56bcc0350b37.png">

这是个非常简单的demo，prl.showContent()如果在第二个的位置 每次tv的值都会被回置到2022

**Comment by liangjingkanji** [comment]
难道存在多个contentView? 你这个问题我没遇到过不排除和你的`kotlin-android-extensions`有关

**Comment by the6nnoo** [comment]
确实，改成findViewById没有这个问题

**Comment by liangjingkanji** [comment]
1. 是否考虑将默认的StateChangedHandler改为Visibility而非RemoveView来解决此问题
2. 或者不再考虑`kotlin-android-extensions`, 毕竟这是废弃框架

**Comment by the6nnoo** [comment]
可以，用viewbinding来代替了

**Comment by liangjingkanji** [comment]
更推荐databinding

**Comment by the6nnoo** [comment]
有时候，页面简单，与数据交互的地方不多 不需要databinding。毕竟会让xml变得更臃肿

**Comment by liangjingkanji** [comment]
本身就包含ViewBinding功能, 即使页面简单你也可以在Activity像ViewBinding一样使用, 而且我的基类自动继承其`ViewDataBinding`字段无需构建对象
