### ISSUE TITLE
东哥请教一个问题。使用下拉刷新上拉加载后，如何刷新局部数据呢？

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#243]
东哥请教一个问题。使用下拉刷新上拉加载后，如何有效刷新局部数据呢？

比如有一个评论列表。是分页加载的，如果有人点赞，红心变红，计数器加1，反之红心取消变色，计数器减一

**Comment by liangjingkanji** [comment]
[更新数据](https://liangjingkanji.github.io/BRV/refresh-data/)

**Comment by zkzk7749** [comment]
哈哈哈，东哥秒回复啊。 我还没问完呢。
使用这种模式，<com.drake.brv.PageRefreshLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:id="@+id/page"
    app:stateEnabled="true"
    android:layout_height="match_parent"
    tools:context="com.drake.brv.sample.fragment.RefreshFragment">

<androidx.recyclerview.widget.RecyclerView
    android:id="@+id/rv"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

</com.drake.brv.PageRefreshLayout>


rv的原始数据源应该怎么保存，因为原有的集合会变

**Comment by liangjingkanji** [comment]
如果是分组的确会导致原始集合变更, 自己复制一份集合对象就行了, 以后不要问这么简单的问题

**Comment by zkzk7749** [comment]
实在不好意思啊，小弟基础太差，影响大佬了。
比如在这个代码中，如何自己复制一份集合对象。

pageLayout.onRefresh {
    scope {
        val data = Get<String>("/path").await()
        addData(data.list){
            // 该回调函数参数返回一个布尔类型用于判断是否存在下一页, 决定上拉加载是否关闭
            adapter.itemCount < data.count // 这里是判断是否由更多页, 具体逻辑根据接口定义
        }
    }
}.autoRefresh()

**Comment by gangoogle** [comment]
> 实在不好意思啊，小弟基础太差，影响大佬了。 比如在这个代码中，如何自己复制一份集合对象。
> 
> pageLayout.onRefresh { scope { val data = Get("/path").await() addData(data.list){ // 该回调函数参数返回一个布尔类型用于判断是否存在下一页, 决定上拉加载是否关闭 adapter.itemCount < data.count // 这里是判断是否由更多页, 具体逻辑根据接口定义 } } }.autoRefresh()
val oldSize =  adapter.model.size()
adapter.model.addAll(data.list)  adapter.notifyItemChange(oldSize,adapter.model.size())

**Comment by liangjingkanji** [comment]
> 实在不好意思啊，小弟基础太差，影响大佬了。 比如在这个代码中，如何自己复制一份集合对象。
> 
> ```kotlin
> pageLayout.onRefresh {
>     scope {
>         val data = Get<String>("/path").await()
>         addData(data.list){
>             // 该回调函数参数返回一个布尔类型用于判断是否存在下一页, 决定上拉加载是否关闭
>             adapter.itemCount < data.count // 这里是判断是否由更多页, 具体逻辑根据接口定义
>         }
>     }
> }.autoRefresh()
> ```

你这个Get每次都是返回的新对象, 不需要复制集合对象
