### ISSUE TITLE
东哥请教下问题哈，比如在这个代码中，如何自己复制一份集合对象。

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#244]
实在不好意思啊，小弟基础太差，影响大佬了。
比如在这个代码中，如何自己复制一份集合对象。

pageLayout.onRefresh {
scope {
val data = Get("/path").await()
addData(data.list){

adapter.itemCount < data.count 
}
}
}.autoRefresh()

**Comment by liangjingkanji** [comment]
搜索 "kotlin 复制集合"

**Comment by zkzk7749** [comment]
addData(data.list){
adapter.itemCount < data.count
}

我在句话后面复制了集合，好了。
另外一个，文档中， 更新数据->添加数据->示例代码的代码示范的有问题，这个是绑定数据的

**Comment by liangjingkanji** [comment]
没太理解你什么意思, 我平时工作比较忙而且维护的开源项目有点多见谅

**Comment by zkzk7749** [comment]
东哥太客气了。是我提问的问题太低级，提问的问题太低级就算了，还没描述清楚

**Comment by liangjingkanji** [comment]
文档更新了
