### ISSUE TITLE
点击事件能否再优雅点一呢？

### ISSUE THREAD

**Issue by GuangNian10000** [liangjingkanji/BRV#245]
当前点击事件写法是onClick(R.id.xxx)，或  R.id.tv_simple.onClick
这样写会出现问题：R.id.xxx是全局作用域的，如果当前 addType<>(R.layout.xx)布局中没有对于id是会闪退或出错的，有时候确实会码错，比如item中有tvState ，另外一个是tvStates在act.xml中，这时候在setup里甚至任何位置R.id.tvStates编译器都不会报错，只有运行到那一行时会闪退。所以能否考虑到作用域的问题

我提议要么不使用R.id方式获取控件，改用对应xml的databing对象获取控件或者把点击事件的关系写到xml里

![image](https://user-images.githubusercontent.com/44353535/183296310-75d32e9b-fdd6-48fd-a1c0-1903605ec05a.png)

谢谢

**Comment by liangjingkanji** [comment]
1. 即使为Item不存在的ID配置点击事件也不会导致崩溃
2. 你说的DataBinding方式配置点击事件目前就支持, 只不过我并不是很推荐, 因为规范的写法便于开发者查找和理解

**Comment by liangjingkanji** [comment]
最开始设计是

```kotlin
onClick(R.id.tv, R.id.tv2){
	when(it) {
		R.id.tv -> {}
		R.id.tv2 -> {}
	}
}
```
我认为这样判断两次太多此一举然后才新增以下方法
```kotlin
R.id.tv.onClick {
	
}

R.id.tv2.onClick {
	
}
```

关于你说的DSL作用域问题, 是想限制onClick只能在setup但是不能在onBind中使用吧, onBind每次滚动都会调用所以本身就不推荐配置点击事件

**Comment by GuangNian10000** [comment]
> 1. 即使为Item不存在的ID配置点击事件也不会导致崩溃
> 2. 你说的DataBinding方式配置点击事件目前就支持, 只不过我并不是很推荐, 因为规范的写法便于开发者查找和理解, 而且BRV没有强制要求使用DataBinding

感谢回复
