### ISSUE TITLE
是否考虑支持Tv端~

### ISSUE THREAD

**Issue by xie123** [liangjingkanji/BRV#246]
如题~

**Comment by liangjingkanji** [comment]
1. TV支持RecyclerView
2. 支持RecyclerView就支持BRV

**Comment by xie123** [comment]
我会这么提问肯定RecyclerView在tv上某些场景是胜任不了。比如焦点快滑后丢失等。应该说tv上要求的RecyclerView，是被扩展后的。

**Comment by liangjingkanji** [comment]
我对TV端适配开发不够了解, 不太清楚你说的是什么RecyclerView, 你的意思是leanback库内的某个列表控件?

**Comment by liangjingkanji** [comment]
如果你的意思是让我去解决TV设备的RecyclerView相关焦点问题, 我的技术能力不够, 而且我都没有相关设备

不过欢迎你进行补充PR, 本框架宗旨是开源互助

**Comment by xie123** [comment]
哈哈哈，一些在tv上的特性拉。其实leanback库里的VerticalGridView 不也是基于RecyclerView的二次开发么。只不过VerticalGridView 不在适合触摸环境下使用。

**Comment by xie123** [comment]
没事没事，就是聊聊

**Comment by liangjingkanji** [comment]
不过我还是欢迎你共享你的解决方案
