### ISSUE TITLE
东哥 有个小问题 想问下

### ISSUE THREAD

**Issue by NeVaDaAAA** [liangjingkanji/BRV#247]
## 问题描述
执行refreshLayout的showLoading方法 数据回来后展示content页面 没有加载更多的foot效果了 不知道是不是我的写法不太对 东哥轻喷
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
![image](https://user-images.githubusercontent.com/20659340/183791355-e5c3f375-83f2-4ee6-a39a-dfd12a322ead.png)
![image](https://user-images.githubusercontent.com/20659340/183791450-c03f567f-305b-47ba-9e79-4a5140bb53a8.png)
加showLoading的录屏：

https://user-images.githubusercontent.com/20659340/183791611-842db5ad-25a5-4be8-a48e-b25fb0462f60.mp4

不加加showLoading的录屏：

https://user-images.githubusercontent.com/20659340/183791858-82d2711d-6bde-49d4-8ae2-c505bdac8bf9.mp4

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.3.79
- Android: 12
- Gradle: 7.2.1
- Android Studio: Android Studio Chipmunk | 2021.2.1 Patch 2

**Comment by liangjingkanji** [comment]
使用`liveData`来加载网络请求出现的问题, 我无法预期, 请不要使用`addData`自己去判断状态和赋值数据吧

**Comment by NeVaDaAAA** [comment]
好的 感谢东哥 我再看下

**Comment by NeVaDaAAA** [comment]
问题排查到了 和LiveData没有关系 我stateLayout的布局里面没有加NestedScrollView 包裹导致的 感谢东哥 BRV是真的好用

**Comment by liangjingkanji** [comment]
但是Content内容视图不是rv列表? 你用的`StateLayout`来问为什么不能滚动? 

以后我只接受fork仓库复现问题的提问了
