### ISSUE TITLE
思路求解

### ISSUE THREAD

**Issue by CosmicRayLucky** [liangjingkanji/BRV#248]
## 问题描述

老哥，视频中这种头像显示效果有什么思路，用哪种方式实现比较好？

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
https://user-images.githubusercontent.com/20819344/184058215-4a3a0e44-db50-45f3-a6e3-7e4af647ee14.mp4

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
这个实现起来比较复杂, BRV内部有个`HoverLinearLayoutManager`实现类似的顶部悬停效果, 你可以借鉴参考下思路
