### ISSUE TITLE
refresh()的错误使用可能导致的crash

### ISSUE THREAD

**Issue by the6nnoo** [liangjingkanji/BRV#249]
这是demo代码
<img width="908" alt="image" src="https://user-images.githubusercontent.com/13672968/184064690-ab1e054d-3827-4f1e-9810-79d51ba46af4.png">
这是logcat日志
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/13672968/184064711-6b4f46f1-8f7c-4e6d-8eb7-e3d176f53788.png">
这是firebase提供的日志
<img width="999" alt="image" src="https://user-images.githubusercontent.com/13672968/184064810-8b736702-c82d-41e1-a13e-edb4f95272c5.png">

以上是我简化的bug demo。
为了偷懒，我在onCreate的里面调用了refresh()代替了initData。
结果在线上有部分bug崩溃回应。
经过测试,如果delay的时间设置的越短，这里crash的概率会越高。
原因是smartRefresh的关闭动画会走到死循环而导致的栈溢出。
不知道brv这里能做点什么阻止这个发生，虽然我可以用autoRefresh()代替。

**Comment by liangjingkanji** [comment]
这是在Fragment还是Activity, 我推测可能是View未创建

有问题我建议你fork仓库复现崩溃, 而不是让我猜测, 你甚至都没贴崩溃异常信息. 我很不喜欢这样浪费时间

**Comment by the6nnoo** [comment]
重新编辑了issues.
BRV的版本是1.3.79

**Comment by liangjingkanji** [comment]
能否fork仓库复现下问题

**Comment by xihan123** [comment]
我复现了这个问题。很显然，是因为没有正确初始化刷新控件以及BRV导致的,要在应用启动时初始化，而不是在Activity或者Fragment初始化。还有就是你的使用方法可能错了，item布局你转为databing 的layout布局了吗
这是和你Activity一样代码的Demo，运行和刷新没有问题，你自己看看吧
![XG%06XO1}0LI{1489HO(PDA](https://user-images.githubusercontent.com/44894509/185333081-68761a3a-2811-4cd2-979a-d527f8ddfb01.png)
![%1VP(_%`GN AIFW8OF77 %R](https://user-images.githubusercontent.com/44894509/185333124-27a37e00-09f8-473d-bc76-1e86ab2d9be1.png)

[MyApplication.zip](https://github.com/liangjingkanji/BRV/files/9368440/MyApplication.zip)

**Comment by the6nnoo** [comment]
demo 只是我在做最简化的操作。
我的初始化操作也是在application上面。
即便是我delay到1毫秒，这个栈溢出的bug也不是百分百出现，只是出现的概率较高。
如果我第一次进来 没有使用prl.onrefresh() 而是prl.autoRefresh()。是不会出现问题的。

**Comment by xihan123** [comment]
要不你先下载我那个Demo试试会不会？我这测试了几十次没有一次崩溃，只有在刷新控件未初始化时调用，才触发了你上面的那个日志内容的错误

**Comment by xihan123** [comment]
> 我不在协程，而只是直接处理问题让协程感觉不 崩溃。 <img alt="图片" width="716" src="https://user-images.githubusercontent.com/13672968/185343472-d3f10079-abf4-4a24-84b2-711b5459bc63.png">

其实你这种写法本身就有点奇怪?要不你看下作者的示例怎么安全的实现结束刷新以及设置没有更多数据?我自己项目也有再用BRV,从来没碰到过你这问题,大概率是写法有问题呗

**Comment by the6nnoo** [comment]
> 其实你这种写法本身就有点奇怪?要不你看下作者的示例怎么安全的实现结束刷新以及设置没有更多数据?我自己项目也有再用BRV,从来没碰到过你这问题,大概率是写法有问题呗

现在我全局替换了refresh(),用了autoRefresh()

**Comment by liangjingkanji** [comment]
也许可以试试直接执行`binding.refresh.finish(hasMore=false)`

由于你迟迟无法fork仓库复现问题, 本问题即将关闭, 猜测只会浪费时间
