### ISSUE TITLE
底部滑入动画没有效果

### ISSUE THREAD

**Issue by wYulin** [liangjingkanji/BRV#251]
## 问题描述
.setAnimation(AnimationType.SLIDE_BOTTOM)不执行
### 期望行为
顺利执行动画
## 如何复现
使用CoordinatorLayout，
  <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rvFiles"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:最新版
- Android:12
- Gradle: 7.2.2
- Android Studio:4.1

**Comment by liangjingkanji** [comment]
我无法复现问题

请提供视频以及fork仓库复现代码
