### ISSUE TITLE
请教一下大神 GridLayoutManager添加footerView的时候 footerview显示了一半没有显示全，有没有遇到类似的问题呢？谢谢了。

### ISSUE THREAD

**Issue by Danniel-yan** [liangjingkanji/BRV#252]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by Danniel-yan** [comment]
目前看下来GridView的高度没有被计算在内 要特殊处理一下吗？

**Comment by liangjingkanji** [comment]
我猜不到, 如果你能fork仓库给我看下我可能能看出问题所在

**Comment by mcxinyu** [comment]
下边没了，还是右边没了
