### ISSUE TITLE
分组模式中可以指定一部分item不在任何组内吗？并按顺序展示。

### ISSUE THREAD

**Issue by GuangNian10000** [liangjingkanji/BRV#253]
例如：
组一 （展开）
item
item
item
不是任何组的item
不是任何组的item
不是任何组的item
组二（展开）
item
item
item
-------------------------------------------------------
组一 （收起）
不是任何组的item
不是任何组的item
不是任何组的item
组二（展开）
item
item
item

**Comment by liangjingkanji** [comment]
当然可以, 分组只是一个特殊类型而已, 只是折叠/展开状态会自动删除/新增某些item
