### ISSUE TITLE
brv  中使用viewbinding  

### ISSUE THREAD

**Issue by yexseven** [liangjingkanji/BRV#254]
## 问题描述
在使用 brv  用 viewbinding  方式 找不到 view 的id
用为我的项目用的是  `androidx.databinding:viewbinding:7.2.0@aar`
一下代码
中的     `val binding = ItemSimpleBinding.bind(itemView) // 使用ViewBinding` 直接崩溃
异常 `java.lang.NullPointerException: Missing required view with ID: xx`
```kotlin
binding.rv.linear().setup {
    addType<SimpleModel>(R.layout.item_simple)   
    onBind {
        val binding = ItemSimpleBinding.bind(itemView) // 使用ViewBinding
        binding.tvSimple.text = layoutPosition.toString()
        Log.e("onBind","${layoutPosition.toString()}")
    }
    R.id.tv_simple.onClick {
        toast("点击文本")
        Log.e("onClick","${layoutPosition.toString()}")
    }
    Log.e("onViewCreated","setup")
}.models = getData()
```

## 版本
- BRV: 1.3.79
- Android: 12
- Gradle: 7.2.0
- Android Studio: chipmunk | 2021.2.1

**Comment by liangjingkanji** [comment]
我无法复现你的问题，请你fork仓库并复现问题

**Comment by liangjingkanji** [comment]
ViewBinding不属于本项目的库, 另外最新AndroidStudio开启的`ViewBinding`版本仅为`4.2.2`

demo的ViewBinding启用代码
```kotlin
viewBinding {
    enabled = true
}
```
请你fork仓库复现问题
