### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by FrankLove** [liangjingkanji/BRV#256]
## 问题描述
simpleFragment demo滑动到顶部或者底部在测试机上出现到顶部(底部)一条横线不停的闪烁几秒后消失
### 期望行为
不应该出现
## 如何复现
滑动复现
> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

https://user-images.githubusercontent.com/8580868/186628849-e9e28f69-26bf-46ba-a3a3-a4dec9306dad.mp4

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.3.80
- Android:9.0
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
不好意思我无法复现此问题, 另外BRV仅仅是自定义Adapter, 依旧是`RecyclerView`

或许你自己写个原生的RV列表试下是否会出现此问题

**Comment by FrankLove** [comment]
原生的没有这个问题，试了3台设备唯独在一个手机上会这样，纳闷了

**Comment by liangjingkanji** [comment]
可是BRV就是原生RecyclerView, 仅仅是自定义了Adapter, 你可以尝试下载demo删减代码看能否排查原因, 我这边无法复现问题靠你了

**Comment by liangjingkanji** [comment]
你原生RecylerView是在demo中使用的吗? 不排除是rv版本问题
