### ISSUE TITLE
onBind {}中获取控件会空指针

### ISSUE THREAD

**Issue by huangShan-gitHub** [liangjingkanji/BRV#257]

**Comment by liangjingkanji** [comment]
有问题建议fork仓库复现问题, 否则只能瞎猜

1. 所有Item类型都经过`onBind`回调, 你可能没有判断类型导致在当前类型中查询其他类型的视图

**Comment by huangShan-gitHub** [comment]
是错了，需要用findView 获取id

**Comment by liangjingkanji** [comment]
那你调用的是Activity的`findViewById`吧

**Comment by huangShan-gitHub** [comment]
嗯，是的，眼瞎。大佬回复的速度可真迅速哇~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月31日(星期三) 下午2:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liangjingkanji/BRV] onBind {}中获取控件会空指针 (Issue #257)





 
那你调用的是Activity的findViewById吧

**Comment by liangjingkanji** [comment]
早期可能是为了不和Activity的`findViewById`冲突才命名`findView`
