### ISSUE TITLE
博主你好，用你这个库和net这个库很久，现在有一个项目公司强制用java开发，我可以在Java中用你这两个库吗

### ISSUE THREAD

**Issue by zs18340282344** [liangjingkanji/BRV#259]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
完全不允许出现kt代码的话就不建议使用了, 如果能使用kt桥接下还是使用没问题的

**Comment by liangjingkanji** [comment]
只是一些内联方法要求转为非内联方法(桥接)来给java使用, 因为java不支持kt的内联`inline`方法
