### ISSUE TITLE
使用网格布局+悬停，网格布局中使用divider, 显示有问题。

### ISSUE THREAD

**Issue by amosxb** [liangjingkanji/BRV#26]
同上
![Screenshot_20210727-152800_SmartLedPro](https://user-images.githubusercontent.com/19277279/127115264-5c296fbe-f86d-4996-844d-96fd7d898f58.jpg)

**Comment by liangjingkanji** [comment]
请提供你的分割线设置代码以及item大概xml描述

**Comment by amosxb** [comment]
private fun changeGridLayout() {
        val manager = HoverGridLayoutManager(this, 2)
        manager.spanSizeLookup = object : GridLayoutManager.SpanSizeLookup() {
            override fun getSpanSize(position: Int): Int {
                return if (mSubBinding.rvHome.bindingAdapter.isHover(position)) 2 else 1
            }
        }

        mSubBinding.rvHome.layoutManager = manager

        mSubBinding.rvHome
            .divider {
                endVisible = true
                orientation = DividerOrientation.GRID

                setDivider(8, true)
                addType(R.layout.item_common_grid_group)
                setColor(Color.TRANSPARENT)
            }
            .setup {
                addType<CommonHeadModel>(R.layout.item_common_write_head)
                addType<CommonItemModel>(R.layout.item_common_grid_group)
                models = data()

                onClick(R.id.item) {
                    when (itemViewType) {
                        R.layout.item_common_write_head -> toast("悬停条目")
                        else -> toast("普通条目")
                    }
                }

                // 可选项, 粘性监听器
                onHoverAttachListener = object : OnHoverAttachListener {
                    override fun attachHover(v: View) {
                        ViewCompat.setElevation(v, 10F) // 悬停时显示阴影
                    }

                    override fun detachHover(v: View) {
                        ViewCompat.setElevation(v, 0F) // 非悬停时隐藏阴影
                    }
                }
            }
    }

**Comment by amosxb** [comment]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">

    <RelativeLayout
        android:id="@+id/item"
        style="@style/MatchWrap"
        android:background="@drawable/sp_common_grid_group_corner_bg"
        android:padding="15dp">

        <ImageView
            android:id="@+id/iv_lamp_type"
            android:layout_width="80dp"
            android:layout_height="80dp"
            android:scaleType="fitCenter"
            android:src="@drawable/ic_single_color" />

        <ImageView
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:layout_below="@id/iv_lamp_type"
            android:layout_marginStart="25dp"
            android:layout_marginTop="15dp"
            android:scaleType="fitCenter"
            android:src="@drawable/ic_switch" />

        <ImageView
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:layout_below="@id/iv_lamp_type"
            android:layout_alignParentEnd="true"
            android:layout_marginTop="15dp"
            android:layout_marginEnd="25dp"
            android:scaleType="fitCenter"
            android:src="@drawable/ic_edit" />

        <ImageView
            android:layout_width="20dp"
            android:layout_height="20dp"
            android:layout_alignParentEnd="true"
            android:scaleType="fitCenter"
            android:src="@drawable/ic_small_edit" />

        <TextView
            style="@style/CommonTv14"
            android:layout_marginTop="30dp"
            android:layout_toEndOf="@id/iv_lamp_type"
            android:ellipsize="end"
            android:lines="1"
            android:text="灯带群组" />
    </RelativeLayout>
</layout>

**Comment by liangjingkanji** [comment]
你使用divider的`addType`函数导致只有group才会有分割线.
并且我建议你这种分隔间距可以直接给item的xml中添加`margin_bottom="8dp"`就可以了, 不需要使用divider函数

**Comment by amosxb** [comment]
那左边的边距不好控制，上下、右边是可以了。

**Comment by liangjingkanji** [comment]
你这种直接给网格类型的item设置一个`layout_margin="8dp"`即可

**Comment by liangjingkanji** [comment]
你这种属于网格布局, 应当
```
startVisible = true
endVisible = true
```

参考: https://liangjingkanji.github.io/BRV/divider-grid/#3

**Comment by amosxb** [comment]
![Screenshot_20210728-111519_SmartLedPro](https://user-images.githubusercontent.com/19277279/127258097-73fa5ba2-0030-4fc5-a352-cef12324c244.jpg)
这是不加divider,只设置margin的情况

**Comment by amosxb** [comment]
大佬。你有QQ群麽，这样讲有点麻烦。

**Comment by liangjingkanji** [comment]
README就有, 点击图标就可以加入

**Comment by liangjingkanji** [comment]
解决了吗

**Comment by amosxb** [comment]
大佬，问了你群里的人，好像没人能解决这个，现在是用margin弄的，但是左边的边距不知道怎么设置。

**Comment by liangjingkanji** [comment]
你告诉群里的人: "你们都是废物吗? 都不会?"

**Comment by liangjingkanji** [comment]
你使用网格分割线(不使用startVisible/endVisible)
<img src="https://i.imgur.com/udblR3G.png" width="30%"/>

然后给rv设置一个`padding="8dp"`

**Comment by amosxb** [comment]
rv 设置padding 会影响悬停布局的。    如果不设置divider，设置marginEnd,marginBottom的话，显示就是这个样子。
![Screenshot_20210728-165219_SmartLedPro](https://user-images.githubusercontent.com/19277279/127294228-ac05ce42-aa20-455c-810e-f3f5b2eaeaa5.jpg)

**Comment by liangjingkanji** [comment]
我给你实现个Demo解决下, 忘记这不是嵌套rv了抱歉

**Comment by amosxb** [comment]
谢了，大佬

**Comment by liangjingkanji** [comment]
建议使用嵌套列表保证间距问题
1. [代码实现](https://github.com/liangjingkanji/BRV/blob/65b6db8d1c3612fda0f2e2c39cfa330c0ec6c3ac/sample/src/main/java/com/drake/brv/sample/ui/fragment/hover/HoverGridDividerFragment.kt#L45)
2. [文档说明](https://liangjingkanji.github.io/BRV/divider-grid/#_5)

**Comment by amosxb** [comment]
谢大佬
