### ISSUE TITLE
动态添加数据导致数组越界

### ISSUE THREAD

**Issue by cjcj125125** [liangjingkanji/BRV#262]
您好，在使用分组功能时候，因为数据量比较大，一二级数据是第一个接口请求获得，点击二级菜单中的iten后，根据id请求三级数据，我添加好数据后，再次展开或折叠会出现数组越界问题，请问有没有好的处理方法？

**Comment by liangjingkanji** [comment]
demo里面有个仿抖音评论列表的示例就是通过请求接口获取子评论, 你可以参考下
