### ISSUE TITLE
自定义侧滑移动的视图`android:tag="swipe"`复用问题

### ISSUE THREAD

**Issue by dogscar** [liangjingkanji/BRV#263]
## 问题描述
自定义侧滑移动的视图android:tag="swipe"后，当侧滑删除目标view后，滚动列表，复用的那一个item会直接显示背景项，滑动一下又能恢复。
代码是在官方的示例基础上修改的。
 @liangjingkanji
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
![2](https://user-images.githubusercontent.com/33310862/190302683-5b5a0c05-3e81-4007-ac99-f15dfa8d0e73.gif)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.3.81
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
为什么不fork仓库复现问题, 这样问题解决速度很慢

**Comment by liangjingkanji** [comment]
Swipe视图的`transitionX`没有恢复导致

**Comment by dogscar** [comment]
暂时在onBind里把swipeView.x = 0f

**Comment by liangjingkanji** [comment]
已修复应该知道吧?
