### ISSUE TITLE
三级分组，删除子item问题

### ISSUE THREAD

**Issue by cjcj125125** [liangjingkanji/BRV#264]
## 东哥你好，非常感谢用了你的BRV节省了大量写adapter的时间，但是再三级分组item中也遇到了一些问题，删除子item的时候使用你demo中的方法：
1. 删除子item多次后顺序错乱
 mutable.removeAt(position)
 notifyItemRemoved(position)
删除再折叠打开后，再次删除会导致item删除错乱问题；
2. 删除一级(最顶级item) 后再次打开其他item会出现item越界问题导致崩溃，麻烦东哥指点，非常感谢

**Comment by liangjingkanji** [comment]
删除子列表item同时请删除对应的`itemSublist`

**Comment by cjcj125125** [comment]
mutable.removeAt(position) 不就是删除对应的itemSublist 么？

**Comment by cjcj125125** [comment]
另外就是我删除之后直接在查询接口，然后调用 mBinding.recyclerView.bindingAdapter.models = list(接口返回)
设置数据后再点击item，直接就崩溃了(数组越界)  太奇怪了

**Comment by liangjingkanji** [comment]
> mutable.removeAt(position) 不就是删除对应的itemSublist 么？

为什么你觉得会自动删除itemSublist, mutable只是一个集合而已, 所谓的分组就是自动为models添加子列表(itemSublist), 分组就是一个多类型Item列表而已

具体你看源码吧, 你观察下models变化就知道了, 索引越界肯定是你将models里面的子列表删除了, 这个时候折叠会再次去删除itemSublist数量的item但是早就被你删除了所以就会越界

**Comment by cjcj125125** [comment]
我看一下源码，mutable不就是adapter的数据源吗？另外在demo和文档中我也看到了相关的说明，删除前需要先折叠子item，还望 强哥明示，这问题把我折腾疯了
![微信截图_20220920163924](https://user-images.githubusercontent.com/20206579/191211256-cbc25f17-e93a-41d7-a70e-c0a2f7051e68.png)

**Comment by cjcj125125** [comment]
上图修正一下，我用的是remove不是removeAt

**Comment by liangjingkanji** [comment]
我看不出问题所在

另外请按照模板提示提问, 不要删除
