### ISSUE TITLE
开启多选模式下，若更新 RV 数据让 items 变为了 0 ，那么关闭多选 toggle(false) 功能失效

### ISSUE THREAD

**Issue by Moriafly** [liangjingkanji/BRV#265]
## 问题描述

开启多选模式下，若更新 RV 数据让 items 变为了 0 ，那么关闭多选 toggle(false) 功能失效，且此情况下再调用 getCheckedModels 会下标越界

### 期望行为

希望此情况下依旧可以退出多选模式

业务逻辑：涉及多选删除，先退出多选模式再更新 RV 可以避免此问题，但是有时候可能会疏忽，如果方便修复的话

## 版本
- BRV: 1.3.80

（这个库太好用了，强东哥🌹）

**Comment by liangjingkanji** [comment]
`toggleMode`在itemCount为0的时候依然可以被改变, 

你说的"退出多选模式"我猜测是你在`onToggle`里面进行判断的, 考虑到itemCount可能为0你应该在调用`toggle()`方法的地方就去退出/进入多选模式

**Comment by liangjingkanji** [comment]
好用可以推荐下, 方便更多人使用和维护

**Comment by Moriafly** [comment]
非常谢谢！！
