### ISSUE TITLE
菜鸟需求东哥帮助~~

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#266]
东哥你好啊，菜鸟寻求帮助。

我在研究抖音评论的实现方式，我现在遇见两处困难，请东哥指点一二啊，小弟不胜感激。

第一个问题是，主评论展开后，如果还有数据，那么肯定会再次请求网络，数据回来以后向集合中添加。问题是如何优雅的实现自动翻页呢。

第二个问题是，给主评论增加数据，我会的，文档里边也有。但是给子评论增加数据我就不会了，求指点啊

**Comment by liangjingkanji** [comment]
子评论的子评论都是新开一个界面吧, 你这种继续累加写起来很不方便和合理建议直接修改交互, 如果要写原理和所谓"主评论"是一样

至于自动翻页其搜索"RecyclerView跳转Item位置"

增删改查子列表记得同步更新`itemSublist`

**Comment by zkzk7749** [comment]
我没描述清楚。 

比如第一条主评论下，假如有30条子评论，我点击展开，请求了10条子评论。那么还有20条未展开，我第二次点击展开的时候，如何使用Net框架优雅的请求网络，并且把新来的这10条加入子评论集合中。

**Comment by liangjingkanji** [comment]
请参考demo中的`抖音评论列表`

**Comment by zkzk7749** [comment]
感谢东哥！

**Comment by liangjingkanji** [comment]
多看文档和demo吧, 举一反三, 灵活使用工具和框架
