### ISSUE TITLE
东哥，请问下，下面这种布局，出不来下拉刷新，是不是我什么地方弄的不对。

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#267]
如下列代码。
一个页面，两个接口。一个接口是专门用来请求RV的，一个接口请求非RV部分的。 现在这个页面的下拉效果出不来。

<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".ui.fragment.CoordinatorLayoutFragment">

        <com.google.android.material.appbar.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/windowBackground">

            <ImageView
                android:layout_width="match_parent"
                android:layout_height="250dp"
                android:background="#000000"
                app:layout_scrollFlags="exitUntilCollapsed|scroll|enterAlwaysCollapsed" />

            <com.google.android.material.tabs.TabLayout
                android:id="@+id/tab"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                app:tabMode="scrollable" />

        </com.google.android.material.appbar.AppBarLayout>

        <com.drake.brv.PageRefreshLayout
            android:id="@+id/page"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager" />
        </com.drake.brv.PageRefreshLayout>

    </androidx.coordinatorlayout.widget.CoordinatorLayout>
</layout>

**Comment by liangjingkanji** [comment]
两个接口请求关RV什么事情? 正常情况你等两个接口请求完毕再显示界面数据

**Comment by liangjingkanji** [comment]
你没有为`PageRefreshLayout`设置behavior当然无法联动滚动

**Comment by zkzk7749** [comment]
设置了的，我发出去了正准备补充 app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior"

**Comment by zkzk7749** [comment]
好的，我先试试等两个接口请求完毕再显示界面数据

**Comment by liangjingkanji** [comment]
```kotlin
 binding.page.onRefresh {
            scope {
                val bDeferred = Get<String>("https://github.com/liangjingkanji/Net/").await()
                val response = Get<HomeArticleModel>(String.format(Api.ARTICLE, index)).await()
                addData(response.datas) {
                    index < response.pageCount
                }
            }
        }.autoRefresh()
```

**Comment by zkzk7749** [comment]
已按照您的方式改了，一切正常，就是整个页面的下拉刷新无法触发

**Comment by liangjingkanji** [comment]
`app:layout_behavior`在哪?

**Comment by liangjingkanji** [comment]
麻烦你看下demo中的CoordinatorLayout示例

**Comment by zkzk7749** [comment]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".ui.fragment.CoordinatorLayoutFragment">

        <com.google.android.material.appbar.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/windowBackground">

            <ImageView
                android:layout_width="match_parent"
                android:layout_height="250dp"
                android:background="#000000"
                app:layout_scrollFlags="exitUntilCollapsed|scroll|enterAlwaysCollapsed" />

            <com.google.android.material.tabs.TabLayout
                android:id="@+id/tab"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                app:tabMode="scrollable" />

        </com.google.android.material.appbar.AppBarLayout>

        <com.drake.brv.PageRefreshLayout
            android:id="@+id/page"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior">

            
            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rvRecyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
            
        </com.drake.brv.PageRefreshLayout>

    </androidx.coordinatorlayout.widget.CoordinatorLayout>
</layout>

这是布局文件。
我看demo了，demo的最底下是viewpager.我这个直接是PageRefreshLayout包RV

**Comment by zkzk7749** [comment]
滑动，联动什么的都没问题。就是下拉刷新无法触发

**Comment by zkzk7749** [comment]
好的，感谢东哥。我发现问题了，下拉刷新无法触发我用别的方式处理，比如增加头部啥的

**Comment by liangjingkanji** [comment]
没理解你说的话 "下拉刷新无法触发我用别的方式处理，比如增加头部啥的"

**Comment by zkzk7749** [comment]
也就是说我，我不使用CoordinatorLayout了，我直接给rv增加头部布局就行。
这样的话PageRefreshLayout就可以直接包裹RV了。


另外再请教东哥一个问题。 就是抖音列表那里。增加主评论并且刷新列表，我会，demo写的很详细。

但是，增加了子条目，我这个废柴，只会添加数据也就是添加itemSublist，但是不会刷新了列表了

**Comment by liangjingkanji** [comment]
添加itemSublist还需要添加item
