### ISSUE TITLE
局部刷新问题

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#268]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

![图片](https://user-images.githubusercontent.com/28262649/191697531-bf2c26be-5a33-4392-89cd-b36432599b54.png)

局部刷新时，怎么拿到点击的item 的 index？  modelPosition 是这个字段？

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/191709406-ff0c3f39-5861-4b26-bc89-6a0a6bf0201c.png)
看了你的demo,  是用这个？

**Comment by liangjingkanji** [comment]
我一般用`layoutPosition`
你点击查看modelPosition源码可以看到他是减去了`headCount`
