### ISSUE TITLE
嗨，东哥，Brv框架是不能指定自己的LayoutManager吗

### ISSUE THREAD

**Issue by zhangzhiao** [liangjingkanji/BRV#269]
fun RecyclerView.linear(
    @RecyclerView.Orientation orientation: Int = VERTICAL,
    reverseLayout: Boolean = false,
    scrollEnabled: Boolean = true,
    stackFromEnd: Boolean = false
): RecyclerView {
    layoutManager = HoverLinearLayoutManager(context, orientation, reverseLayout).apply {
        setScrollEnabled(scrollEnabled)
        this.stackFromEnd = stackFromEnd
    }
    return this
}

**Comment by zhangzhiao** [comment]
看了下源码解决了，linear()后面重新set就行，打扰了，如果会有其他问题麻烦告诉我，没有的话我明天之前关掉issues

**Comment by zhangzhiao** [comment]
linear().apply {
            layoutManager =
                LooperLayoutManager(context).apply { orientation = LinearLayoutManager.VERTICAL }
        }

**Comment by TxcA** [comment]
> linear().apply { layoutManager = LooperLayoutManager(context).apply { orientation = LinearLayoutManager.VERTICAL } }

能用，但是多此一举。
你都看源码了，linear只是设置`LayoutManage`，为何还先调用`linear()`再去覆盖设置一次`LooperLayoutManager`。

```kotlin
recyclerView.run {
    layoutManager = LooperLayoutManager(context).apply { orientation = LinearLayoutManager.VERTICAL }
    setup {

    }
}

```

如果该layoutManage使用较多，可以写一个类似`linear()`的扩展方法
```kotlin
fun RecyclerView.flex(
    @FlexDirection flexDirection: Int = FlexDirection.ROW,
    @FlexWrap flexWrap: Int = FlexWrap.WRAP,
): RecyclerView {
    layoutManager = FlexboxLayoutManager(context, flexDirection, flexWrap)
    return this
}

---

recyclerView.flex().setup {

}
```

**Comment by zhangzhiao** [comment]
啊，确实，谢谢，直接setup就可以了
