### ISSUE TITLE
感觉这个框架会异军突起 尤其在BRVAH常年不维护的情况下

### ISSUE THREAD

**Issue by Zengyonghao** [liangjingkanji/BRV#27]
感觉这个框架会异军突起  尤其在BRVAH常年不维护的情况下

**Comment by liangjingkanji** [comment]
README有QQ群图标, 点击自动加群

**Comment by liangjingkanji** [comment]
无论BRVAH是否更新都完爆之, 开发效率提升600%

**Comment by JimmyZou92** [comment]
希望作者如果有一天不想维护了,一定要写出来,不要让使用者白等,谢谢了,感激感激

**Comment by liangjingkanji** [comment]
我个人也非常反感不维护, 更别说像某些人一直不标注"废弃". 

我已经保持3年我的所有仓库都一直在维护中, 而且我也在寻求社区共同更好地维护项目

**Comment by SupLuo** [comment]
> 我个人也非常反感不维护, 更别说像某些人一直不标注"废弃".
> 
> 我已经保持3年我的所有仓库都一直在维护中, 而且我也在寻求社区共同更好地维护项目

没找到进群的入口呢，可能是因为readme首页有几个图我加载不出来？麻烦谁发一下QQ号

**Comment by liangjingkanji** [comment]
> > 我个人也非常反感不维护, 更别说像某些人一直不标注"废弃".
> > 我已经保持3年我的所有仓库都一直在维护中, 而且我也在寻求社区共同更好地维护项目
> 
> 没找到进群的入口呢，可能是因为readme首页有几个图我加载不出来？麻烦谁发一下QQ号

621712280

GitHub图片都无法加载出来吗? 你可以尝试点击图片, 或者尝试修改自己的DNS, 因为群随时被封可能会更新

**Comment by SupLuo** [comment]
> 621712280

只有两三个小图标加载不出来，我都尝试点击过，实在不行。

**Comment by wuyihao99** [comment]
> README有QQ群图标，点击自动加群

721362171是这个qq群吗？

**Comment by wuyihao99** [comment]
> 

621712280这个qq是空的。。。。

**Comment by liangjingkanji** [comment]
> > README有QQ群图标，点击自动加群
> 
> 721362171是这个qq群吗？

是的，相信README

**Comment by Uimix** [comment]
如果能出java版，我相信，这个框架一定能排No.1

**Comment by liangjingkanji** [comment]
> 如果能出java版，我相信，这个框架一定能排No.1

永远不可能, 别想了, 坚持写Java的人不需要什么框架

**Comment by liangjingkanji** [comment]
实际上这个框架你可以让他支持Java, 自己封装下
