### ISSUE TITLE
分组列表，在展开分组后修改列表内容然后刷新会出现类型转换错误

### ISSUE THREAD

**Issue by MattLjp** [liangjingkanji/BRV#272]
在分组Demo的基础上添加修改列表内容并刷新列表
![image](https://user-images.githubusercontent.com/53996180/196620121-8b91498a-cffe-402a-afd7-d808903d580c.png)

**Comment by liangjingkanji** [comment]
这是你类型转换错误, 集合里面可不止有GroupDragBasicModel, 还有GroupDragModel, 请仔细阅读错误信息

**Comment by liangjingkanji** [comment]
你的错误信息位置你没有截图出来, 我无法判断你的错误, 请自己debug调试下具体错误发生位置, 这是简单的类型转换错误

**Comment by liangjingkanji** [comment]
如果依然没有解决问题或者fork仓库本问题将被关闭
