### ISSUE TITLE
在上拉加载的时候有没有可能去掉上拉加载动画

### ISSUE THREAD

**Issue by HandSomeMaster** [liangjingkanji/BRV#274]
## 问题描述
在上拉加载的时候去掉上拉动画
### 期望行为
用户上拉列表，正常情况下感觉不到列表有上拉加载的动作

**Comment by liangjingkanji** [comment]
当然可以, 上拉加载使用的是[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout), 这是Android扩展性最强的下拉刷新库

你可以通过自定义实现`RefreshFooter`接口来去除上拉加载动画, [参考文档](https://github.com/scwang90/SmartRefreshLayout/blob/master/art/md_custom.md)

**Comment by liangjingkanji** [comment]
快速支持无动画的上拉加载这个提议可以考虑

**Comment by liangjingkanji** [comment]
参考文档描述: [关闭上拉加载动画](https://liangjingkanji.github.io/BRV/refresh/#_10)

**Comment by north521** [comment]
> 
这个参考文档打不开了

**Comment by liangjingkanji** [comment]
> > 
> 
> 这个参考文档打不开了

你再试下，如果文档打不开可以尝试自己在文档通过标题寻找
