### ISSUE TITLE
多类型布局

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#278]
## 问题描述

![图片](https://user-images.githubusercontent.com/28262649/198945500-440c9d84-5f38-428f-bdba-eeb0b6194023.png)

这下面怎么写？
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
你调用Activity方法干什么

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/198950976-597cdd54-73ec-4407-b836-f906a24077a8.png)

知道怎么写了

**Comment by liangjingkanji** [comment]
我还是更推荐你使用Databinding, 代码以及bug都更少
