### ISSUE TITLE
onbind 问题

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#279]
## 问题描述

![图片](https://user-images.githubusercontent.com/28262649/198946838-60f95194-0713-4cac-aba0-56186a185d02.png)

这里还要写findview , 可以封装一下？
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
你的意思是写一系列`setText/setImage`等方法? 我认为那会极大增加框架复杂度没必要

另外本框架推荐的是databinding mvvm数据绑定, 几乎不需要使用`findView()`

**Comment by lastzhou** [comment]
嗯  跟BRVAH 类似。
1，databinding 已经废弃了，官方推荐 viewbind

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/198952647-a8ffe310-bb32-43d6-9aa6-e46faa3cd6ff.png)

我现在用的viewbind , 如果 viewbind 也废弃，那就只能手动封装了

**Comment by liangjingkanji** [comment]
1. DataBinding没有废弃, 最近AS更新还有关于他的更新(因为DataBinding是跟随AS发布的), 可能有人会说DataBinding官方开发者说不会支持KSP, 那是因为支持KSP本身的确意义不太大
2. ViewBinding支持一个取代findViewById的功能, 和DataBinding的双向数据绑定功能就不是一个东西, DataBinding只是附带这个功能罢了

没有任何一篇官方文章说推荐使用ViewBinding取代DataBinding, ViewBinding支持方便那些一直在用findViewById的人
