### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#280]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间
![图片](https://user-images.githubusercontent.com/28262649/198976352-1af02ea1-9ecc-435d-bb18-74b27b2357fa.png)

当刷新时需要清空原来数据，我这个没起作用，还有什么办法？

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
`addData()`会自动处理清空数据和重置index

**Comment by lastzhou** [comment]
ok，很强大，  还有个问题  
![图片](https://user-images.githubusercontent.com/28262649/198980015-50d01a22-f1b3-4726-b632-6f3af4ff64aa.png)

怎么把这个请求，提取出来放到refresh,  如果提取出来，就不能调用内部的addData() 方法了

**Comment by TxcA** [comment]
![1N{`_55{F$}V~VF}IXPHSXO](https://user-images.githubusercontent.com/15992858/198980953-58f84bfd-09f1-47dc-a813-092ae15c2264.png)

把你的`onLoadMore{ }` 和 `refresh` 删掉就好了。不配置`onLoadMore{ }` 会自动执行`onRefresh{ }`的。

还有就是:
```kotlin
    private fun PageRefreshLayout.refresh() {
        scope {
            // this is PageRefreshLayout.scope
        }
    }

    private fun refresh(page: PageRefreshLayout) {
        page.scope {
            // this is PageRefreshLayout.scope
        }
    }
```

**Comment by lastzhou** [comment]
ok  强大，可以跟据内部的index 来联动

**Comment by lastzhou** [comment]
你们这个demo里面，如果超过了这个，就自动停止上拉加载，不用手动处理？？

**Comment by liangjingkanji** [comment]
> 你们这个demo里面，如果超过了这个，就自动停止上拉加载，不用手动处理？？ ![图片](https://user-images.githubusercontent.com/28262649/198986613-f9db3954-8d0a-42da-aad9-ee6b1790f1f0.png)

当然, 不然怎么叫自动分页加载, 一般`total`这个字段由后端数据返回
