### ISSUE TITLE
onPayload 函数建议

### ISSUE THREAD

**Issue by shenbengit** [liangjingkanji/BRV#281]
## 问题描述
onPayload()只返回了payloads列表的第一个值。

### 期望行为
onPayload()返回payloads整个列表。
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
![image](https://user-images.githubusercontent.com/24364422/199937772-c1933fae-333a-41f2-ac40-62b5af3d8573.png)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.3.82
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
的确没有考虑到多次调用合并数据问题, 已修复, 欢迎发起pr
