### ISSUE TITLE
请问上拉加载的底部的loadMoreView是SmartRefresh还是brv提供的呢？brv可以自定义吗？

### ISSUE THREAD

**Issue by SinceJulyzzZ** [liangjingkanji/BRV#282]
## 问题描述

BRVAH提供了 如
![image](https://user-images.githubusercontent.com/64911679/200291072-782a839a-23cb-45d6-9205-b6b27f4cfc57.png)

请问BRV可以自定义吗？   还是只每个都自己加Footer呢
## 截图

![94b0cbf09e0d797a4573db202bbfe7d](https://user-images.githubusercontent.com/64911679/200284792-6c7920ce-9d42-4b17-a90c-1417efb110b7.jpg)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
SmartRefreshLayout提供的, 而`PageRefreshLayout`继承自SmartRefreshLayout, 详情可以点开查看源码注释或使用文档

**Comment by liangjingkanji** [comment]
> 好的谢谢解答，意思是BRV自身没有提供此项功能对吧？

BRV通过内嵌SmartRefreshLayout实现此功能, 而且PageRefreshLayout是BRV特有的类, 我认为可以理解为BRV支持此功能
