### ISSUE TITLE
选择模式问题

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#285]
## 问题描述

![图片](https://user-images.githubusercontent.com/28262649/200514799-efd639c6-9c91-4eb3-8849-39d69f5bc15b.png)
仿照demo,数据初始化时，这里为false , 界面上却还能显示
### 期望行为
应该是不可见
## 如何复现

![图片](https://user-images.githubusercontent.com/28262649/200515220-0d0ad5d3-95d5-4811-b7af-2b559e413445.png)
我没有在xml, 中绑定checkbox
> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
你使用ViewBinding绑定Activity的`layoutInflater`干什么? 你这不止一次犯这种上下文错乱的低级错误了

**Comment by liangjingkanji** [comment]
请仔细阅读demo和排错

**Comment by lastzhou** [comment]
databing 和viewbing 我都用了，搞混了
