### ISSUE TITLE
ViewBinding支持复用

### ISSUE THREAD

**Issue by von-mon** [liangjingkanji/BRV#286]
## 问题描述
addType<SimpleModel>(R.layout.item_simple) 不支持viewBinding
### 期望行为
期望支持view Binding ，不习惯使用databinding
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
文档和demo不是都有使用示例吗?

[ViewBinding](https://liangjingkanji.github.io/BRV/view-binding/)

**Comment by liangjingkanji** [comment]
ViewBinding只是取代findViewById的一个小工具而已, 和DataBinding不是同类型框架(DataBinding包含ViewBinding的功能)

DataBinding是双向数据绑定工具

我不明白你说`addType()`不支持ViewBinding是什么情况? 两者没有什么关系吧?

**Comment by jin123d** [comment]
> ViewBinding只是取代findViewById的一个小工具而已, 和DataBinding不是同类型框架(DataBinding包含ViewBinding的功能)
> 
> DataBinding是双向数据绑定工具
> 
> 我不明白你说`addType()`不支持ViewBinding是什么情况? 两者没有什么关系吧?

根据官方的`recyclerView`的[使用说明 ](https://developer.android.com/guide/topics/ui/layout/recyclerview?hl=zh-cn#implement-adapter)，ViewHolder在创建时，就直接调用findViewById来方法来获取子view，在`onBindViewHolder`时即可直接操作子view。
按照目前BRV 文档中的用法，如果`dataBindingEnable`时，会生成`viewDataBinding`，并且传递到`BindingViewHolder`中，这种使用是正确的。
但是如果不使用`dataBinding`，按照文档所写，则是在`onBind()`方法中进行`findview`（使用`ViewBinding`亦是如此，在`onBind()`方法中调用`ItemSimpleBinding.bind(itemView)`）。
按照我的理解，是否应该在`onCreate()` 进行ItemSimpleBinding.bind(itemView)，【文档中虽然写了`onCreate()` 调用`ItemSimpleBinding.bind()`，但是生成的`binding`类并未传递到`ViewHolder`】，在`onBind()`时拿到生成的生成的`binding`类来进行UI操作。

简言之，
>* `onBind()`方法中进行`findview`是否合理（不使用ViewBinding时。
>* `ViewHolder`类是否需要持有生成的binding类(使用ViewBinding时)。

**Comment by liangjingkanji** [comment]
1. 合理, BRVAH亦或原始的RecyclerView.ViewHolder都是在OnBindViewHolder里面findViewById()
2. 如下


关于你说的ViewHolder直接持有binding类(就像databinding使用getBinding<V>()一样)我认为可以考虑

但是为什么我一直没有实现这是因为我认为并没有简化多少代码量并且ViewBinding本身不适合封装
```kotlin
val binding = getBinding<ItemViewBinding>()
val binding = ItemViewBinding.bind(itemView)
```

但是@DylanCaiCoding提过在onBind中反复调用`bind()`稍微影响性能(https://github.com/DylanCaiCoding/ViewBindingKTX/issues/51#issuecomment-1135320358), 应当进行缓存. 当初我的看法是性能影响微乎其微并且可以自己在model中缓存

但是现在我认为让ViewBinding和DataBinding用法趋同可能更好, 并且减少学习成本, 关于这点提议我觉得可以改进下, 也欢迎你Pr

**Comment by liangjingkanji** [comment]
#288 使用getBinding()获取ViewBinding实例

这是不是你想要的效果

**Comment by jin123d** [comment]
> 



> 1. 合理, BRVAH亦或原始的RecyclerView.ViewHolder都是在OnBindViewHolder里面findViewById()
> 2. 如下
> 
> 关于你说的ViewHolder直接持有binding类(就像databinding使用getBinding()一样)我认为可以考虑
> 
> 但是为什么我一直没有实现这是因为我认为并没有简化多少代码量并且ViewBinding本身不适合封装
> 
> ```kotlin
> val binding = getBinding<ItemViewBinding>()
> val binding = ItemViewBinding.bind(itemView)
> ```
> 
> 但是@DylanCaiCoding提过在onBind中反复调用`bind()`稍微影响性能([DylanCaiCoding/ViewBindingKTX#51 (comment)](https://github.com/DylanCaiCoding/ViewBindingKTX/issues/51#issuecomment-1135320358)), 应当进行缓存. 当初我的看法是性能影响微乎其微并且可以自己在model中缓存
> 
> 但是现在我认为让ViewBinding和DataBinding用法趋同可能更好, 并且减少学习成本, 关于这点提议我觉得可以改进下, 也欢迎你Pr

关于第一点，我看官方的文档是在onCreateViewHolder，并不是在onBindViewHolder中进行findViewById,文档在这里
https://developer.android.com/guide/topics/ui/layout/recyclerview?hl=zh-cn#implement-adapter

**Comment by jin123d** [comment]
> 关于 @jin123d 说的第一点, 那无法封装实现的(因为ViewBinding需要指定具体类), 而且也没有必要, 我认为你没有理解官方写的目的
> 
> 官方示例是为了避免频繁触发`onBindViewHolder`来findViewById以减少轻微性能损耗, 但是`getBinding()`本身也会进行缓存, 所以两者性能一致
> 
> 即使每次在onBindViewHolder里面findViewById对性能影响也比较轻微, 例如比较有名气的BRVAH完全没有缓存每次都会去findViewById
> 
> 如果你有更好的解决办法欢迎提出

我同意你的第二点的解决方法，只是对`原始的RecyclerView.ViewHolder都是在OnBindViewHolder里面findViewById()`这句话有点疑问，目前来看`getBinding()`已经能够达到缓存的目的了。

**Comment by liangjingkanji** [comment]
@jin123d 欢迎共同探讨实现方案
