### ISSUE TITLE
麻烦看下Android Studio 使用 assemble 打包失败的问题

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#287]
D:/gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

该项目没使用kotlin，所以我也不知道这个应该怎么解决😂

**Comment by SaltedFish-Extreme** [comment]
D:/gradle/caches/transforms-2/files-2.1/0a20ec77ce1c7059350ffcf45d4d2037/jetified-BRV-1.3.83/jars/classes.jar!/META-INF/brv_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

**Comment by liangjingkanji** [comment]
这是gradle升级导致的问题, 和本框架无关, 可以尝试添加以下代码解决

```
lintOptions {
    checkReleaseBuilds false
}
```

**Comment by SaltedFish-Extreme** [comment]
好的，麻烦东哥了，谢谢了😂
