### ISSUE TITLE
关注我抖音号: dynp9ncittb2是本人吗？

### ISSUE THREAD

**Issue by lishangwl** [liangjingkanji/BRV#289]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
互联网虚拟形象

**Comment by zkzk7749** [comment]
已关注

**Comment by liangjingkanji** [comment]
> 已关注

最近开始摆摊卖咖喱了
