### ISSUE TITLE
使用Databinding绑定，在布局里面如何获取索引？

### ISSUE THREAD

**Issue by rayzeng0221** [liangjingkanji/BRV#291]
我的需求是需要根据索引改变Item背景，我不想在onbind里面进行判断，也不想通过ItemBinding,想直接在布局通过自定义属性实现，能想到的办法就是给实体增加字段来知道索引，我想知道还有其他方式吗？

**Comment by liangjingkanji** [comment]
BRV支持4中绑定数据方式, 数据模型实现ItemBind接口(类似BRVAH的)你还没提到
