### ISSUE TITLE
BindingAdapter.mutable不支持com.google.protobuf.ProtobufArrayList数据集合

### ISSUE THREAD

**Issue by EspoirX** [liangjingkanji/BRV#293]
如题，比如我直接用pb的数据做数据源，就遇到了这个：

ClassCastException: com.google.protobuf.ProtobufArrayList cannot be cast to java.util.ArrayList

最好做下类型判断吧

**Comment by liangjingkanji** [comment]
BRV不可能无法将`com.google.protobuf.ProtobufArrayList`导入到项目中, 请自己封装该方法

```kotlin
var mutable get() = models as ProtobufArrayList
```

**Comment by liangjingkanji** [comment]
框架只能考虑大部分情况, 并且遵守低耦合高内聚原则, 无法兼容第三方框架. 必要时请自己处理一些自己特有框架代码

欢迎参与pr代码贡献

**Comment by EspoirX** [comment]
我的意思是存在这种情况，我遇到的只是其中一个例子，并不是说要把ProtobufArrayList导入，
如果设计是不兼容就抛异常，那没问题的。
如果不是，我觉得可以完善一下，比如不是ArrayList就做个类似你里面扁平化的操作？

**Comment by liangjingkanji** [comment]
`mutable`返回的是自身可变集合对象, 不可能`new`一个新的集合对象实例返回, 那样即使修改也和源集合没有关系
