### ISSUE TITLE
头部添加问题

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#295]
## 问题描述
![图片](https://user-images.githubusercontent.com/28262649/202611269-64ba6dc6-95c4-4198-a75b-89ec35dd58ca.png)
将顶部banner,加到head 里面， 列表和banner数据模型, 不一样

![图片](https://user-images.githubusercontent.com/28262649/202611554-8ed3f084-4c0e-4171-8adf-3ef0a5d41ae0.png)
用这种方式，好像不能实现
### 期望行为
还有其他方式？

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
Banner应该需要一个集合对象作为他的数据集, 而你认为集合对象不能作为item数据模型? 集合也是对象, 甚至和String没有本质区别

**Comment by liangjingkanji** [comment]
你问的此问题和brv无关

**Comment by lastzhou** [comment]
我知道，你意思是把 banner 的数据模型，整合到列表的数据模型里面去

**Comment by liangjingkanji** [comment]
一个集合也是一个数据模型, 思维不要太顽固
