### ISSUE TITLE
东哥你好，小弟请教一个问题哈

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#296]
我们这个库如何优雅的使用stubview呢，我在文档中没找到介绍

**Comment by liangjingkanji** [comment]
本库是快速构建RecyclerView列表, 和`StubView`没有关系

**Comment by zkzk7749** [comment]
是的，但是RecyclerView列表中，可以有StubView，这个可以有的吧

**Comment by zkzk7749** [comment]
比如个别控件显示频率不高，但是偶尔有又不能忽略它，用多布局又有些浪费资源时

**Comment by liangjingkanji** [comment]
这个和TextView没区别, 自己想怎么用就怎么用, 我不可能Item上面显示什么布局我还要介绍使用

**Comment by liangjingkanji** [comment]
你要文档精细到这种程度?? 我觉得有点夸张了, 要不我开个5000课程你付费学吧

**Comment by zkzk7749** [comment]
好的，感谢东哥

**Comment by zkzk7749** [comment]
我主要是想看有没有更好的方法随时控制StubView的inflate.  必须直接可以@{ }的，我先用笨办法试试

**Comment by liangjingkanji** [comment]
> 我主要是想看有没有更好的方法随时控制StubView的inflate. 比如直接可以用@{ }这种表达式的，我先用笨办法试试

ViewStup只是需要控制显示隐藏即可, 自动会inflat, 或者你自己自定义一个`@BindingAdapter`属性

不要刻意去追求不明确的性能优化, 特别是为牺牲代码可读性去复用/优化性能, 有时候`View.GONE`或者多类型更合适
