### ISSUE TITLE
空页面的设计

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#297]
## 问题描述
com.drake.statelayout.StateLayout  感觉不太好用，xml上每次都要嵌套recyclerview, kotlin 代码也要调用。
### 期望行为
能否利用 BRV，设计一个空页面？
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
高内聚低耦合, BRV不会取代StateLayout功能, 但是PageRefreshLayout自身已经内嵌StateLayout来实现缺省页无需再写一遍, 请仔细阅读demo案例

当然你可以自己通过Adapter来实现空页面功能, 目前我并没有更好的思路, 欢迎发起pr
