### ISSUE TITLE
多布局 onCreate 里面判断itemViewType 都是-1

### ISSUE THREAD

**Issue by 287138531** [liangjingkanji/BRV#298]
## 问题描述
多布局 onCreate 里面判断itemViewType 都是-1
 想实现的是rv嵌套rv，然后在父rv初始化的 onCreate，初始化子rv。。如滑动卡顿里面的说明
但是实际onCreate里面没法初始化子rv
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
优化下避免歧义, onCreate现在已经支持itemViewType值

**Comment by liangjingkanji** [comment]
开源项目的优势在于社区力量, 欢迎共同改进维护本项目
