### ISSUE TITLE
com.drake.brv.PageRefreshLayout 嵌套问题

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#299]
## 问题描述

![图片](https://user-images.githubusercontent.com/28262649/203518874-5305691b-5f14-49bf-87e5-6005865f6e2c.png)

![图片](https://user-images.githubusercontent.com/28262649/203519112-7cce5a52-e860-4104-b9c7-edcc2ad14033.png)

![图片](https://user-images.githubusercontent.com/28262649/203519513-b7a3bcde-d1b9-422a-876e-f658e8b3a49d.png)

我已经指定了 recycleview id 了，为毛还是加载不出来数据，  PageRefreshLayout 只能套一个recycleview?
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
在哪指定的`recyclerViewId`?

**Comment by liangjingkanji** [comment]
仔细阅读下demo的`PagePartStateFragment`吧

**Comment by liangjingkanji** [comment]
```kotlin
var bind = ItemAriticleBinding.bind(itemView)
```
可以改成

```kotlin
val binding = getBinding<ItemAriticleBinding>()
```

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/203520631-7c40686e-b9c7-47d5-8311-c20524760ded.png)
知道了，我写错了

**Comment by liangjingkanji** [comment]
你代码一堆警告也就算了, 眼神还一直不好, 平时有空多学门手艺吧
