### ISSUE TITLE
如何优化，实现空页面的功能

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/BRV#301]
## 问题描述
![图片](https://user-images.githubusercontent.com/28262649/203753719-db0fc557-56c5-4bd5-a1c1-0ae9ad679230.png)
![图片](https://user-images.githubusercontent.com/28262649/203753974-5deab39f-1ee7-405e-a2c5-adaab585b730.png)

用了一个变量保存空页面的id，可以不用变量？

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
没看得懂你说的什么意思

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/203758898-f87628a0-0c49-42f7-8d7c-04c397a53b32.png)

改了源码，可以后台实现空页面了，到时我提交一个分支，你看一下

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/203759415-e243286e-c4dc-46b0-a33f-cdd8dc5be549.png)
改了下源码，基本可以实现代码添加空页面了，到时提一个分支

**Comment by liangjingkanji** [comment]
那错误缺省页呢? 
我不认为BindingAdapter需要去负责处理缺省页, 并且缺省页也不一定是列表
而且你这样改造影响`自动缺省页`功能, 不知道你是否使用了Net的自动缺省页功能

**Comment by lastzhou** [comment]
获得收益：
1，首页一般都比较复杂，局部处理空页面会变的简单
2，需要定制缺省页面，也很简单

**Comment by lastzhou** [comment]
你的框架很优秀，是我多虑了

**Comment by liangjingkanji** [comment]
按照你的理解的局部缺省页不仅仅是一个emptyLayoutId可以解决的, 这种情况建议自己写多类型
