### ISSUE TITLE
有些问题想请问一下

### ISSUE THREAD

**Issue by MurasameAya** [liangjingkanji/BRV#303]
## 问题描述
1.在使用现在的最新版本时，只要一下拉刷新，列表上方有一个空白。能否请教一下这个是什么？而且没有像demo的APK有一个refreshing的gif
2.想请问下addData()如何能增量更新

## 截图
1.这是进来这个页面后下拉刷新的动作执行后的截图。然后一直上下拉都不会消失
<img width="182" alt="企业微信截图_16693677722740" src="https://user-images.githubusercontent.com/52487645/203944754-856ff6f9-01a7-4336-98cd-52a6d6ae065c.png">
2.这是相关的代码，如果有哪里做错的话，能麻烦告知我一下吗？
<img width="258" alt="企业微信截图_16693679569892" src="https://user-images.githubusercontent.com/52487645/203944943-be94aeb9-cd5c-4ea0-ad2c-0c41ff04159a.png">

## 版本
- ### BRV:1.3.86
- Android:
- Gradle: 
- Android Studio:

> 

>

**Comment by liangjingkanji** [comment]
### 提问回答

1. 是否是没有配置SmartRefreshLayout? 能否fork仓库复现问题?
2. 你说的增量更新是否是rv的`diffUtils`功能? 还是指的`notifyDataItemChanged()`增量通知内容更新



### 代码问题

另外请仔细阅读文档/demo, 因为你写的代码有严重问题

1. 你`autoRefresh()`调用2次干什么
1. 当onRefresh和onLoadMore一样逻辑的时候只需要写`onRefresh`即可

**Comment by xuexixuexijpg** [comment]
想问下支持原来的传payload这种写法吗？

**Comment by xuexixuexijpg** [comment]
> > 想问下支持原来的传payload这种写法吗？
> 
> 支持

请问如果我xml里面做了数据绑定然后代码里面也写了onBind这两个有冲突吗？我代码onBind里做了部分UI绑定数据，有些放在了xml里绑定，然后我xml里绑定的数据显示不了...

**Comment by liangjingkanji** [comment]
> > > 想问下支持原来的传payload这种写法吗？
> > 
> > 
> > 支持
> 
> 请问如果我xml里面做了数据绑定然后代码里面也写了onBind这两个有冲突吗？我代码onBind里做了部分UI绑定数据，有些放在了xml里绑定，然后我xml里绑定的数据显示不了...

不冲突, 如果无法解决问题请fork仓库复现问题发送给我地址
