### ISSUE TITLE
列表重新赋值数据可以恢复列表展开状态

### ISSUE THREAD

**Issue by wwy863399246** [liangjingkanji/BRV#305]
## 问题描述
viewmodel保存的分组集合数据，更新到1.3.84以上 用setDifferModel 无法正确恢复列表状态

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.3.84
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
不知道问题所在, 能fork仓库复现问题吗?

**Comment by wwy863399246** [comment]
navigation  我用viewmodel保存的分组列表数据，每次返回到当前页面数据都会增加，用1.3.83 的setDifferModel()可以恢复到正确数据，后面的版本这个方法就失效。我有空发个demo 过来

**Comment by liangjingkanji** [comment]
你是否在`Fragment.onViewCreated()`中进行的网络请求?  参考下[EngineNavFragment](https://github.com/liangjingkanji/Engine/blob/HEAD/engine/src/main/java/com/drake/engine/base/EngineNavFragment.kt#L49)

**Comment by wwy863399246** [comment]
veiw会重建，为了防止重复请求，用viewmodel 保存数据，还原状态的时候分组列表的数据会出现重复的数据，所以还原的是时候用的setDifferModel ，1.3.84后这个方法就没用了

**Comment by liangjingkanji** [comment]
如何还原?

**Comment by liangjingkanji** [comment]
请fork仓库复现问题, 否则本问题将被关闭

**Comment by liangjingkanji** [comment]
star按钮右边是fork, 就会将仓库拉取到自己账号下面然后你修改复现问题后提交告诉我, 发我你fork的仓库地址就行了

**Comment by liangjingkanji** [comment]
以前开始, 分组展开后的数据就无法进行重新赋值达到恢复"展开后列表状态"

从现在开始会计划支持这个需求

**Comment by liangjingkanji** [comment]
升级到最新版本即可

**Comment by wwy863399246** [comment]
好的，谢谢，最近很忙，没时间去复现



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月08日 10:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [liangjingkanji/BRV] 列表重新赋值数据可以恢复列表展开状态 (Issue #305) |

升级到最新版本即可
