### ISSUE TITLE
1.3.31版本无法下载

### ISSUE THREAD

**Issue by liuxiaoliu66** [liangjingkanji/BRV#31]
已经尝试清除缓存重启，只能继续使用1.3.29版本

**Comment by liangjingkanji** [comment]
我这边下载正常, 请你截图下你无法下载的信息

**Comment by liuxiaoliu66** [comment]
> Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
     Required by:
         project :app > com.github.liangjingkanji:BRV:1.3.31
      > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
         > Could not get resource 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
               > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
         > Could not get resource 'https://jitpack.io/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
            > Could not GET 'https://jitpack.io/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
               > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
               > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
               > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
   > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
     Required by:
         project :app > com.github.liangjingkanji:BRV:1.3.31
      > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
         > Could not get resource 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
               > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
         > Could not get resource 'https://jitpack.io/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
            > Could not GET 'https://jitpack.io/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
               > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
               > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
               > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect

**Comment by liangjingkanji** [comment]
你是不是删掉了jcenter()

**Comment by liuxiaoliu66** [comment]
我试试

**Comment by liangjingkanji** [comment]
解决了吗

**Comment by txwgoogol** [comment]
> > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > Required by:
> > project :app > com.github.liangjingkanji:BRV:1.3.31
> > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > Could not get resource 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > Could not GET 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > Could not get resource 'https://jitpack.io/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > Could not GET 'https://jitpack.io/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > Could not get resource 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > Could not GET 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > Could not get resource 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > Could not GET 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > Required by:
> > project :app > com.github.liangjingkanji:BRV:1.3.31
> > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > Could not get resource 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > Could not GET 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > Could not get resource 'https://jitpack.io/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > Could not GET 'https://jitpack.io/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > Could not get resource 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > Could not GET 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > Could not get resource 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > Could not GET 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect


> > >

你的gradle版本是不是7.0以后的，这个项目依赖的SmartRefreshLayout是JCenter仓库的，Gradle 7.0 以后就不能用了，导致依赖BRV有问题，，，应该是这样的，

**Comment by liangjingkanji** [comment]
> > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > Required by:
> > > project :app > com.github.liangjingkanji:BRV:1.3.31
> > > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > > Could not get resource 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > > Could not GET 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > > Could not get resource 'https://jitpack.io/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > > Could not GET 'https://jitpack.io/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > > Could not get resource 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > > Could not GET 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > > Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
> > > > Could not get resource 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > > Could not GET 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-layout-kernel/2.0.3/refresh-layout-kernel-2.0.3.pom'.
> > > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > > Required by:
> > > > project :app > com.github.liangjingkanji:BRV:1.3.31
> > > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > > Could not get resource 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > > Could not GET 'https://maven.aliyun.com/repository/public/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > > Could not get resource 'https://jitpack.io/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > > Could not GET 'https://jitpack.io/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > > Could not get resource 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > > Could not GET 'https://repo.maven.apache.org/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> > > > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
> > > > Could not get resource 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > > Could not GET 'https://dl.google.com/dl/android/maven2/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
> > > > Connect to 127.0.0.1:10809 [/127.0.0.1] failed: Connection refused: connect
> 
> > > >
> 
> 你的gradle版本是不是7.0以后的，这个项目依赖的SmartRefreshLayout是JCenter仓库的，Gradle 7.0 以后就不能用了，导致依赖BRV有问题，，，应该是这样的，

jcenter是永久只读仓库, gradle不存在直接禁用, 最多提示废弃

**Comment by liuxiaoliu66** [comment]
已经解决了，应该是gradle的代理问题
