### ISSUE TITLE
列表为空的时候，下拉刷新，出现动画不会自动关闭的情况

### ISSUE THREAD

**Issue by syxc** [liangjingkanji/BRV#310]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.3.86
- Android: 11
- Gradle: 7.2.2
- Android Studio: 2021.3.1 Patch 1

以下是部分代码：

```kotlin
page?.onRefresh {
  pageIndex = index

  queryMessageData(
    if (pageIndex == 1) {
      1
    } else {
      pageIndex
    }
  )

  val data = getMessageData()
  addData(data) {
    pageIndex < totalPage
  }
}
```

**Comment by liangjingkanji** [comment]
无法复现, 希望你能在demo中复现此问题

**Comment by syxc** [comment]
> 无法复现, 希望你能fork仓库在demo中复现此问题, 可以立刻解决

找到原因了，分析如下：
```kotlin
// 非 binding 方式加载 layout 的情况下
page = rootView?.findViewById(R.id.page) /* 这种，下拉刷新正常 */
rv = rootView?.findViewById(R.id.rv)
// page = rv?.pageCreate() /* 这种，下拉刷新会出现问题（动画出现不会自动关闭的情况）*/
```
已解决。

**Comment by liangjingkanji** [comment]
pageCreate并不推荐使用, 但是我认为可能是你多次调用pageCreate导致创建多个PageRefreshLayout

2022年了还在findViewById吗

**Comment by syxc** [comment]
> pageCreate并不推荐使用, 但是我认为可能是你多次调用pageCreate导致创建多个PageRefreshLayout
> 
> 2022年了还在findViewById吗

这种页面需要 findViewById 的情况不多，够用，够用...
