### ISSUE TITLE
多类型列表选择模式，怎么排除一些不需要选择的类型？

### ISSUE THREAD

**Issue by 287138531** [liangjingkanji/BRV#312]
## 问题描述
如题，现在我是手动遍历数据去判断是否全选的，  onChecked里面 getModel 又不能判断类型。。
不知道这种多类型情况下，要怎么做选择模式。
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
1. onCheck里面有个回调参数`allChecked`表示是否已全选
2. `getItemType(position)`即可获取类型

**Comment by 287138531** [comment]
测试过allChecked在多类型里面并不准确

**Comment by liangjingkanji** [comment]
文档中有提及如何限制item选择类型: [选择模式](https://liangjingkanji.github.io/BRV/checked/#_4)
