### ISSUE TITLE
请问下，怎么删除嵌套分组中的第三级Item？

### ISSUE THREAD

**Issue by xiaotian317** [liangjingkanji/BRV#313]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
嵌套分组就是多类型item, 根据`layoutPosition`删除即可, 不过注意itemSublist同步删除数据

**Comment by xiaotian317** [comment]
> 



> 嵌套分组就是多类型item, 根据`layoutPosition`删除即可, 不过注意itemSublist同步删除数据

感谢回复，请问删除itemSublist的方式这样可以吗？
一：通过getModel<GroupBasicModel>()获取到第三级的实体
二：通过遍历models删除获取的GroupBasicModel，生成一个新的models
三:  给适配器设置setDifferModels

如果不可以，还请帮忙指导下，谢谢

**Comment by liangjingkanji** [comment]
可以的, 最近我比较忙碌没有及时回复抱歉, 建议使用models而不是过度依赖`setDiffModels()`

请自己优先尝试

**Comment by xiaotian317** [comment]
好的，因为对kotlin才刚刚开始学着使用，所以排查起来有些困难，实在是打扰了，我尝试以下方式删除第三级数据，会出现被删除的第三级item跑到第二级去了，不知道是哪里出问题了
var _data =rv?.bindingAdapter?._data as MutableList<GroupModel>
_data.get(0).jsonSublist.get(0).jsonSublist.removeAt(0)
rv?.models=_data
notifyDataSetChanged()

**Comment by liangjingkanji** [comment]
已添加嵌套分组删除示例代码, 请查看上面显示的提交内容

**Comment by xiaotian317** [comment]
好的，十分感谢
