### ISSUE TITLE
如何刷新itemview里的指定view内容

### ISSUE THREAD

**Issue by Bruce8hou** [liangjingkanji/BRV#314]
## 问题描述
在每个itemview里面有很多view，只是需要根据后端的数据来刷新其中一个view的状态。比如 里面有一个单选控件，在通过setDifferModels 更新数据后只是更新了单选控件的状态。其他控件状态不要全部刷新（如果全部刷新 会闪烁）listAdapterky 可以根据DiffUtil.ItemCallback 和onBindViewHolder 结合 处理。BRV有没有什么办法呢  文档里只是有对比数据方法 但是没有刷新指定控件的说明（目前项目里没有使用DataBinding）
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
[局部刷新](https://liangjingkanji.github.io/BRV/refresh-data/#_4)文档此处不是提过如何根据某个item吗? 

如果不使用DataBinding可能相对比较麻烦, 需要使用`notifyItemChanged(position)`, 该方法会再次触发`onBindViewHolder`

> 这属于RecyclerView使用方法不属于BRV

**Comment by Bruce8hou** [comment]
局部刷新一般会造成整个itemView全部数据重新绑定 如果itewView里面有很多控件会造成闪烁。如果用默认的listAdapter 一般处理是使用DiffUtil.ItemCallback判断差异   override fun onBindViewHolder( holder: RecyclerView.ViewHolder, position: Int, payloads: MutableList<Any> ) 里刷新指定控件状态即可。BRV里面可以自定义itemDifferCallback  但是怎么调用onBindViewHolder呢

**Comment by Bruce8hou** [comment]
已经解决了 在onPayload处理局部刷新就好了 但是在onPayload中如何区分多种item类型呢
