### ISSUE TITLE
缺省对象status()无法创建

### ISSUE THREAD

**Issue by rayzeng0221** [liangjingkanji/BRV#315]
我试用最新版，发现 StatusLayout  只能通过布局声明？不能 通过：
val state = state()  或者  rv.state()   来调用了吗？  
我尝试 使用，但是代码无法提示出来

**Comment by liangjingkanji** [comment]
因为总是有人反复调用`state()`函数反复创建对象然后问为什么出现问题, 所以现在改名叫 `stateCreate()`了

另外我不止一次强调不推荐使用这个函数, 布局就最好在layout声明, 简单而且问题少性能高. 不排除未来我会删除这个函数

**Comment by liangjingkanji** [comment]
文档已经修复更新
