### ISSUE TITLE
列表分段

### ISSUE THREAD

**Issue by Staticzll** [liangjingkanji/BRV#316]
![T83F9~ 5T%%0E $~E38EE](https://user-images.githubusercontent.com/26913056/209898341-282d70e2-fe48-43be-b2a4-dd451ac4aa30.png)
这种怎么做呢？

**Comment by Staticzll** [comment]
可以滑动

**Comment by liangjingkanji** [comment]
这叫多类型列表，不叫列表分段

**Comment by Staticzll** [comment]
用RV可以做吗？

**Comment by liangjingkanji** [comment]
当然可以
你不要思维固化，一个item可以是竖向列表或者横向列表，或者一个轮播图或者一个LinearLayout

**Comment by liangjingkanji** [comment]
你思维固化严重，建议加群接受群友的指导
