### ISSUE TITLE
无法拖拽到另一个item(禁用拖拽状态)的相邻位置

### ISSUE THREAD

**Issue by 258188170** [liangjingkanji/BRV#317]
## 问题描述
demo 中拖拽模块，有一个 item 禁用拖拽后，可拖拽 item无法拖拽到该item相邻位置
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
![Uploading image.png…]()

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by 258188170** [comment]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/28388441/210503927-539e2b21-76a0-4b95-96d7-af258e6743bc.png">

**Comment by liangjingkanji** [comment]
经过我的测试是可以的, 不过需要拖拽到更远的位置, 但是这属于rv自带的功能组件我只是简化实现, 暂时没有更好的办法修复此问题(欢迎pr)


https://user-images.githubusercontent.com/21078112/210795281-8bfb9096-11e6-4b3e-acb4-c50eed755d2f.mp4

**Comment by liangjingkanji** [comment]
该问题已在dev分支被修复
