### ISSUE TITLE
diff和payload同时使用的时候，BindingViewHolder里面还是老数据

### ISSUE THREAD

**Issue by pyj831** [liangjingkanji/BRV#321]
## 问题描述
onPayload执行以后，BindingViewHolder不会调用bind，数据还是老的，这个方法又是internal修饰的，导致列表刷新不了
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
1. 执行`BindingViewHolder.bind`就不是局部更新了而是完全更新了
2. 你可以重写BindingAdapter来实现全部调用

```kotlin
public void onBindViewHolder(@NonNull VH holder, int position,
        @NonNull List<Object> payloads) {
    onBindViewHolder(holder, position);
}
```

**Comment by liangjingkanji** [comment]
如果你使用diffUtils工具去更新, 他会自动调用`notify**`方法

如果你手动调用`notify**()`去局部更新, 那么你更新之前就需要自己先更新`models`数据集合

**Comment by pyj831** [comment]
![image](https://user-images.githubusercontent.com/19635211/211791423-4e23b279-701d-4249-a07d-5fa937050a39.png)
我看这个方法里面更新了_data,然后在自动调用notify的时候，BindingAdapter里的data没有更新

**Comment by liangjingkanji** [comment]
`BindingAdapter里的data`是什么?

**Comment by pyj831** [comment]
打错了BindingViewHolder这个里面的_data

**Comment by pyj831** [comment]
然后我直接调用getModel取到的就是老数据，新数据得自己从adapter里的_data拿

**Comment by liangjingkanji** [comment]
### 以下我说的内容和BRV框架本身设计无关

如果`setDiffModels()`对比数据后触发`局部更新`, 无法做到刷新`BindingViewHolder._data`数据

因为局部刷新本身不会返回model而是返回增量数据(`ItemDifferCallback.getChangePayload()`返回值), 这可以是任何类型的对象

你如果需要更新`BindingViewHolder._data`数据请自己手动完成

例如:

```kotlin
binding.rv.dividerSpace(10.dp).setup {
    addType<GameModel.Data>(R.layout.item_game)
    onPayload {
        val model = getModel<GameModel.Data>()
        model.img = it[0] as String
    }
}
```

如果对`DiffUtils`不够熟悉我也不推荐使用`setDiffModels()`, 这并不是一个万能方法, 甚至很多时候比直接`models = data`麻烦得多

你的项目可能并不需要Diff, 也许你需要的是DataBinding的自动更新View功能

**Comment by pyj831** [comment]
抱歉，因为item里面东西有点多，payload里面我没有传具体的数据，传的是哪些view需要更新，所以才想着修改viewholder里的数据

**Comment by liangjingkanji** [comment]
那你完全不需要增量更新, 直接`notifyItemDataChanged(position)`就行了(第2个参数不要传)

没特别需求别用`setDiffModels()`

**Comment by pyj831** [comment]
之前的老哥在那里用的room+livedata，只要数据有变动，扔一个list出来，不用diff的话，每次都是整体刷新，所以我才想diff+payload

**Comment by liangjingkanji** [comment]
对于这种没有规律的数据集合变更的确正是`setDiffModels`的最佳使用场景
