### ISSUE TITLE
横向列表更新数据后布局刷新问题

### ISSUE THREAD

**Issue by chdown** [liangjingkanji/BRV#322]
## 问题描述

横向列表，重新设置数据后，布局宽度未刷新

复现：
1、将demo简单布局，改为宽度和高度自适应，方向为水平

![image](https://user-images.githubusercontent.com/29998950/212232364-af7b8e4c-0d4e-4af6-a0e5-e072c25437d3.png)

2、点击item后重新设置数据，文本长度比之前少，布局会出现下面的问题，宽度未自适应

![image](https://user-images.githubusercontent.com/29998950/212232540-567a1415-0f50-4ccd-9d9d-9664531567f3.png)

**Comment by liangjingkanji** [comment]
这和BRV有什么关系

**Comment by chdown** [comment]
感谢
