### ISSUE TITLE
Sample编译失败

### ISSUE THREAD

**Issue by TwilightKHQ** [liangjingkanji/BRV#325]
## 问题描述
新拉的代码编译失败，提示`Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://jcenter.bintray.com/com/github/liangjingkanji/Serialize/2.0.0/Serialize-2.0.0.pom'.`
回退1月16号的代码可以正常编译 
`Serialize 2.0` 是不是没有发布出来？ 

### 期望行为
编译正常通过

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.3.89
- Android:
- Gradle: 
- Android Studio: 2022.1.1

**Comment by liangjingkanji** [comment]
的确是这个问题, 现在重新同步即可
