### ISSUE TITLE
还是希望可以添加个开关来设置是否只执行一次动画

### ISSUE THREAD

**Issue by ChawLoo** [liangjingkanji/BRV#327]
## 问题描述
还是希望可以添加个开关来设置是否只执行一次动画，因为全列表数据替换的时候，没有动画很生硬。
### 期望行为
增加一个开关设置是否仅首次执行动画
## 如何复现
-
> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
-
异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:684d9c3c29
- Android:11
- Gradle: 7.6
- Android Studio:Android Studio Electric Eel | **2022.1.1**

**Comment by liangjingkanji** [comment]
什么动画?

**Comment by ChawLoo** [comment]
> 什么动画? 描述问题请描述清晰

列表动画，目前列表动画只执行了一次，翻看了源码 也没有合理的方案去解决，因为判定是通过lastPosition来判定的

**Comment by liangjingkanji** [comment]
你加个flag然后写个demo示例代码吧

**Comment by ChawLoo** [comment]
> 你加个标记变量然后写个demo示例代码吧

fork了以后新增了一个列表动画，增加了一个标识符，写了一个demo

**Comment by liangjingkanji** [comment]
然后你需要发起pr, 如果不会可以查看主页README的贡献代码说明
