### ISSUE TITLE
优化建议：findView缓存

### ISSUE THREAD

**Issue by senselesscn** [liangjingkanji/BRV#328]
提出问题前先拍下东哥马屁，这是我用过最简洁、功能最强大的RecyclerView库，真正做到了开箱即用。
---
是否有必要为BindingViewHolder中的findView函数做一个缓存，这样一来对于复杂的item调用findView时可以提高效率。

**Comment by liangjingkanji** [comment]
findView等于`findViewById`, 不会做缓存. 如果你有这种需求你就应该使用ViewBinding/DataBinding(BRV中使用`getBinding()`), 

你就使用findView了还在纠结性能问题, 就像吃着炸鸡还要喝无糖可乐

**Comment by senselesscn** [comment]
倒也是这么回事

**Comment by liangjingkanji** [comment]
有空可以多推荐下本项目, 方便更多人使用和维护/补全本框架
