### ISSUE TITLE
加载更多完成的时候，滑到底部，再往上滑动出现卡顿，不流畅。

### ISSUE THREAD

**Issue by IdyllicFish** [liangjingkanji/BRV#329]
## 问题描述
滑到底部，再往上滑动出现卡顿，不流畅。
[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)的加载更多是嵌套滑动，并且只能出现在最底部，列表不足一页时还不能跟随到列表 最后一项
### 期望行为
希望和[BaseRecyclerViewAdapterHelper](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)一样适配器实现加载更多的布局
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)是目前应用最广泛扩展性最好的下拉/上拉刷新框架

1. 无法复现卡顿, 请附上sample中卡顿视频, 且参考下SmartRefreshLayout文档
2. 加载更多显示在内容列表上的奇葩需求我非常反感, 且没有多余精力支持这个需求, 你可以自己继承Adapter实现
