### ISSUE TITLE
能支持只启动viewbinding吗？

### ISSUE THREAD

**Issue by lhj1079947827** [liangjingkanji/BRV#33]
如题

**Comment by liangjingkanji** [comment]
DataBinding是目前最优解, 如果使用ViewBinding那会造成大量代码以及架构耦合. 建议使用MVVM

**Comment by liangjingkanji** [comment]
我考虑下发布新的分支

**Comment by liangjingkanji** [comment]
你在onCreate或者onBind中使用以下代码即可创建ViewBinding

```
ItemSimpleBinding.bind(itemView)
```

**Comment by cikichen** [comment]
viewbinding是目前官方重点推荐的方向了

**Comment by liangjingkanji** [comment]
> viewbinding是目前官方重点推荐的方向了

这只是取代kotlin命名空间而已. 两者针对方式不一样, 而且我考虑的从来不是绝对的官方. 而是实际开发体验.
你要是不嫌麻烦也可以自己用 [BRV中使用ViewBinding](https://liangjingkanji.github.io/BRV/view-binding/)
