### ISSUE TITLE
DataBinding数据绑定问题

### ISSUE THREAD

**Issue by lisxian** [liangjingkanji/BRV#330]
可以在item的layout布局中添加position的绑定么,只绑定数据bean不够用,有些时候在layout里面需要position

**Comment by liangjingkanji** [comment]
请阅读sample或者文档, 通过为bean实现不同接口可以获取不同的信息, 例如实现`ItemPosition`接口

- [文档介绍](https://liangjingkanji.github.io/BRV/item/)
