### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Janzjoy** [liangjingkanji/BRV#331]
## 问题描述

为什么会编译报错啊

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

![image](https://user-images.githubusercontent.com/108626070/215771548-5ed79529-96d4-48bf-823e-352b0985ca8a.png)

## 版本
- BRV:1.3.9
- Android:
- Gradle: 7.5
- Android Studio:

**Comment by liangjingkanji** [comment]
看情况你似乎无法下载官方依赖, 解决方法

1. 使用阿里镜像仓库
2. 使用VPN国外代理

**Comment by Janzjoy** [comment]
> 看情况你似乎无法下载官方依赖, 解决方法
> 
> 1. 使用阿里镜像仓库
> 2. 使用VPN国外代理

**Comment by Janzjoy** [comment]
> 看情况你似乎无法下载官方依赖, 解决方法
> 
> 1. 使用阿里镜像仓库
> 2. 使用VPN国外代理

谢谢，正常了
