### ISSUE TITLE
分组的子列表无法使用选择模式

### ISSUE THREAD

**Issue by Clearpole** [liangjingkanji/BRV#332]
会报错父Model不能作为子Model使用

**Comment by liangjingkanji** [comment]
请附上错误信息

**Comment by Clearpole** [comment]
代码在https://github.com/clearpole/test1

**Comment by Clearpole** [comment]
![image](https://user-images.githubusercontent.com/103406935/216294952-fd451962-71d5-46d1-83fc-f8c05c5fe434.png)

**Comment by liangjingkanji** [comment]
让你fork仓库改现有demo, 你新建项目干什么, 你的版本太高我无法运行起来项目

**Comment by Clearpole** [comment]
好吧，我找到了另外一种实现方式，多谢回答

**Comment by liangjingkanji** [comment]
运行了你的demo也根本没有发生异常崩溃

**Comment by Clearpole** [comment]
我这里运行全选会崩溃，不知道为什么

**Comment by liangjingkanji** [comment]
类型转换崩溃异常我认为很好找原因吧, 你自己尝试下debug, 你的人生有的是这种机会

**Comment by Clearpole** [comment]
收到，谨记

**Comment by liangjingkanji** [comment]
光看你代码我怎么都猜不到会类型转换异常, 我认为你不是运行的你的demo

**Comment by Clearpole** [comment]
确实是运行了test1的demo，另外我在除了这个demo的另一个项目也运行了类似的代码，同样是报错转换异常

**Comment by liangjingkanji** [comment]
找到问题了没

**Comment by Clearpole** [comment]
找到了，因为分组列表全选会包括父级 Model 一起选择，而父级Model 和子级 Model 不属于同类型，所以会闪退报错，我的解决方法是加个 try catch

**Comment by liangjingkanji** [comment]
我不明白全选为什么会要求父级和子级同类型?

**Comment by Clearpole** [comment]
是我表达失误
分组列表全选的时候，我想要的效果是只选择子级 Model，但它会连带着父级 Model 一起选择，所以闪退，我解决它的方法是在 onChecked 整体套上 try
`rv.setup｛
addtype〈Model〉｛layout｝
onChecked｛
try｛

...

｝catch（..）｛
// 选择父级 item 的时候 会到这里
｝
｝
｝.models=models（）`

**Comment by liangjingkanji** [comment]
这不算是bug, 你应该判断类型而不是trycatch. 或者使用`setCheckableType`指定可选择类型

**Comment by Clearpole** [comment]
好的，我回去试试

**Comment by liangjingkanji** [comment]
请记住任何多类型列表都存着需要分类型情况处理
