### ISSUE TITLE
使用网格分割线没有适配到RTL布局的问题

### ISSUE THREAD

**Issue by xhh1993** [liangjingkanji/BRV#333]
## 版本
- BRV: 最新版本

分割线左右镜像导致分割线计算错乱

![微信截图_20230203205029](https://user-images.githubusercontent.com/17424639/216607799-55b218fa-bab7-4064-b21d-12cafdc96b81.png)

**Comment by liangjingkanji** [comment]
请fork仓库复现问题

**Comment by liangjingkanji** [comment]
我并不记得分割线有什么左右镜像功能
