### ISSUE TITLE
demo示例首页

### ISSUE THREAD

**Issue by north521** [liangjingkanji/BRV#335]
## 问题描述
demo中的示例首页，在轮播图上来回滑动，会出来抖动、卡顿

**Comment by liangjingkanji** [comment]
无法复现问题, 另外轮播图不是本框架功能, 你可以替换成其他轮播图框架或者反馈给作者

**Comment by north521** [comment]
不是轮播图的问题，在轮播图到最新折扣栏之间，慢速滑动，最新折扣的tab会快速抖动，上来上下不去，大概1秒时间

**Comment by liangjingkanji** [comment]
这个好像是CoordinatorLayout的一个Behavoir的bug, 我目前没空处理demo问题

**Comment by north521** [comment]
好的，谢谢了

**Comment by liangjingkanji** [comment]
在空闲时间有限的情况下我只能优先保证框架的稳定性, 另外本框架是开源社区维护欢迎所有人共同补充修复问题

**Comment by north521** [comment]
好的，刚下个demo体验一下，发现这问题，确定不是框架的问题就好
