### ISSUE TITLE
RV 嵌套 RV，child RV 如何 find 父 RV 条目的位置?

### ISSUE THREAD

**Issue by timmy-gzw** [liangjingkanji/BRV#336]
## 问题描述
当 RV 嵌套 RV，child RV item 点击的时候如何 find 父 RV item 的position? findParentPosition 都是返回-1.

### 期望行为
下面是使用 Demo NestedListFragment 复现的场景. 期望就是希望在 ItemNestedHorizontalRvBinding item 点击的时候, 拿到 NestedListModel 的数据

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

![微信截图_20230212124246](https://user-images.githubusercontent.com/19669214/218293409-8636a9f9-881e-4e2f-8473-048350be8c29.png)

**Comment by liangjingkanji** [comment]
### 鉴于此问题过于简单且和本框架无关系, 建议加群挨骂

1. 此问题和本框架无关系, 你可以直接搜索rv如何解决

2. `findParentPosition` 是`分组`情况下查询上级分组的位置, 和你的需求没关系


<br>

解决方法: 创建一个变量

```kotlin
onCreate {
    val parentPosition = layoutPosition
    getBinding<ItemNestedHorizontalRvBinding>().rv.setup {
        addType<String>(R.layout.item_simple_horizontal)
        R.id.item.onClick {
            Log.i("日志","父rv位置 = $parentPosition")
        }
    }
}
```

**Comment by timmy-gzw** [comment]
哈哈哈哈，这就加群

**Comment by deng81416754** [comment]
![企业微信截图_16975146366382](https://github.com/liangjingkanji/BRV/assets/16043435/c9065c2f-1dd5-4347-81a0-a92115a77d8c)

**Comment by deng81416754** [comment]
`NestedListFragment` rv嵌套rv 遇到了 onCreate 中拿到的 `layoutPosition`  始终为 -1

**Comment by liangjingkanji** [comment]
你和他有异曲同工之妙，你加群问下大家

**Comment by deng81416754** [comment]
好的， 这就去加群挨骂

**Comment by Yumikolab** [comment]
群在哪里？
