### ISSUE TITLE
怎么把轮播图放到RV里面

### ISSUE THREAD

**Issue by north521** [liangjingkanji/BRV#338]
怎么把轮播图放到RV里面？
```kotlin
// 轮播图
binding.banner.setAdapter(HomeBannerAdapter())
.setIndicator(RoundLinesIndicator(requireContext()))
.setOnBannerListener { data, position ->
    toast("点击: 轮播图(${position})")
}.setIntercept(false)
```

**Comment by liangjingkanji** [comment]
和嵌套RV有什么区别，而且我又不确定你用什么Banner

**Comment by liangjingkanji** [comment]
Item里面可以放任何控件，我希望你尝试举一反三

**Comment by liangjingkanji** [comment]
新增演示如何創建嵌套輪播圖: [首頁列表](https://github.com/liangjingkanji/BRV/blob/9d1055d69c3302fdfa28622b87588f2311511a3e/sample/src/main/java/com/drake/brv/sample/ui/fragment/home/HomeListFragment.kt#L38)
