### ISSUE TITLE
页面回退时候, binding.page.onRefresh() 会被执行两次

### ISSUE THREAD

**Issue by fengtech** [liangjingkanji/BRV#34]
非常好的rv库,  使用中碰到一个问题.

当列表也点击到详情页, 再从详情页退回到列表也时候,  binding.page.onRefresh() {} 会被执行两次, 回退时候没有手动执行刷新代码

有时候用 binding.page.refresh()  刷新也会执行两次, 不知道那里出问题了

**Comment by liangjingkanji** [comment]
你确定`refresh/autoRefresh/showLoading`等函数只有调用一次吗? 因为他们调用一次就执行一次`onRefresh `

**Comment by fengtech** [comment]
页面返回时候应该没有机会调用这几个函数，真是奇怪了

**Comment by liangjingkanji** [comment]
你打日志查看, 要肯定. 或者你能在Demo里面复现

**Comment by fengtech** [comment]
var scope: CoroutineScope? = null
        binding.filterEdit.debounce().listen(this) {
            scope?.cancel() // 发起新的请求前取消旧的请求, 避免旧数据覆盖新数据
            scope = scopeNetLife { // 保存旧的请求到一个变量中, scopeNetLife其函数决定网络请求生命周期
                toast("debounce")
                req()
            }
        }
排查出来这这段代码影响, 页面返回时候req()会重复执行

**Comment by liangjingkanji** [comment]
在onCreate函数里面写的吗？页面被销毁了？

**Comment by liangjingkanji** [comment]
你查看Demo [EditDebounceFragment](https://github.com/liangjingkanji/Net/blob/HEAD/sample/src/main/java/com/drake/net/sample/ui/fragment/EditDebounceFragment.kt)是否存在这种情况?
我这边无法复现这个问题
