### ISSUE TITLE
grid(2) 第一个item设置成占满一行点击事件失效

### ISSUE THREAD

**Issue by 13596626382** [liangjingkanji/BRV#341]

**Comment by liangjingkanji** [comment]
我无法复现问题, 请fork仓库复现此问题

**Comment by 13596626382** [comment]
我刚才试了一下，我把点击事件放在onBind{ } 这里，导致第一个item点击事件失效，放到setup{ }里就没问题

**Comment by liangjingkanji** [comment]
你没看demo吗? 点击事件怎么能在onBind里面设置, 任何rv框架都不允许在onBind里面设置点击事件

rv复用会导致覆盖点击事件发生
