### ISSUE TITLE
点击防抖的一个小建议

### ISSUE THREAD

**Issue by maydaynicko** [liangjingkanji/BRV#348]
现在的点击防抖是只针对单个item的，但是实际开发中列表有很多防止多点触控暴力点击的需求，建议可以提供一个判断全局点击时间防抖的click函数

**Comment by liangjingkanji** [comment]
短时间内连续点击多个区域, 虽然说很难但是可以做到, 但是我认为这是用户的自主行为, 并不是"防抖"这种防止超出预期的交互行为

**Comment by maydaynicko** [comment]
其实还是比较好复现的，两根手指同时点击item多次，虽然一般人不会这么干，但是这么干了总是会导致不可预期的错误。导致我每次都要在onBind里findView调用自己的全局防抖点击事件

**Comment by liangjingkanji** [comment]
"两根手指同时点击item多次" 这是用户自己故意为之的行为, 不存在`不可预期`的错误

而且你你就算实现了列表的, 还有其他控件的, 比如标题栏等控件, 所以这不是brv框架需要考虑的问题, 我认为这也不是你需要考虑的问题

另外TOP级别的App也没有实现你说的需求
