### ISSUE TITLE
分组 之后，点击位置好乱啊，刷新的位置也乱了

### ISSUE THREAD

**Issue by pichsy** [liangjingkanji/BRV#349]
分组之后
点击 item的获取的 position和 刷新时 postion该用哪个，望给点建议，
总之，再加上isCheked 特别乱，根本刷新不到想要的位置。modelPostion不对，absPosxxx也不对，淦~~

**Comment by liangjingkanji** [comment]
只有`modelPosition`是本框架提供, 点进去查看源码可以知道只是减去headerCount而已

```kotlin
val modelPosition get() = layoutPosition - headerCount
```

至于用哪个position请你网络搜索下区别, 那是rv内部提供的, 正常情况下使用哪个都没区别

**Comment by liangjingkanji** [comment]
下次希望你描述问题我能看懂并且有代码或者fork仓库复现问题
