### ISSUE TITLE
ViewPager2嵌套SmartRefreshLayout滑动冲突的问题

### ISSUE THREAD

**Issue by wxw-9527** [liangjingkanji/BRV#350]
看项目介绍下拉刷新和上拉加载是集成了SmartRefreshLayout实现的，之前我使用过SmartRefreshLayout框架，发现和ViewPager2会有滑动冲突的问题，请问本项目解决这个问题了么？最近打算更换一款RecyclerView适配器框架，翻issues的时候找到了这个项目

https://github.com/scwang90/SmartRefreshLayout/issues?q=viewpager2

**Comment by liangjingkanji** [comment]
本项目是rv的adapter框架, 并不存在滑动冲突

至于你说的`SmartRefreshLayout`的滑动冲突建议反馈给他的github主页, 或者搜索对应的解决办法, 或者直接使用其他的下拉刷新框架
