### ISSUE TITLE
 缺省页、空布局问题

### ISSUE THREAD

**Issue by w296365959** [liangjingkanji/BRV#351]
## 问题描述
CoordinatorLayout+RecyclerView 的时候，如果RecyclerView内容为空时，想要在RV区域显示缺省布局， 希望在新增一种添加缺省布局的样式；
如果不想要嵌套布局，目前无法快捷的支持这种样式需求

### 期望行为
希望能否在BindingAdapter内 新增一个如addHeader类似的功能 addEmpty用来针对rv设置缺省布局

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by w296365959** [comment]
奇怪，github怎么写1个空字会变成 空间  2个字

**Comment by liangjingkanji** [comment]
1. 在Demo中有这个演示示例`PagePartStateFragment`

2. 其次对于你说的`addEmpty`, 那是否还得考虑`addLoading`和`addError`? 我认为这种多类型Item你可以自己判断数据添加扩展性更好, 只需要在返回数据时处理下即可, 例如判断服务器返回为空你就add一个`Empty`的多类型Item进models即可

我不希望使用BRV会限制住你的思维, 或者只能这么实现, 或者添加一堆根本用不上的api方法

我以前甚至连addHeader和addFooter都不打算添加, 如果你连多类型这个概念都没有理解我认为完全不会RV
