### ISSUE TITLE
使用BRV ItemExpand因为其中的Any的时候无法支持Kotlin Serializable

### ISSUE THREAD

**Issue by Xeldow** [liangjingkanji/BRV#352]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
![image](https://user-images.githubusercontent.com/39125652/230700811-1ae02c88-97e9-4c88-a473-0c49cff1a93c.png)
异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
使用属性访问方法getter形式，不要直接让itemSublist序列化

**Comment by Xeldow** [comment]
![image](https://user-images.githubusercontent.com/39125652/230703547-c3d3350c-4139-45d9-88b4-484f3a422204.png)
我使用了这种方式
![image](https://user-images.githubusercontent.com/39125652/230703569-75f6e396-4e83-4a00-9ca6-0b61c46d4c9c.png)
最终还是报错了
 Caused by: java.lang.ClassCastException: MiaoChildItem cannot be cast to MiaoItem at MiaoItem$$serializer.serialize(MiaoItem.kt:19)

**Comment by liangjingkanji** [comment]
itemSublist仅仅是代理, 你无需给他赋值, 你现在是语法问题导致报错了

请参考[Demo示例代码](https://github.com/liangjingkanji/BRV/blob/6067ed7b10b57c04390e3d7592bd5eee6bd708ea/sample/src/main/java/com/drake/brv/sample/model/Group1Model.kt#L36)

**Comment by liangjingkanji** [comment]
如果依然存在问题请fork仓库复现问题, 可以立即快速解决, 几乎大部分issues都是因为猜测问题导致解决缓慢

**Comment by Xeldow** [comment]
感谢您的耐心解答！我把相关代码弄到demo里面去了，安装后返回桌面触发onPause后就可以复现
https://github.com/Xeldow/KtDemo

**Comment by Xeldow** [comment]
> itemSublist仅仅是代理, 你无需给他赋值, 你现在是语法问题导致报错了
> 
> 请参考[Demo示例代码](https://github.com/liangjingkanji/BRV/blob/6067ed7b10b57c04390e3d7592bd5eee6bd708ea/sample/src/main/java/com/drake/brv/sample/model/Group1Model.kt#L36)

补充一下，这个方法试过了，还是不行。不过今天下午在弄demo的时候发现一个神奇的东西，如果支持操作数据但是不初始化RecycleView相关的操作，就没有问题

**Comment by Xeldow** [comment]
找到原因了···原来BRV会把元数据的List改造，把MiaoChildItem给add到了MutableList<MiaoItem>中导致解析错误，看来不能直接把元数据传入BRV

**Comment by liangjingkanji** [comment]
令我感到震惊的是你竟然没有察觉到是`SaveData.save()`导致的崩溃, 竟然认为BRV导致的崩溃

我看到`onPause`才会崩溃我就想到和BRV没关系了

分组的原理就是动态添加删除models里面的元素, 所以会修改其集合内容, 并且多类型也是添加其元素.... 不然怎么实现多类型列表

**Comment by Xeldow** [comment]
> 令我感到震惊的是你竟然没有察觉到是`SaveData.save()`导致的崩溃
> 
> BRV实现多类型列表当然需要修改`models`数据集合的元素....

🤦🏻‍♀️没想明白多类型列表会改到 models 中的元素。。那其实如何有做数据保存的需求的话就不能用分组的模式了吧（因为会改变元数据）现在我不用分组列表，直接用多类型也达到了效果，可惜就是不能折叠了
