### ISSUE TITLE
关于分组单选的问题

### ISSUE THREAD

**Issue by YQcharlse** [liangjingkanji/BRV#354]
大佬！急需大佬指点！无限极树，只单选的时候在使用
![image](https://user-images.githubusercontent.com/42264736/231744216-1a293dd7-342f-4b07-b984-604dc88d3e53.png)
1.这样的实体是否有问题？
2.怎么确定选择的Position

**Comment by liangjingkanji** [comment]
听不太懂你描述的什么

**Comment by liangjingkanji** [comment]
当然可以一样, 子列表的只是相对被父列表的`itemSublist`包含而已

**Comment by liangjingkanji** [comment]
`position`取决于你想要的相对于父列表的位置(`itemGroupPositon`)还是相对于整个列表的位置`itemPosition`

分组展开.折叠原理就是将父列表的`itemSublist`从`models`里面添加/删除

**Comment by YQcharlse** [comment]
![image](https://user-images.githubusercontent.com/42264736/231958566-260bfd53-75b9-4d92-853f-7a3d5af168eb.png)
这样结构的树要单选，我想取相对于整个列表的位置itemPosition，来做单选。但不知道怎么取

**Comment by liangjingkanji** [comment]
1. 你问的这个问题令我很生气, 你竟然知道实现`ItemExpand`但是你不知道实现`ItemPosition`接口

2. BRV的选择模式默认就是针对的整个列表

请仔细阅读demo和文档, 并且记得更新demo

**Comment by YQcharlse** [comment]
太感谢了东哥，我竟然没有想到实现ItemPosition接口！
