### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by JasonYinH** [liangjingkanji/BRV#355]
/.gradle/caches/transforms-2/files-2.1/5ffd5d9f0983116bf31a47db189f02f0/jetified-BRV-1.3.90-api.jar!/META-INF/brv_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

**Comment by JasonYinH** [comment]
项目里的kotlin_version = '1.6.20'

**Comment by JasonYinH** [comment]
Rebuild报错，项目能运行到手机上。

**Comment by JasonYinH** [comment]
.gradle/caches/transforms-2/files-2.1/5332c22770c2ba04cd8fcebc452fbbb6/jetified-Channel-1.1.5-api.jar!/META-INF/channel_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.4.0.  网上搜了，不过都没用解决问题。

**Comment by liangjingkanji** [comment]
1. 你升级下kotlin版本
2. 你在demo复现

无法复现的问题我无法解决, 而且这个问题应该和框架没关系的

**Comment by liangjingkanji** [comment]
解决了吗? 还有问题你加群咨询下吧, 我的知识面狭窄
