### ISSUE TITLE
折叠时默认保留几项，这种效果需要怎么实现

### ISSUE THREAD

**Issue by BLOODMAGEBURT** [liangjingkanji/BRV#359]
类似京东筛选项的效果
![expand](https://user-images.githubusercontent.com/16059706/234444730-44755f23-412a-43a5-b89d-e69cae588103.jpeg)

我想重写bindingAdapter的flat(）方法默认保留几项，发现flat()不是open的

**Comment by liangjingkanji** [comment]
我认为你选择了个最难的实现方式

你其实可以将折叠状态整个视为一个类型

<img width="593" alt="image" src="https://user-images.githubusercontent.com/21078112/234502440-d2e8a920-551c-423b-91ae-c4d033acfa3e.png">

因为这个无论是展开还是折叠都是一样的, 你没必要把他分开



## 其他

我其实认为这个压根不需要使用BRV的展开/折叠功能, 你直接让Item显示隐藏就好了, 更简单

**Comment by BLOODMAGEBURT** [comment]
东哥一语点醒梦中人，确实可以用显示隐藏来实现
