### ISSUE TITLE
外部布局是 NestScrollView无法正常下拉刷新和加载更多

### ISSUE THREAD

**Issue by rayzeng0221** [liangjingkanji/BRV#360]
这是我的布局，运行后 列表无法正常下拉刷新和加载更多，滑动冲突了：
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            >

            <RelativeLayout
                android:layout_marginEnd="@dimen/qb_px_20"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="@dimen/qb_px_2">

                <RelativeLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content">

                    <FrameLayout
                        android:clickable="true"
                        android:id="@+id/fl_avatar"
                        android:layout_width="@dimen/qb_px_74"
                        android:layout_height="@dimen/qb_px_74"
                        android:layout_centerVertical="true"
                        android:layout_marginRight="@dimen/qb_px_19"
                        android:background="@drawable/avatar_shadow">

                        <ImageView
                            android:id="@+id/iv_avatar"
                            android:layout_width="@dimen/qb_px_72"
                            android:layout_height="@dimen/qb_px_72"
                            android:layout_gravity="center"
                            android:src="@drawable/icon_default_avatar" />
                    </FrameLayout>

                    <TextView
                        android:id="@+id/tv_name"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_toRightOf="@id/fl_avatar"
                        android:fontFamily="@font/ali_heavy"
                        android:text="DR.Mike"
                        android:textColor="@color/color_020A1A"
                        android:textSize="@dimen/qb_px_20" />

                    <RelativeLayout
                        android:layout_width="@dimen/qb_px_192"
                        android:layout_height="@dimen/qb_px_61"
                        android:layout_below="@id/tv_name"
                        android:layout_marginTop="@dimen/qb_px_6"
                        android:layout_toRightOf="@id/fl_avatar">

                        <TextView
                            android:maxLength="75"
                            android:id="@+id/tv_desc"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:lineHeight="@dimen/qb_px_17"
                            android:text="Graduated from the University of Pennsylvania in 1975 with a PhD in dentistry. "
                            android:textColor="@color/color_959596"
                            android:textSize="@dimen/qb_px_12" />

                        <TextView
                            android:id="@+id/tv_more"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_alignParentRight="true"
                            android:layout_alignParentBottom="true"
                            android:layout_marginBottom="@dimen/qb_px_9"
                            android:drawableRight="@drawable/arrow_right_blue"
                            android:drawablePadding="@dimen/qb_px_5"
                            android:text="more"
                            android:textColor="@color/color_0981F6"
                            android:textSize="@dimen/qb_px_12" />
                    </RelativeLayout>

                </RelativeLayout>

            </RelativeLayout>

            <com.drake.brv.PageRefreshLayout
                android:id="@+id/rv_page"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1">

                <androidx.recyclerview.widget.RecyclerView
                    tools:listitem="@layout/item_consultation"
                    android:id="@+id/rv_consultation"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </com.drake.brv.PageRefreshLayout>

        </LinearLayout>

    </androidx.core.widget.NestedScrollView>

</layout>

**Comment by liangjingkanji** [comment]
NestedScrollView和权重一起使用?? NestedScrollView这个和PageRefreshLayout会滑动冲突的

**Comment by liangjingkanji** [comment]
你这个布局设计有脱裤子放屁的嫌疑

**Comment by liangjingkanji** [comment]
长期不回复本问题将被关闭
