### ISSUE TITLE
关闭刷新，只开启加载更多，可能无法加载更多

### ISSUE THREAD

**Issue by LeonShannon** [liangjingkanji/BRV#361]
## 问题描述
不知道算我使用的问题，还是啥问题

外层套一个PageRefreshLayout，在xml中禁止refresh，开启loadmore。

step1. 第一次加载数据，下拉几页后得到没有更多数据，设置
`binding.pageLayout.finish(success = true, hasMore = false)`。
无法加载更多，提示“没有更多数据了”，符合预期

step2. 这时从头拉取数据，成功加载第一页，期望继续下拉加载更多（实际上服务端有数据），设置  
`binding.pageLayout.finish(success = true, hasMore = true)`。
无法加载更多，提示“没有更多数据了”，不符合预期。

暂时解决办法：
在step2的时候，判断是全新拉取数据，调用`binding.pageLayout.refresh()`，然后在`pageLayout`的`onRefresh`回调里面直接`showContent()`,然后在`model=data`，可以加载更多

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.4.1
- Android:全版本
- Gradle: 8.0
- Android Studio: Flamingo | 2022.2.1

**Comment by liangjingkanji** [comment]
能否fork仓库复现问题

**Comment by liangjingkanji** [comment]
你都禁止下拉刷新了你怎么还可以`step2. 这时从头拉取数据，成功加载第一页` ??
