### ISSUE TITLE
能否添加底部/左右悬停

### ISSUE THREAD

**Issue by bwmgd** [liangjingkanji/BRV#362]
## 问题描述
希望可以进行上下左右的悬停，这样可以方便进行表格的功能，就像前端的table一样可以进行滑动和表头单列的固定
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
![Screenshot_2023-05-08-18-19-19-603_com kiwibrowser browser](https://user-images.githubusercontent.com/40416231/236799606-2a72dc35-3bce-47d3-92b1-67eedeacbd7e.jpg)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
功能很不错, 可惜我也不知道如何实现, 本框架的悬停功能并不是我实现的

**Comment by liangjingkanji** [comment]
复杂表格效果还是更推荐由前端实现, 本框架不是表格框架
