### ISSUE TITLE
关于没有更多数据的样式

### ISSUE THREAD

**Issue by NicodeLee** [liangjingkanji/BRV#363]
## 问题描述
关于上拉加载，没有更多的时候，底部的foot能不能直接显示不用上拉才提示呢。
主要是现在设计都这样设计了，而且确实很多屏幕这样没有更多的时候提示也相对友好不用在上拉。

## 截图

这是直接显示的：
![微信截图_20230512163040](https://github.com/liangjingkanji/BRV/assets/3689377/fdd1dd02-c8a5-4c35-9e51-fa105189f26d)

这是demo中上拉才显示
![微信截图_20230512163115](https://github.com/liangjingkanji/BRV/assets/3689377/213741a0-ceb1-4749-94f8-8f7e624301c5)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
本框架扩展的[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout), 你可以使用他的属性`setEnableFooterFollowWhenLoadFinished(true)`启用此功能

以后有任何上拉下拉刷新需求建议你先看看他的文档

**Comment by NicodeLee** [comment]
感谢，api名字改了`  setEnableFooterFollowWhenNoMoreData(true)`  后续上下拉相关的就自己解决了。

**Comment by mlp1995** [comment]
setEnableFooterFollowWhenNoMoreData 这个也没生效啊 老哥你怎么解决的
