### ISSUE TITLE
关于上拉刷新数据加载的问题

### ISSUE THREAD

**Issue by byjjack** [liangjingkanji/BRV#365]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
<img width="674" alt="截屏2023-05-28 18 55 58" src="https://github.com/liangjingkanji/BRV/assets/19277478/d317b670-7fc0-44e8-9cb4-611b58ceb0bc">

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.4.1
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
因为你没有判断是否有下一页就默认认为一直存在下一页

你看下addData函数的最后一个参数

**Comment by liangjingkanji** [comment]
都协程的时代了还`observe`, 你这代码写着不累吗?

**Comment by byjjack** [comment]
嗯嗯好的，哈哈我这刚转kotlin所有的东西都想试试，还有就是你们的Net 很强很棒十分好用

**Comment by liangjingkanji** [comment]
看到框架的本质, 不要盲目模仿模板

不要简单问题复杂化, 最后代码量变多你还看不懂

**Comment by byjjack** [comment]
就是现在遇到一个问题没弄明白，这块我改成了false ，但是上拉正常了，下拉刷新就会多两条数据
<img width="745" alt="截屏2023-05-29 14 48 24" src="https://github.com/liangjingkanji/BRV/assets/19277478/b1be1420-8cdc-473b-b7ee-4974ed9c2874">

**Comment by byjjack** [comment]
好的，我试试判断一下

**Comment by liangjingkanji** [comment]
PageRefreshLayout 默认开启: [不满一页时候关闭上拉加载功能](https://github.com/liangjingkanji/BRV/blob/5269ef245e7f312a0077194611f1c2aded647a3c/brv/src/main/java/com/drake/brv/PageRefreshLayout.kt#LL455C22-L455C22)

**Comment by byjjack** [comment]
已经添加了 但是不管用，下拉刷新还是会增加数据 ，是我设置的不对吗
<img width="742" alt="截屏2023-05-29 15 53 31" src="https://github.com/liangjingkanji/BRV/assets/19277478/c32d9a03-fe20-47ce-8e62-c854bbb9ed82">

**Comment by liangjingkanji** [comment]
原来你说的下拉刷新增加数据? 

那我建议你不要使用addData方法, 因为你使用的ViewModel来处理数据所以, 具体原因我也不清楚除非你能fork仓库复现问题

你自己获取数据自己给rv列表赋值吧, 自己去判断是否有下一页

**Comment by NicodeLee** [comment]
我这边也刚写完，没什么问题，用的跟lz差不多的实现，有数据建议打印一下请求跟返回数据，看后台的页码索引是否正确返回。
```
       onRefresh {
                mViewModel.getOrder(index - 1)?.observe(this@OrderActivity) {
                    val totalCount = it.total
//                    XLog.e("总数:" + totalCount + ",总页数：" + totalPage(totalCount))
                    if (it.list.isEmpty()) {
                        showEmpty()
                    } else {
                        addData(it.list) {
                            index < (totalPage(totalCount))
                        }
                    }
                }
            }.autoRefresh()
```

**Comment by liangjingkanji** [comment]
> 我这边也刚写完，没什么问题，用的跟lz差不多的实现，有数据建议打印一下请求跟返回数据，看后台的页码索引是否正确返回。
> 
> ```
>        onRefresh {
>                 mViewModel.getOrder(index - 1)?.observe(this@OrderActivity) {
>                     val totalCount = it.total
> //                    XLog.e("总数:" + totalCount + ",总页数：" + totalPage(totalCount))
>                     if (it.list.isEmpty()) {
>                         showEmpty()
>                     } else {
>                         addData(it.list) {
>                             index < (totalPage(totalCount))
>                         }
>                     }
>                 }
>             }.autoRefresh()
> ```

`addData`里面有默认判断list是否为空然后showEmpty, 你可以不用自己判断

**Comment by byjjack** [comment]
嗯嗯我了解了，我这块后台没有返回那个页数，我debug一下看看问题出在哪里，

**Comment by NicodeLee** [comment]
> > 我这边也刚写完，没什么问题，用的跟lz差不多的实现，有数据建议打印一下请求跟返回数据，看后台的页码索引是否正确返回。
> > ```
> >        onRefresh {
> >                 mViewModel.getOrder(index - 1)?.observe(this@OrderActivity) {
> >                     val totalCount = it.total
> > //                    XLog.e("总数:" + totalCount + ",总页数：" + totalPage(totalCount))
> >                     if (it.list.isEmpty()) {
> >                         showEmpty()
> >                     } else {
> >                         addData(it.list) {
> >                             index < (totalPage(totalCount))
> >                         }
> >                     }
> >                 }
> >             }.autoRefresh()
> > ```
> 
> `addData`里面有默认判断list是否为空然后showEmpty, 你可以不用自己判断

试了可行，更简洁了，又省几行代码，简单的列表一个类才几十行代码

**Comment by liangjingkanji** [comment]
我还是更推荐直接使用Net直接一行代码立刻请求返回结果更好, 你这种回调形式太麻烦, 协程时代异步任务应该写同步代码

**Comment by byjjack** [comment]
修改代码不使用viewmodel 就没有问题了，之前下拉刷新多数据问题没有找到问题原因，介意net和brv 配合使用，不要介意使用viewmodel会出问题
<img width="757" alt="截屏2023-05-29 17 03 48" src="https://github.com/liangjingkanji/BRV/assets/19277478/d3e7867b-d0b1-432a-9f95-77cb03913399">

**Comment by liangjingkanji** [comment]
我这么说吧, 你认真看下demo或者文档, onRefresh里面应该使用的是`scope`, 这样才会跟随PageRefreshLayout生命周期

另外我认为问题不是ViewModel的问题只是不兼容, 你可以自己排查下具体代码位置, addData只是给出的一个参考, 你完全可以自己实现一个addData函数

**Comment by byjjack** [comment]
嗯嗯好的
