### ISSUE TITLE
关于缺省页展示问题

### ISSUE THREAD

**Issue by byjjack** [liangjingkanji/BRV#367]
## 问题描述 
我的使用BRV 和 Net配合使用的 在关于缺省页展示是根据后台返回的错误码来展示的但现在展示错误

### 期望行为 
希望展示能根据错误码来展示

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
![7500cd6cca301c4bf55ec18fb450d37](https://github.com/liangjingkanji/BRV/assets/19277478/e6764618-025c-42b8-8169-e7814165c241)
![c77072a0cc0a6e016593c591cd9714b](https://github.com/liangjingkanji/BRV/assets/19277478/e350f81e-9519-43d8-9446-9940474bc1d7)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.4.1
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
看下你设置缺省页的地方，你应该设置错误的布局了

**Comment by byjjack** [comment]
布局都检查过了，没有设置错误，

**Comment by liangjingkanji** [comment]
我的意思是你可能 `emptyLayout = 你现在显示的错误布局`, 你截图看下吧

或者你能在本仓库的demo中复现此问题, 否则我无法解决

**Comment by byjjack** [comment]
嗯嗯好的

**Comment by liangjingkanji** [comment]
长时间没有回复本问题关闭
