### ISSUE TITLE
拖拽过程中我想合并两个Item这个需要怎么做

### ISSUE THREAD

**Issue by artillerymans** [liangjingkanji/BRV#368]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
本框架并没有简化所谓合并的操作(你需要自己实现)

合并和删除只是动画不同, 请自己实现这个效果
