### ISSUE TITLE
瀑布流两列，当数量为 奇数个会出现靠右的情况

### ISSUE THREAD

**Issue by qmkkxtxby** [liangjingkanji/BRV#371]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
请fork仓库复现问题, 并提供截图

**Comment by liangjingkanji** [comment]
这不是bug

瀑布流布局中居左还是居右取决于上一行的item是左边短还是右边短, 不存在一定居左

**Comment by liangjingkanji** [comment]
<img width="227" alt="image" src="https://github.com/liangjingkanji/BRV/assets/21078112/41b50489-4c0e-405c-849a-bc809951731b"> 
<img width="243" alt="image" src="https://github.com/liangjingkanji/BRV/assets/21078112/3eec681d-0e7e-414e-9aff-db24e0ef5ea8">


你觉得像这种按照你的想法一直居左排列合适吗?

**Comment by qmkkxtxby** [comment]
但你看代码，我高度都是一样的，划线部分的item明显高度不对

**Comment by liangjingkanji** [comment]
高度都是一致的你用什么瀑布流布局？

**Comment by Youngkingtom** [comment]
高度都是一致的你用什么瀑布流布局？

**Comment by qmkkxtxby** [comment]
我这边是多布局瀑布流，后台可能只有一页数据，刚好数据又是同一种类型，就会出现虽然是瀑布流但是所有item高度都是一致的情况。最后一个会出现在最右边，并且上面间距没了。
 mBind.rv.staggered(spanCount = 2)
            .divider { setDivider(12,dp = true) }
           .setup {
                addType<GuessLikeMenuBean> {
                    when (itemType) {
                        1 -> R.layout.adapter_like_menu
                        2 -> R.layout.adapter_like_more
                        else -> R.layout.adapter_like_package
                    }
                }
            }
![123](https://github.com/liangjingkanji/BRV/assets/32348330/f32898db-afd5-4057-bf32-252519f9b2ab)

**Comment by qmkkxtxby** [comment]
我把 divider { setDivider(12,dp = true) }去掉，直接在布局里面设置边距margin6就能正确显示居左，且边距正确

**Comment by liangjingkanji** [comment]
请你fork demo复现下这个问题

**Comment by qmkkxtxby** [comment]
第一次的图片就是fork demo的，我只是改成了固定高度就出现了倒数第二个的高度不对的问题，应该解决了高度问题就没问题了。
![image](https://github.com/liangjingkanji/BRV/assets/32348330/d43c95d6-7383-4dde-8290-40df43ab4222)

**Comment by liangjingkanji** [comment]
可是第一张图片没有任何问题
如果你还不能fork仓库复现问题提供代码给我，我将关闭此issues

**Comment by qmkkxtxby** [comment]
现在不管奇数情况靠右的问题，fork代码瀑布流高度设置一样的确没有出现靠右的情况，但我这边的确有，但fork代码之后瀑布流高度一致情况出现了第9个的高度高于其他item高度，代码和图片如下，可以明显看出第9个的高度是不对的
class StaggeredDividerFragment: BaseDividerFragment<FragmentStaggeredDividerBinding>(R.layout.fragment_staggered_divider) {

    override fun initView() {
        binding.rv.staggered(2).divider {
            setDrawable(R.drawable.divider_horizontal)
        }.setup {
            addType<DividerModel>(R.layout.item_divider_vertical)
            onBind {
                // 设置动态高度
                val layoutParams = itemView.layoutParams
                layoutParams.height = getModel<DividerModel>().height
                itemView.layoutParams = layoutParams
            }
        }.models = getData()
    }

    private fun getData(): List<Any> {
        val data = mutableListOf<Any>()
        // 生成动态宽高
        for (i in 0..10) {
            data.add(DividerModel(400))
        }
        return data
    }

    override fun initData() {
    }
}
https://user-images.githubusercontent.com/32348330/246800672-60a29454-63a7-4bc9-beeb-18ff14af7ed0.jpeg

**Comment by liangjingkanji** [comment]
我再次说明本问题无法复现

实在不行你自定义分割线吧, 不要使用BRV提供的简化函数了(只是提供不代表一定要使用)

<img width="350" alt="image" src="https://github.com/liangjingkanji/BRV/assets/21078112/53d10779-b4ab-4f41-a3bc-bb90c9fea0cd">

**Comment by SNTopdsddsad** [comment]
@liangjingkanji
