### ISSUE TITLE
无法复现Edge.computeEdge可能发生的NPE

### ISSUE THREAD

**Issue by LeonShannon** [liangjingkanji/BRV#372]
## 问题描述
用了StaggeredGridLayoutManager的地方就是这里。但是没有复现出来

<img width="559" alt="image" src="https://github.com/liangjingkanji/BRV/assets/24221796/46057b2d-eeee-4e9a-99cc-7ff5e72f71e0">
<img width="750" alt="image" src="https://github.com/liangjingkanji/BRV/assets/24221796/185e6d94-e5dd-4d11-8375-4389e2dbf23b">

## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
<img width="1496" alt="image" src="https://github.com/liangjingkanji/BRV/assets/24221796/efe57309-92f1-4bb3-8f88-8108270ced7c">

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.4.1
- Android:任何版本都存在
- Gradle: 8.1.1
- Android Studio:Android Studio Hedgehog | 2023.1.1 Canary 9

**Comment by liangjingkanji** [comment]
`staggered()`这个函数本身就是设置layoutManager, 但是我看你又再`layoutManager`设置一遍, 我不太能理解你写的代码含义

查看异常本身我认为发生在`com/drake/brv/DefaultDecoration.kt:727`

```kotlin
when (layoutManager) {
    is StaggeredGridLayoutManager -> {
        val spanCount = layoutManager.spanCount
        val spanIndex = (layoutManager.findViewByPosition(position)?.layoutParams
                as StaggeredGridLayoutManager.LayoutParams).spanIndex + 1
```

我认为这个异常和你自己定义的LayoutManager可能存在一定关系

**Comment by liangjingkanji** [comment]
你提供不了fork仓库复现的代码, 所以我只能猜测, 上面就是我的猜测

**Comment by liangjingkanji** [comment]
我认为问题发生在
```kotlin
layoutManager.findViewByPosition(position) 返回null导致的NPE
```

**Comment by liangjingkanji** [comment]
试了下如果没问题给个反馈吧

**Comment by liangjingkanji** [comment]
我发布的新版本1.4.2上线了只是减少了部分crash? 依旧存在这个问题是吗? 

> .... 我先把这个这方法加上，然后再做一下空数据，不添加 header 的处理，线上跑跑看看还有问题没

还是说你之前提到的那种解决方式?

**Comment by liangjingkanji** [comment]
我也是PS5玩家有用你们App, 这个开源项目的"首页"示例就是抄的你们产品, 是我抄的太潦草吗? 你都没看出来

欢迎你参与这个项目让brv/sample更完善

**Comment by liangjingkanji** [comment]
因为感觉你们app做的很好很适合演示, 我写的也没你们好, 有空欢迎你优化下

本问题我先关闭了, 如果线上新版本还存在该问题会reopen继续跟踪问题

**Comment by liangjingkanji** [comment]
问题有解决吗?
