### ISSUE TITLE
上拉加载更多没有反映，向上拖动布局都不动

### ISSUE THREAD

**Issue by Mr-gao-Github** [liangjingkanji/BRV#375]
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图
![d52ee5a306e7617ccfd1f11dc5711a2](https://github.com/liangjingkanji/BRV/assets/33086954/3839573e-0825-4296-b15a-af014ff33e8a)

**Comment by Mr-gao-Github** [comment]
更新最新版本可以了

**Comment by liangjingkanji** [comment]
可能和以前的版本配置默认情况下是没有更多页有关
