### ISSUE TITLE
  请问，怎么实现列表只加载指定的几个，点击按钮后再全部加载呢

### ISSUE THREAD

**Issue by ximenchuipaopao** [liangjingkanji/BRV#376]
## 问题描述
  请问，怎么实现列表只加载指定的几个，点击按钮后再全部加载呢
### 期望行为
  请问，怎么实现列表只加载指定的几个，点击按钮后再全部加载呢
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
加载几个数量的列表都无法控制吗? 

这个问题过于复杂建议你加群问下其他人, 我这边无法解答
