### ISSUE TITLE
关于骨架屏使用内存泄露的问题

### ISSUE THREAD

**Issue by greadking** [liangjingkanji/BRV#378]
## 如何复现
见下图

## 版本
- BRV:1.4.1
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
你有发现内存泄漏位置吗? LeastAnimationStateChangedHandler不属于框架本身内容, 你可以先尝试自己修复此问题然后发起PR

**Comment by liangjingkanji** [comment]
项目现在新增内存泄露依赖, 开启后并不会捕捉到内存泄露, 可能是之前Engine库导致的Fragment内存泄漏问题吧
