### ISSUE TITLE
 onBing 方法中怎样能获取到 oncreate 定义的字段

### ISSUE THREAD

**Issue by 530l** [liangjingkanji/BRV#379]
## 问题描述
 
onCreate（） 是创建 onCreateViewHolder 的回调，我想定义一些字段是根据 hodel 创建的声明周期走的，我应该定义在 oncreate 里面，然后自己缓存起来吗，再 onBind（）方法关联起来，还是怎样？ onBing 方法中怎样能获取到 oncreate 定义的字段

     onCreate {
                   if (itemViewType == R.layout.xxxxx_header){}
                   if (itemViewType == R.layout.xxxxx_info){
                          var gsyVideoOptionBuilder = GSYVideoOptionBuilder()
                   }
            }
   onBind {

               gsyVideoOptionBuilder.setXXXXXXX
    }

## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.4.2
- Android: 13
- Gradle: 7.0
- Android Studio: Android Studio Bumblebee | 2021.1.1 Patch 2

**Comment by liangjingkanji** [comment]
1. 使用ViewHolder的`itemView.setTag`去读写对象
2. onBind里面去判断`itemViewType`

不过我认为可以给BindViewHodler新增一个`tag`变量来存储

**Comment by linyingfa** [comment]
这个可以，给BindViewHodler新增一个tag变量来存储，有空增加下

**Comment by liangjingkanji** [comment]
已完成
