### ISSUE TITLE
尝试使用1.3.31版本时，无法正确加载项目

### ISSUE THREAD

**Issue by PengShaoLei1997** [liangjingkanji/BRV#38]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.scwang.smart:refresh-layout-kernel:2.0.3.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.scwang.smart:refresh-header-material:2.0.1.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.scwang.smart:refresh-header-material:2.0.1.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.scwang.smart:refresh-header-material:2.0.1.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
Show Details
Affected Modules: app

**Comment by PengShaoLei1997** [comment]
项目中未使用JCenter()仓库，是否存在影响？

**Comment by liangjingkanji** [comment]
smartRefreshLayout在jcenter, 处于很多考虑我都不建议你删除jcenter, 这意味着你放弃大量的第三方库

**Comment by PengShaoLei1997** [comment]
感谢您的回复！刚刚去看了下smartRefreshLayout库，正是因为依赖于JCenter导致了我项目加载失败。

**Comment by liangjingkanji** [comment]
不推荐你删除jcenter依赖, 因为很多第三方库无法保证间接或者直接是否存在依赖
jcenter官方承诺永久可访问下载, 你无需担心未来项目无法编译
