### ISSUE TITLE
瀑布流列表的Item高度会被分割线影响

### ISSUE THREAD

**Issue by TwilightKHQ** [liangjingkanji/BRV#380]
## 问题描述
瀑布流列表的Item高度会被分割线影响
将item_divider_vertical.xml的布局高度设为300px，添加分割线和不添加分割线，Item的高度不一样

## 期望结果
无论是否添加分割线都不影响Item的高度

## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

Forked地址：https://github.com/TwilightKHQ/BRV
## 截图
![uTools_1689565998271](https://github.com/liangjingkanji/BRV/assets/25874642/bc8463ea-b263-4289-806f-0eaf9099c9c7)
![uTools_1689565931534](https://github.com/liangjingkanji/BRV/assets/25874642/4cb81533-2f27-4cad-9539-f9153d4750d6)
![uTools_1689566236939](https://github.com/liangjingkanji/BRV/assets/25874642/a7143ae7-5015-46ae-ac77-05b714b3be0b)

## 版本
- BRV:1.4.2
- Android:13
- Gradle: 
- Android Studio:

**Comment by TwilightKHQ** [comment]
应该和 #371 后面描述的问题有关

**Comment by liangjingkanji** [comment]
这是RecyclerView的问题, 我无法修复此问题

BRV使用官方的方式实现分隔物, 仅能缩小item无法扩大, 见`DefaultDecoration#getItemOffsets`的方法中设置偏移

如果你能解决此问题欢迎pr

**Comment by liangjingkanji** [comment]
BRV提供一个计算item是否位于列表边缘的工具类(默认的DefaultItemDecoration也是使用这个工具类实现的)

该工具可以方便判断item内部的视图是否显示从而实现"非分隔物方式"的分割线实现, 可以不占据Item内部空间

或者自己实现ItemDecoration接口
