### ISSUE TITLE
有木有进行性能优化的考量哇

### ISSUE THREAD

**Issue by zs1973** [liangjingkanji/BRV#381]
如题，和BaseRecycleViewAdapterHelper相比，似乎那个性能上更好一些。

**Comment by liangjingkanji** [comment]
本项目文档提供一些滑动卡顿方面的参考: [滑动卡顿](https://liangjingkanji.github.io/BRV/performance/)

**Comment by shenhuxi92** [comment]
RecyclerView的性能优化不是你自己处理的么，BRVAH什么时候帮你做了性能优化了啊？

**Comment by zs1973** [comment]
> RecyclerView的性能优化不是你自己处理的么，BRVAH什么时候帮你做了性能优化了啊？

你说的对
