### ISSUE TITLE
有没有交流群？

### ISSUE THREAD

**Issue by guowenlong123** [liangjingkanji/BRV#382]
## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
![qrcode_1690426000111](https://github.com/liangjingkanji/BRV/assets/21078112/1119d99d-cfb9-4316-8aee-d5865fd8c8e1)

**Comment by TwilightKHQ** [comment]
？？ 早上才进群，下午就炸了

**Comment by liangjingkanji** [comment]
刷新网页二维码会变更

**Comment by guowenlong123** [comment]
群封了

**Comment by liangjingkanji** [comment]
群消失以后请刷新网页, REAMDE和二维码都会更新的
