### ISSUE TITLE
代码索引

### ISSUE THREAD

**Issue by yzjdev** [liangjingkanji/BRV#384]
建议在使用文档中添加代码索引， 这样方便查阅文档所对应的代码片段

**Comment by liangjingkanji** [comment]
开发文档和代码并不完全是一一对应关系, 在关键位置我有提供超链接跳转到源码位置. 我不清楚你是想要跳转到框架源码还是sample示例代码位置

> 文档旨在让开发者理解, 代码更在于让开发者实战和贡献反哺本项目
