### ISSUE TITLE
好像没有Node，树级

### ISSUE THREAD

**Issue by lishangwl** [liangjingkanji/BRV#387]
## 是否可以参与实现
> 由于本项目参与者的技术及精力有限无法满足大部分开发者的需求, 欢迎开发者参与贡献

**Comment by liangjingkanji** [comment]
`Node = 无限分组`

让我想到有人问我为什么只有悬停没有粘性头部

**Comment by lishangwl** [comment]
> `Node = 无限分组`
> 
> 让我想到有人问我为什么只有悬停没有粘性头部

你已经在qq群里说过我了

**Comment by liangjingkanji** [comment]
> > `Node = 无限分组`
> > 让我想到有人问我为什么只有悬停没有粘性头部
> 
> 你已经在qq群里说过我了

群里的不是我

**Comment by liangjingkanji** [comment]
[分组/树级](https://liangjingkanji.github.io/BRV/group.html)

为了你以后分组叫 `书记`
