### ISSUE TITLE
选择模式

### ISSUE THREAD

**Issue by 530l** [liangjingkanji/BRV#389]
## 问题描述
BRV 快速勾选 checkbox 会出现标题已选的数量 和 checkbox 的选择状态对不上，
## 如何复现
demo 连续快速点击 checkbox
> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.5.2
- Android:13
- Gradle: 7.2
- Android Studio:Android Studio Giraffe | 2022.3.1 Patch 1

**Comment by liangjingkanji** [comment]
能录屏吗?

**Comment by 530l** [comment]
https://github.com/liangjingkanji/BRV/assets/14791260/6e5b7747-62fc-4d8e-9375-c220981173f2

**Comment by liangjingkanji** [comment]
这本质上是CheckBox的问题, 因为该按钮并不是响应的点击事件

1. 替换为其他控件, 例如ImageView或者`FilterCheckBox`
2. onClick替换为`onFastClick`, 改为快速响应点击事件

**Comment by 530l** [comment]
ok

**Comment by liangjingkanji** [comment]
sample我有更新
