### ISSUE TITLE
真是一个优秀的RV框架，不过我想问当前框架是否支持嵌套Group接合局部空布局使用？即当一个组中的元素为0的时候就显示空布局？

### ISSUE THREAD

**Issue by XXQAQ** [liangjingkanji/BRV#391]
如题

**Comment by liangjingkanji** [comment]
定义一个类型叫"空布局", 如果返回0则添加该类型

**Comment by XXQAQ** [comment]
> 定义一个类型叫"空布局", 如果返回0则添加该类型
> 
> 你思维灵活点吧

不是的，这种做法让业务层关心了当数据为0时的处理，不能像PagePartStateFragment一样做到业务层无感知的效果

**Comment by liangjingkanji** [comment]
你不自己判断框架怎么知道到底什么数据为零, 分组在rv中本来就属于多类型实现

**Comment by liangjingkanji** [comment]
经过我的评估是自己判断数据(直接判断子分组是否为empty, 为empty自动添加一个对象即可)比框架封装更简单

**Comment by XXQAQ** [comment]
> 经过我的评估是自己判断数据(直接判断子分组是否为empty, 为empty自动添加一个对象即可)比框架封装更简单
> 
> 如果你有更好的解决方案欢迎pr

这个做法最大的问题是，业务层每次插入数据前需要对这个List做判断，如果其中的元素为EmptyModel，那要先删除该元素，再添加DataModel。业务层关心了空到非空的集合转换，这点从设计上不是很合理

**Comment by liangjingkanji** [comment]
前端理所应当处理业务数据, 我没明白有什么不合理的, 我们在model层一直会转化数据, 数据控制UI展示

还是说你有更好的处理办法吗?

**Comment by XXQAQ** [comment]
我是这样想的：对外部而言，只要为Adapter设置了对应的空布局以后，那么在Adapter的List空掉以后，不需要对List做任何处理就自然展示空布局，所有业务逻辑操作由Adapter内部自己消化。当然像你刚刚说处理是Adapter对内部的处理，只是可能需要把空布局视作一种特殊item，由框架内部根据情况转换数据item和特殊item
&nbsp;


120363542
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月14日(星期四) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liangjingkanji/BRV] 真是一个优秀的RV框架，不过我想问当前框架是否支持嵌套Group接合局部空布局使用？即当一个组中的元素为0的时候就显示空布局？ (Issue #391)





 
前端理所应当处理业务数据, 我没明白有什么不合理的, 我们在model层一直会转化数据, 数据控制UI展示
 
还是说你有更好的处理办法吗?

**Comment by liangjingkanji** [comment]
业务逻辑我是让你在model中处理好直接set给adapter, 没让你在adapter中处理业务(而且brv推荐的是无adapter写法)

建议你遵守mvvm架构设计, model处理业务逻辑数据

**Comment by XXQAQ** [comment]
我就是用的mvvm，你还是没明白，我的问题点于，Adapter的空状态始终要由外部来维护，而不是自身维护

**Comment by liangjingkanji** [comment]
本框架不支持你要的写法, 除非你能提供更好的代码pr, 如果你想讨论数据到底应该谁处理可以加群和更多人讨论

你说的是局部list不是整个list, 根本无法感知你到底什么地方空, 你想的太简单了, 而且也并不是所有需求都需要空

我工作和维护时间需要平衡, 无法在这里继续和你讨论这个问题

**Comment by liangjingkanji** [comment]
如果有修改方案可以提一个"提议"issues然后进行pr

**Comment by liangjingkanji** [comment]
> 我就是用的mvvm，你还是没明白，我的问题点于，Adapter的空状态始终要由外部来维护，而不是自身维护

你的问题我是明白的, `PageRefreshLayout.addData`方法就是你想要的方式, 但是那不是局部

如果非要说的话 局部我认为没必要实现, 并且我也不知道如何实现, 所以我一直说你有更好的实现方式可以提出来, 而不是讨论合理与否

**Comment by liangjingkanji** [comment]
你现在讨论的问题是属于rv的而不是brv的
