### ISSUE TITLE
Jitpack 上 StateLayout 1.4.1 消失，导致BRV 1.5.1 之前的版本不能同步

### ISSUE THREAD

**Issue by realOxy** [liangjingkanji/BRV#392]

**Comment by realOxy** [comment]
而且我建议作者该接口把旧的接口@Deprecated了而不是直接改了（😭

**Comment by liangjingkanji** [comment]
我看了下没有消失,  我也不知道什么旧的接口

**Comment by realOxy** [comment]
> 我看了下没有消失, 我也不知道什么旧的接口

https://jitpack.io/com/github/liangjingkanji/StateLayout/1.4.1/

这里只剩个log了

**Comment by liangjingkanji** [comment]
https://jitpack.io/com/github/liangjingkanji/StateLayout/1.4.1/build.log

**Comment by liangjingkanji** [comment]
感觉是jitpack出现了问题, 我尽快迁移mavenCentral

**Comment by realOxy** [comment]
好的

**Comment by liangjingkanji** [comment]
被冻结了我无法重新生成, 建议你升级新版本吧, 旧版本都是有bug的

我尽快迁移到mavenContral吧

**Comment by wzJun1** [comment]
我还以为我出问题了呢，老项目直接摆烂了，麻了。
