### ISSUE TITLE
Demo内置的Net3.5.8版本已经找不到

### ISSUE THREAD

**Issue by SinceJulyzzZ** [liangjingkanji/BRV#394]
## 问题描述
Demo内置的Net3.5.8版本已经找不到了，建议升级一下，没有缓存可能跑不通了。
## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图
![企业微信截图_16968163886642](https://github.com/liangjingkanji/BRV/assets/64911679/edd39524-29cd-484f-9f18-73219a890007)
![企业微信截图_1696816437163](https://github.com/liangjingkanji/BRV/assets/64911679/a578587b-fb95-43ed-b4d2-48a7f6755ef1)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:master
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
jitpack仓库一些低版本的依赖失效了

**Comment by SinceJulyzzZ** [comment]
thanks
