### ISSUE TITLE
请教一下上拉加载中的状态变更和列表数据先后顺序的问题

### ISSUE THREAD

**Issue by SinceJulyzzZ** [liangjingkanji/BRV#395]
## 问题描述
在BindingAdpter中 的addModels方法
![image](https://github.com/liangjingkanji/BRV/assets/64911679/e808fbb2-6275-45ec-b0ed-6c8074fa0fd5)
此处的更新列表 明明是优先于PageRefreshLayout中finish方法的 finishLoadMore
![image](https://github.com/liangjingkanji/BRV/assets/64911679/de148c12-ed80-4d2b-bee7-523d3b1b7081)

![image](https://github.com/liangjingkanji/BRV/assets/64911679/9be8487e-8f26-4830-bd48-d77837affa1f)

但是结果从UI展示上来看 上拉加载中 却是先展示的加载完成再更新的列表数据，请问为什么会这样呢？  业务逻辑上来说应该是优先加载列表吧？

## 如何复现
Demo
> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
有录屏吗?

**Comment by liangjingkanji** [comment]
"增加数据" 后不代表就立即展示UI了, 因为只是通知RV更新UI而已

**Comment by SinceJulyzzZ** [comment]
https://github.com/scwang90/SmartRefreshLayout/issues/182   类似于这个问题。但是我并没有找到如何设置先后顺序。

**Comment by SinceJulyzzZ** [comment]
https://github.com/liangjingkanji/BRV/assets/64911679/64904c4a-24f2-4290-97c6-762414a551db

可以看到下面的加载状态  先是显示的"加载完成"  ，再有的列表UI更新。 感觉这样顺序不太正确

**Comment by liangjingkanji** [comment]
实际上已经加载数据了, 被挡住了而已
