### ISSUE TITLE
使用ViewBinding 在选择模式下的问题以及复现步骤

### ISSUE THREAD

**Issue by deng81416754** [liangjingkanji/BRV#398]
## 问题描述
测试单选模式的 使用ViewBinding，手动绑定数据 ，onChecked 中调用notifyChange ，以下方法 onBind、onPayload 不会回调
具体代码在 fork仓库，的`CheckModeFragment`   和 `fragment_check_mode.xml` 
## 期望结果
刷新页面数据
## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
https://github.com/deng81416754/BRV
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

https://github.com/liangjingkanji/BRV/assets/16043435/232e5eff-cbdf-410e-ab78-8e4bc92e412c

## 截图
![image](https://github.com/liangjingkanji/BRV/assets/16043435/4898813a-9d50-4608-a694-bf4175d6e4bb)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.5.3
- Android:6.0 or  13
- Gradle: gradle-7.2
- Android Studio:Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 20, 2023

**Comment by GuangNian10000** [comment]
？解决了？我现在有这个问题
