### ISSUE TITLE
PageRefreshLayout的setnomoredata出现的底部文字不对

### ISSUE THREAD

**Issue by lwz339** [liangjingkanji/BRV#399]
东哥，求助一个问题
`if(binding.homeRecyclerView.adapter!!.itemCount>=homeViewModel.total){
	binding.page.setNoMoreData(true)
}`我在fragment重建的时候判断是否已经加载完成所有数据，然后设置不再加载，为什么这时候再次上拉，底部显示的不是no more data而是pull up to load more？而且只是显示文字有问题，不会触发onloadmore。其他正常情况的加载完成会显示no more data，是我设置有问题吗？

**Comment by liangjingkanji** [comment]
怎么不fork仓库复现问题

**Comment by liangjingkanji** [comment]
已在[最新版本](https://github.com/liangjingkanji/BRV/releases/latest)修复
