### ISSUE TITLE
侧滑只能默认删除吗？可以类似与qq列表侧滑那样，出现自定义的图标或文字吗？

### ISSUE THREAD

**Issue by leifengwl** [liangjingkanji/BRV#4]

**Comment by liangjingkanji** [comment]
暂时不支持该功能, 并且这个我认为应该不属于RV的责任

推荐使用这个库 [SwipeToActionLayout](https://github.com/st235/SwipeToActionLayout)来配合

另外这是属于iOS的系统交互效果, 我不建议Android去实现, 和标签栏切换可能产生事件冲突;  建议使用Android用户常使用的长按弹出菜单
