### ISSUE TITLE
添加函数泛型返回对应List<Type>的models

### ISSUE THREAD

**Issue by liuxiaoliu66** [liangjingkanji/BRV#40]
`  fun <T> BindingAdapter.getModels() = mutable as ArrayList<T>`
获取model有getModel<xxx>()，能否为getModels时也添加一个类似的方法，有时候会方便许多

**Comment by liangjingkanji** [comment]
你可以重新打开上个issues.  在上个issues我已经提到了models里面如果是多类型的话存在很多个类型的元素, 无法统一转成某个元素.

而且你可以使用`adapter.getModel<Type>(position)`直接获取指定类型元素即可.

```kotlin
val myList = arrayList<String>()
rv.{
   onBind{
       val model = getModel<String>()
   }
}.models = myList

myList.foreach {
    // it 即为String
}
```
假设你需要在adapter外层遍历集合, 你可以直接遍历你将赋值给models的myList(这个你可以自己声明为某个类型的list), 而不是遍历models. models即你传入的list
