### ISSUE TITLE
无法下载sources

### ISSUE THREAD

**Issue by yzjdev** [liangjingkanji/BRV#401]
## 问题描述 
Could not GET 'https://jitpack.io/com/github/liangjingkanji/BRV/1.5.5@aar/BRV-1.5.5@aar.pom'. Received status code 400 from server: Bad Request

## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.5.5
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
路径如下: https://jitpack.io/com/github/liangjingkanji/BRV/1.5.5/

你请求的路径错误的

**Comment by yzjdev** [comment]
也许这是jitpack导致的  期待迁移更新
