### ISSUE TITLE
关于checkedAll(false)的一些问题

### ISSUE THREAD

**Issue by yzjdev** [liangjingkanji/BRV#403]
## 问题描述
1  对于一个bean的checked默认为true时  checkedAll(false)  无法正确识别状态  需要手动向checkedPostions集合里添加checked=true的bean对应的position 
2  在第一次加载列表后  还没有处于可见状态的item对应的checked状态， 调用checkedAll(false)无法立即更新后续的item的checked状态

## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

https://github.com/liangjingkanji/BRV/assets/121114254/fed55bef-6dbf-4be3-ba3a-a75ec1cee219

https://github.com/liangjingkanji/BRV/assets/121114254/a5f9afb1-dc88-491b-a55e-0d1d06607be6

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.5.5
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
1. 文档已经提到`setChecked`去设置默认选中, BRV的选择状态是解耦的, 不可能知道你字段变化了
2. 该问题应该是你在onCheck里面仅更新View的状态而没有像demo一样更新数据, 至于原因建议你学习下rv复用机制

**Comment by liangjingkanji** [comment]
1. 文档写了
2. Demo无法复现

**Comment by yzjdev** [comment]
![feb344433ce4b1b04ec879b8b05b1f7](https://github.com/liangjingkanji/BRV/assets/121114254/96aa7496-d93f-4682-97d1-05be8bda91bf)




https://github.com/liangjingkanji/BRV/assets/121114254/4c0828e9-5f9f-468d-8cf4-b471cfc999de


大佬你好 我使用您的demo  仅修改了此处  复现了我所反馈的第二个问题  我不知道应该在什么地方去调用什么方法来更新model

**Comment by liangjingkanji** [comment]
fork仓库发我地址或者直接发代码， 或者自行修复
