### ISSUE TITLE
求助，列表滑上滑下后发现item的Textview状态会自动改变

### ISSUE THREAD

**Issue by luckyfuzhi** [liangjingkanji/BRV#405]
https://github.com/liangjingkanji/BRV/assets/109713443/bb32056c-148d-4662-bd61-adc437d0f945

![brv的bug图片](https://github.com/liangjingkanji/BRV/assets/109713443/56b50e01-656b-4cf1-9eee-c76a76994bf2)
## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by dlisagod** [comment]
这不是很基础的问题吗，你状态自己没处理好，rv是会复用的，所以你得处理好label!=0时的状态

**Comment by liangjingkanji** [comment]
> 这是很基础的问题，你状态没处理好，rv是会复用的，所以你得处理好choice不等于0、1和label!=0时的状态

他回答的很好
