### ISSUE TITLE
使用autoRefresh时，使用TabLayout+ViewPager2快速切换会导致中间的onRefresh不被调用到。

### ISSUE THREAD

**Issue by parcool** [liangjingkanji/BRV#408]
先看视频：
[Screen_recording_20231130_183027.webm](https://github.com/liangjingkanji/BRV/assets/12092478/a84fa1d4-5491-44a1-99fe-d205cfec4b44)
经过简单排查发现：
```
@Override
protected void onDetachedFromWindow() {
    super.onDetachedFromWindow();
    mAttachedToWindow = false;
    mManualLoadMore = true;
    animationRunnable = null;
    if (reboundAnimator != null) {
        Animator animator = reboundAnimator;
        animator.removeAllListeners();
        reboundAnimator.removeAllUpdateListeners();
        reboundAnimator.setDuration(0);//cancel会触发End调用，可以判断0来确定是否被cancel
        reboundAnimator.cancel();//会触发 cancel 和 end 调用
        reboundAnimator = null;
    }
......
}
```
SmartRefershLayout里的onDetachedFromWindow执行了（中间那个tab的），这会导致刷新不被调用到。看上去是SmartRefreshLayout本身的锅，但这个问题怎么解决呢？

**Comment by liangjingkanji** [comment]
能fork仓库复现下问题吗? 我猜测不到原因

**Comment by parcool** [comment]
已fork仓库并复现。
仓库地址：[https://github.com/parcool/BRV](https://github.com/parcool/BRV)

[Screen_recording_20231201_125559.webm](https://github.com/liangjingkanji/BRV/assets/12092478/5be173c5-86d4-42e7-a7d5-2c952cc7e1e3)
从视频中可以看到，第二页（评论页），界面是空的。

**Comment by liangjingkanji** [comment]
跨标签切换会存在该问题, 具体怎么修复SmartRefreshLayout这个问题我也不清楚, 或许你应该给作者反馈下

给几个建议吧
1. 初次使用缺省页体验更好, `autoRefresh()`改为`showLoading()`
2. 懒加载, 在`Fragment.onResume`去请求网络
