### ISSUE TITLE
多类型:怎么根据不同的类型分别设置rv.linear()和rv.grid()

### ISSUE THREAD

**Issue by v1ncent9527** [liangjingkanji/BRV#41]

**Comment by liangjingkanji** [comment]
rv.layoutManager = MyLayoutManager()

grid就是GridLayoutManager的封装函数
linear就是LinearLayout的封装函数

如果你说的根据item的type设置layoutManager那是不可能的. 但是grid完全满足linear的功能 
搜索: `GridLayoutManager spanSize 如何使用`

**Comment by v1ncent9527** [comment]
Ojbk，搞定了，thanks
