### ISSUE TITLE
跨 item或者id 防抖问题

### ISSUE THREAD

**Issue by tc7326** [liangjingkanji/BRV#412]
当点击RecyclerView中同一个item的同一个id时 防抖有效。

当点击RecyclerView中第一个 item/id 后 迅速点击第二个 item/id 防抖无效。

效果如图：

![SVID_20231213_163634_1](https://github.com/liangjingkanji/BRV/assets/38179758/f0f4fa85-6b12-4b67-8546-2e2165ea9e77)

**Comment by liangjingkanji** [comment]
你去看下大厂App支持不, 我认为这种极端情况不需要考虑

即使你做了, 后面你又会要求全屏幕所有控件都防抖动吧, 你干脆禁止掉屏幕多点触控功能得了

**Comment by liangjingkanji** [comment]
而且我认为这和BRV框架没关系

**Comment by tc7326** [comment]
> 你去看下大厂App支持不, 我认为这种极端情况不需要考虑
> 
> 即使你做了, 后面你又会要求全屏幕所有控件都防抖动吧, 你干脆禁止掉屏幕多点触控功能得了

你好，首先这不是极端情况，是一个很正常也很常见的需求：

我刚测试了部分APP 包括但不限于 抖音快手 淘宝京东 QQ微信 等。

它们的列表均可以正常的 跨 itme/id 防抖。你也可以亲自试试再下定论。

我为什么提这个问题：

因为目前项目一般都是采用view的拓展函数来实现 全局防抖 具体可以参考这个 https://www.jianshu.com/p/7118226ecba9

还有你说和你的框架没有关系 但是你框架的 onclick 传递的是view的id 破坏了原view的onclick事件

如果我在项目中使用该框架 就需要为了适配该框架又得重新写一套拦截逻辑。这样对于我来就本末倒置了。

还有我只是提出使用中的问题并进行反馈 也不至于让你大动干戈 戾气十足。

至于该不该 或者说是否进行实现 不还是你说了算。

还有 你是做开源了 你的目的是推广你的项目 让你的项目变得更好 或者说提升你的知名度。

而我 只是个使用者 框架用的不舒服我换一个就好 我们并没有利益冲突。

**Comment by liangjingkanji** [comment]
如果是本框架自身点击事件造成了你维护全局防抖动的需求, 那可以改

我最近工作繁忙同时也没有实现案例过, 如果你有修改方案可以提pr, 我会review合并

这是开源框架, 我不需要什么知名度, 谁在用谁就有维护责任
我不是brv作者我只是使用者之一, 至于利益冲突这框架没任何利益, 选择用或不用或者pr都取决于你

如果不喜欢我回复语气, 下次可以换一个人来回复

**Comment by tc7326** [comment]
> 如果是本框架自身点击事件造成了你维护全局防抖动的需求, 那可以改
> 
> 我最近工作繁忙同时也没有实现案例过, 如果你有修改方案可以提pr, 我会review合并
> 
> 这是开源框架, 我不需要什么知名度, 谁在用谁就有维护责任 我不是brv作者我只是使用者之一, 至于利益冲突这框架没任何利益, 选择用或不用或者pr都取决于你
> 
> 如果不喜欢我回复语气, 下次可以换一个人来回复

你好 抱歉 昨天走进思维误区了 我今天用多台手机重新测试 确认 不是框架的问题。

应该是 RecyclerView 自身的问题 或者 某些ROM的问题。

我分别测试了 Android 10 到 13 的 框架实现 和 原生adapter实现 均为正常。

在基于Android10的某蒙ui上 表现出可以连续点击item的现象。

到此，该问题不属于框架的问题，可以关闭该问题。

造成的困扰 在此抱歉。

**Comment by liangjingkanji** [comment]
BRV并没支持跨Item防抖动

试下这个版本吧
```
implementation 'com.github.liangjingkanji:BRV: ac84d3bc9b'
```

**Comment by smalls0098** [comment]
作者对于安卓贡献还是很牛的，特别是kotlin。4天前提出的item防抖，今天就解决了，其他大佬可能会让你自己提pr。
不行了，我还要再吹一次大佬牛逼

**Comment by originzyf** [comment]
作者对于安卓贡献还是很牛的，特别是kotlin。4天前提出的item防抖，今天就解决了，其他大佬可能会让你自己提pr。
不行了，我还要再吹一次大佬牛逼
