### ISSUE TITLE
编译依赖失败

### ISSUE THREAD

**Issue by QIMOU** [liangjingkanji/BRV#414]
## 问题描述
依赖导入失败
## 期望结果
导入成功
## 如何复现
api 'com.github.liangjingkanji:BRV:1.5.8'
> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

https://jitpack.io/com/github/liangjingkanji/BRV/1.5.8/BRV-1.5.8.pom
## 截图
<img width="419" alt="image" src="https://github.com/liangjingkanji/BRV/assets/43950415/c4ff86c1-7504-4ae5-9b68-84c9769ae4d0">
<img width="1243" alt="image" src="https://github.com/liangjingkanji/BRV/assets/43950415/bb1a8a8d-d5cb-4ea8-b755-8e097089c4c6">

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.5.8
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
点击链接可以打开文件, 你不能打开吗

**Comment by QIMOU** [comment]
打不开的

**Comment by QIMOU** [comment]
<img width="978" alt="image" src="https://github.com/liangjingkanji/BRV/assets/43950415/f7ed7284-5e1c-4581-962d-ecee9c0f8e21">
<img width="1116" alt="image" src="https://github.com/liangjingkanji/BRV/assets/43950415/203e84ae-badd-4183-9780-7079fb7b3cf7">

**Comment by liangjingkanji** [comment]
第二张截图就是

**Comment by QIMOU** [comment]
第二张截图就是正常情况的吗？ 
但是android studio 编译就一直提示这个。[头大]
![image](https://github.com/liangjingkanji/BRV/assets/43950415/d8c8ef0c-956d-4fed-94cc-947f824d4253)

**Comment by QIMOU** [comment]
或者 有jar、aar包吗。昨天弄了一下午 就是运行不了

**Comment by liangjingkanji** [comment]
https://jitpack.io/com/github/liangjingkanji/BRV/1.5.8/BRV-1.5.8.aar

**Comment by QIMOU** [comment]
嗯嗯 ，刚到公司，我再运行一遍试试，公司网络确实不好 时好时坏
