### ISSUE TITLE
这个能实现出iOS通知中心那种效果吗？

### ISSUE THREAD

**Issue by MarkHan1213** [liangjingkanji/BRV#427]
## 描述
iOS通知中心那种堆叠效果，从底部是层叠的状态（一个item 盖着一个item），向上滑动逐个展开，直到底部没有内容。

## 参考实现
参考iOS通知中心

## 是否可以参与实现
> 由于本项目参与者的技术及精力有限无法满足大部分开发者的需求, 欢迎开发者参与贡献

**Comment by liangjingkanji** [comment]
本框架是简化和自带某些RecycleView效果, 你说效果本框架没有提供简化, 请自行实现

如果你问RecycleView能否实现, 那你可以搜索自定义LayoutManager
