### ISSUE TITLE
能添加DiffUtil 扩展么

### ISSUE THREAD

**Issue by walker0406** [liangjingkanji/BRV#43]
rt

**Comment by liangjingkanji** [comment]
本身就支持`DiffUtil`
而且如果你是直接刷新item中的视图, 我建议使用DataBinding的`notifyChange`, 效率比DiffUtil更高, 也更方便

**Comment by liangjingkanji** [comment]
BRV只是自定义Adapter, 并不影响使用DiffUtil. 不过目前已更新对DiffUtil的快速实现: [使用文档](https://liangjingkanji.github.io/BRV/refresh-data/#_2)
