### ISSUE TITLE
有没有兼容的 fastbar 

### ISSUE THREAD

**Issue by xiaocainiaooo** [liangjingkanji/BRV#433]
## 描述
我当前使用 HoverGridLayoutManager 的时候开了原生的 fastbar

            app:fastScrollEnabled="true"
            app:fastScrollHorizontalThumbDrawable="@drawable/fast_scroll_thumb"
            app:fastScrollHorizontalTrackDrawable="@drawable/fast_scroll_track"
            app:fastScrollVerticalThumbDrawable="@drawable/fast_scroll_thumb"
            app:fastScrollVerticalTrackDrawable="@drawable/fast_scroll_track"
            会bar 出现后会抖动 控制效果也很差
## 是否可以参与实现
> 由于本项目参与者的技术及精力有限无法满足大部分开发者的需求, 欢迎开发者参与贡献

**Comment by liangjingkanji** [comment]
那你就先使用官方的`GridLayoutManager`
