### ISSUE TITLE
模块化下使用runtimeOnly依赖，被依赖的library中的列表显示不了内容

### ISSUE THREAD

**Issue by cdck** [liangjingkanji/BRV#434]
## 问题描述
使用模块化的时候，如果`sample`使用 `runtimeOnly` 的方式依赖`mylibrary`，在`mylibrary`里的Activity的onCreate处配置了` BRV.modelId = BR.m` ，也会导致内容失效，就是item无法显示内容，显示效果相当于空白占位的效果
## 期望结果
如果使用的是`implementation`依赖则就正常，期望跟该情况一样是需要如何配置
## 如何复现
[fork的示例地址：https://github.com/cdck/BRV](https://github.com/cdck/BRV)

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)
![2024-04-10-10-47-40](https://github.com/liangjingkanji/BRV/assets/26270449/4966f456-ed94-43d7-8ae3-b41280d3dc37)
但是数据是有的：
![2024-04-10-10-49-06](https://github.com/liangjingkanji/BRV/assets/26270449/3c50faa8-1631-4916-8c02-2c1c5d5e1e88)

## 版本
- BRV: 1.5.8
- Android: 12
- Gradle: 8.0
- Android Studio: Android Studio Flamingo | 2022.2.1

**Comment by liangjingkanji** [comment]
`BR.m`相当于`R.`属于资源索引,  我不写多模块应用, 你可以自行搜索解决方案

1. 或你也可以通过直接设置常量解决
2. 或者在每个模块都设置一次`BR.m`
