### ISSUE TITLE
给BindingAdaptor.onCreateViewHolder中的itemView初始赋值提供一个可以覆写的函数

### ISSUE THREAD

**Issue by bobskycn** [liangjingkanji/BRV#437]
## 
open fun inflateView(parent: ViewGroup, viewType: Int):View{
        return LayoutInflater.from(parent.context).inflate(viewType, parent, false)
}
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): BindingViewHolder {
        val itemView =inflateView(parent,viewType)
}

## 是否可以参与实现
> 由于本项目参与者的技术及精力有限无法满足大部分开发者的需求, 欢迎开发者参与贡献

**Comment by liangjingkanji** [comment]
`onCreateViewHolder`可以覆写不就足够了吗?
