### ISSUE TITLE
PageRefreshLayout在refreshing后，失效无法回调和动画无法回弹问题

### ISSUE THREAD

**Issue by ChawLoo** [liangjingkanji/BRV#439]
## 问题描述
下拉刷新组件失效
## 期望结果
正常刷新
## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

Fork：https://github.com/ChawLoo/BRV
已复现，启动即TestAct

## 截图
下拉组件失效了，整个APP并未卡住，下拉回调已经没了，动画效果也不回弹了
![image](https://github.com/liangjingkanji/BRV/assets/26214519/636b7da2-3d1b-48d4-9748-141684f2ece9)
## 版本
- BRV:1.5.8
- Android:11
- Gradle: 8.4.2
- Android Studio: Android Studio Iguana | 2023.2.1 Patch 2

**Comment by RokingYang** [comment]
是有这个问题。我暂时想到的处理方式是手动调用一下finish方法。

**Comment by ChawLoo** [comment]
[跟这个问题类似](https://github.com/liangjingkanji/BRV/issues/353)
也是自定义View的attachToWindow的时序问题
因为没有attachToWindow，这个判断逻辑进不去，就无法更改状态为：RefreshFinish，导致后续状态判断出现问题
![image](https://github.com/liangjingkanji/BRV/assets/26214519/1a9ea952-424b-4469-96e0-d76bebe3eb89)
根源是这个，然后后续一系列的状态切换问题我就不截图了，打断点能看出来

**Comment by zkzk7749** [comment]
我也遇见类似问题，只是我不会排查、定位故障

**Comment by ChawLoo** [comment]
定位到了，正在研究如何修复

**Comment by ChawLoo** [comment]
有个解决方案：
```kotlin
post {
    if (hasMore) finishRefresh(success) else finishRefreshWithNoMoreData()
}
```
![image](https://github.com/liangjingkanji/BRV/assets/26214519/da1491fb-263e-4afa-8bfa-5c9073fa45dd)

**Comment by liangjingkanji** [comment]
#440 这个方案不行吗?

**Comment by ChawLoo** [comment]
> #440 这个方案不行吗?

不行，我已经关闭了，那个方案就无法autorefresh了，还是在SM的状态管理上的问题

**Comment by ChawLoo** [comment]
> 有个解决方案：
> 
> ```kotlin
> post {
>     if (hasMore) finishRefresh(success) else finishRefreshWithNoMoreData()
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/26214519/328069359-da1491fb-263e-4afa-8bfa-5c9073fa45dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjcxODksIm5iZiI6MTcxNDk2Njg4OSwicGF0aCI6Ii8yNjIxNDUxOS8zMjgwNjkzNTktZGExNDkxZmItMjYzZS00YWZhLThiZmEtNWM5MDczZmE0NWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAzNDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NTk5NTllYjk1NzYxYjQ0ZGExNWM4YWFiNTk1OGU0OTNlNWYxOGFlMjk4YzliMGUwNjk5MGUzNTFiZjc5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D-qRU1Y-m4SzFHejnW2CAKZY30CEiKvTvvhWpN28VuQ)

如果是这个方案，考虑的地方就很多，感觉还是需要在sm的状态上做文章

**Comment by liangjingkanji** [comment]
你使用refreshing的生命周期是什么

**Comment by ChawLoo** [comment]
> 你使用refreshing的生命周期是什么?
> 
> 建议在ViewCreated中使用

如果是Act呢？

**Comment by liangjingkanji** [comment]
Act也有类似View创建好的生命周期吧

**Comment by ChawLoo** [comment]
自定义View的attachToWindow生命周期是这样的，
Act.onCreate -> Act.onResume -> Act.onAttachedToWindow -> View.onAttachedToWindow
所以我说加一个post能解决，但是如果加了post的话，考虑的地方就很多

**Comment by ChawLoo** [comment]
@liangjingkanji 最新的PR #442 我测了一下可以修复，你那边要么从其他角度看看？我自己尝试了我能想到的finish均无问题

**Comment by ChawLoo** [comment]
不行，如果加延迟异步执行，解决问题，但是存在一个细节，如果进入页面快速去进行下拉操作是无法下拉的

**Comment by RokingYang** [comment]
调用refresh后再16ms内调用finish必现。

**Comment by ChawLoo** [comment]
> 调用refresh后再16ms内调用finish必现。

他就是因为异步的原因，导致状态不一致，因为SM没有refreshing的方法，所以没问题，看大佬最近忙，自己临时方案解决一下吧，等他后续看看能不能修复

**Comment by liangjingkanji** [comment]
仔细看了下问题, 这就是由于页面未创建完成导致SmartRefreshLayout没有在刷新完成后重置状态为`RefreshState.None`

**Comment by liangjingkanji** [comment]
已修复试试新版本吧
