### ISSUE TITLE
提一个小小建议啊，希望作者适配一下paging3

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/BRV#441]
## 描述
现在是2024年5月了，老建议再提一次，希望作者适配一下paging3

## 理由

众所周知，本库是最牛逼的RV库，已经很完美了。

因官方的ViewPager2坑太多，但我们没办法阻挡官方强推ViewPager2的意志，某些时候在ViewPager2中使用BRV会出现莫名其妙的问题，虽然这些问题非BRV的问题。
所以我建议作者适配一下paging3，主要是为了应对在ViewPager2中多子fragment情况下，且不用PageRefreshLayout时使用。

## 参考实现

无

## 是否可以参与实现
> 由于本项目参与者的技术及精力有限无法满足大部分开发者的需求, 欢迎开发者参与贡献

---------------小弟乐意参加测试，贡献代码就算了，犹如太监上青楼，有心无力

**Comment by liangjingkanji** [comment]
Paging3使用过于复杂, 我从不使用
