### ISSUE TITLE
MaterialHeader 下拉刷新时，有阴影，请查看截图

### ISSUE THREAD

**Issue by gxg-886** [liangjingkanji/BRV#445]
## 问题描述
MaterialHeader 下拉刷新时，有阴影，请查看截图
自定义的Header代码
class MyMaterialHeader : MaterialHeader {
    constructor(context: Context?) : super(context)
    constructor(context: Context?, attrs: AttributeSet?) : super(context, attrs)

    override fun setProgressBackgroundColorSchemeResource(colorRes: Int): MaterialHeader {
        return super.setProgressBackgroundColorSchemeResource(colorRes)
    }

    override fun setColorSchemeResources(vararg colorIds: Int): MaterialHeader {
        return super.setColorSchemeResources(*colorIds)
    }

    override fun setSize(size: Int): MyMaterialHeader {
        mCircleDiameter = ResUtils.getDimensionPixelSize(R.dimen.common_sw_40dp)
        mCircleView.setImageDrawable(null)
        mProgress.updateSizes(size)
        mCircleView.setImageDrawable(mProgress)
        return this
    }
}
## 期望结果
没有阴影

## 如何复现
个别车机设备必现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图
![image](https://github.com/liangjingkanji/BRV/assets/28705834/11675409-f21e-4c3a-a29a-56d1117f9d66)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.5.8
- Android: 14
- Gradle: 8.2.1
- Android Studio:
- Android Studio Iguana | 2023.2.1
Build #AI-232.10227.8.2321.11479570, built on February 22, 2024
Runtime version: 17.0.9+0-17.0.9b1087.7-11185874 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5

**Comment by liangjingkanji** [comment]
请反馈给 SmartRefreshLayout 库, 本仓库没有MaterialHeader源码
