### ISSUE TITLE
拖拽替换回调问题

### ISSUE THREAD

**Issue by chenzz66** [liangjingkanji/BRV#447]
## 问题描述
 拖拽回调事件
DefaultItemTouchCallback中onDrag第一次交换后松手没问题
如果第二次只是长按立马松开还是会触发onDrag事件,两个item还是上次交换的item
这个时候是否可以在onDrag后把sourceViewHolder, targetViewHolder置为null呢

## 期望结果
在不进行交换的时候不触发onDrag事件

## 如何复现
第二次只是长按立马松开
> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.5.8
- Android:11
- Gradle: 8.6
- Android Studio:Android Studio Jellyfish | 2023.3.1 RC 2

**Comment by liangjingkanji** [comment]
感觉你说的解决方案可以, 如果你有空或者希望成为brv贡献者可以提一个pr

如果没想法我有空会发布该版本

**Comment by liangjingkanji** [comment]
无法复现你描述的问题, 你录屏看下吧

**Comment by chenzz66** [comment]
> 无法复现你描述的问题, 你录屏看下吧
> 
> ```kotlin
>     /**
>      * 拖拽移动超过其他item时, 其返回值表示是否已经拖拽替换(会触发函数onMoved)
>      * @return 返回false 禁止被拖拽交换移动
>      */
>     override fun onMove(
>         recyclerView: RecyclerView,
>         source: RecyclerView.ViewHolder,
>         target: RecyclerView.ViewHolder,
>     ): Boolean
> ```
> 
> 理论上你没有超过其他item不会回调`onMove`


https://github.com/user-attachments/assets/07ddff0a-583f-43bf-bfee-45f665fa57b4

没有拖拽交换移动也触发了onDrag事件

**Comment by liangjingkanji** [comment]
原来是错误触发`onDrag`, 我理解有误了

**Comment by liangjingkanji** [comment]
通过记录拖拽起始位置, 实现拖拽起始位置等于目标位置则属于无效移动, 不回调onDrag方法

应该超出你要求的预期效果吧
