### ISSUE TITLE
官方群被封禁了

### ISSUE THREAD

**Issue by Eleven115** [liangjingkanji/BRV#449]
## 是否可以参与实现
> 由于本项目参与者的技术及精力有限无法满足大部分开发者的需求, 欢迎开发者参与贡献

**Comment by liangjingkanji** [comment]
已经创建新的群了, 本问题提供的图片随时更新

<img src="https://raw.githubusercontent.com/liangjingkanji/liangjingkanji/master/img/group-qrcode.png" width="50%"/>
