### ISSUE TITLE
将仓库迁移到mavenCentral

### ISSUE THREAD

**Issue by sth0409** [liangjingkanji/BRV#45]
jcenter停止服务了，作者还没迁移到mavenCentral、jitpack之类的仓库   有替代方案吗

**Comment by liangjingkanji** [comment]
目前我也有迁移到mavenCentral的打算. 到时候我会将其全部迁移到mavenCentral, 包含间接依赖(如果原作者迟迟不迁移)

目前我不建议你删除jcenter, 因为这个是永久提供访问服务(只是不能更新和上传). 很多第三方还在使用中

**Comment by liangjingkanji** [comment]
很抱歉还没迁移到mavenCentral, 一是太忙二是mavenCentral发布新版本审核时间非常长, 可能需要几个小时可能无法满足快速修复bug需求
