### ISSUE TITLE
Recyclerview嵌套Recyclerview，如何获取外面那个Recyclerview的索引

### ISSUE THREAD

**Issue by rayzeng0221** [liangjingkanji/BRV#451]
## 如何复现

> 希望快速解决请Fork仓库复现问题并附上链接, 否则只能等有空才能排查
> 凭空猜测只会让问题晦涩难懂, 浪费本项目可持续维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
问题和本开源项目无关, 不要随便提issues

让内嵌rv的models存储外部rv的item索引即可
