### ISSUE TITLE
未给Models初始化的情况下，触发checkAll 空指针异常

### ISSUE THREAD

**Issue by AR-OoO** [liangjingkanji/BRV#453]
## 问题描述
如题

## 期望结果
触发checkAll不崩溃
## 如何复现
初始化RecyclerView，但是不初始化models，直接调用checkAll方法

原因可能性分析：
setChecked方法调用了isCheckedAll方法
isCheckedAll方法中使用了checkableCount属性的get方法
```kotlin
private val checkableCount: Int
get() {
    var count = 0
    if (checkableItemTypeList == null) {
        return models!!.size
    } else {
        for (i in 0 until itemCount) {
            if (checkableItemTypeList!!.contains(getItemViewType(i))) {
                count++
            }
        }
    }
    return count
}
```

当models未被初始化时为null,且没有设置过checkableItemTypeList时，
就会走return models!!.size
触发NullPointException

## 截图
![image](https://github.com/user-attachments/assets/83e7a9c3-6495-406a-8266-64123319ccd7)

## 版本
- BRV: 1.5.4
- Android: 14
- Gradle:  7.4
- Android Studio: 2022.3.1 Patch 3

**Comment by liangjingkanji** [comment]
你发现的问题不错, 如果你想参与开源项目中可以提pr, 如果没有经验可以看我主页"加入我们"教程

如果没兴趣可以等待我发布下个版本

**Comment by liangjingkanji** [comment]
将在下次更新发布
