### ISSUE TITLE
横向拖拽功能存在问题

### ISSUE THREAD

**Issue by cjcj125125** [liangjingkanji/BRV#456]
## 问题描述
拖动排序功能(横向拖动)存在两个问题：
1.按照文档实现代码，文档为纵向列表，我改为横向列表后发现容易出现拖动完成后 onDrag 方法没有收到回调(慢速拖动)；
2.横向拖动排序需要重写getMovementFlags方法无法进行拖动，需要将其重写为以下代码
![image](https://github.com/user-attachments/assets/83740005-45fd-46fc-b903-1db42fe612fb)

## 期望结果
1. 每次拖动后都能收到onDrag回调与拖动快慢没有关系
2. 代码需要修复上述bug
## 如何复现
按照上述代码复现

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV: 1.6.0
- Android: 10
- Gradle:  7.5
- Android Studio: 2023.3.1 Jellyfish

**Comment by liangjingkanji** [comment]
不是可以指定拖拽方向吗? [拖拽方向设置](https://liangjingkanji.github.io/BRV/drag.html#_1) 为什么要重写

**Comment by liangjingkanji** [comment]
onDrag只是为了方便新增的一个回调函数, 如果不容易出发你可以使用他的上层函数调用

**Comment by cjcj125125** [comment]
确实可以指定拖拽方向，但是我设置了依然无效，重写了之后可以了

**Comment by liangjingkanji** [comment]
看源码和重写无区别, 不知道你是什么情况
