### ISSUE TITLE
项目运行报错，很多第三方库找不到

### ISSUE THREAD

**Issue by yzgt** [liangjingkanji/BRV#464]
编译不报错，运行就报错

## 截图
![image](https://github.com/user-attachments/assets/cfdb4ad8-597d-4831-ad74-01627762dab1)

## 版本
- BRV:1.5.0
- Android:
- Gradle: 
- Android Studio: 最新版

**Comment by senselesscn** [comment]
哥们，这种问题找找自己原因吧

**Comment by liangjingkanji** [comment]
我看你的仓库版本好像很低, 要不你pull更新下

**Comment by yzgt** [comment]
> 哥们，这种问题找找自己原因吧

那你说什么原因？网络没问题

**Comment by yzgt** [comment]
> 我看你的仓库版本好像很低, 要不你pull更新下

下载新版本吗？我就想用旧版，项目里用的是旧版

**Comment by senselesscn** [comment]
> > 哥们，这种问题找找自己原因吧
> 
> 那你说什么原因？网络没问题

这几个依赖报错都是版本找不到，那很有可能版本太低了，这个时候要么升级BRV，要么把这几个排除一下，手动把新版本的加进去

**Comment by liangjingkanji** [comment]
> > 我看你的仓库版本好像很低, 要不你pull更新下
> 
> 下载新版本吗？我就想用旧版，项目里用的是旧版

旧版本建议别用了, 可能有bug, 目前来说没什么迁移问题吧

**Comment by yzgt** [comment]
换成阿里云的镜像可以了

**Comment by liangjingkanji** [comment]
的确存在一个三方库flexbox无法找到依赖
```groovy
implementation "com.google.android:flexbox:1.1.0"
```
已经由@Gu1nBz升级合并
```groovy
implementation 'com.google.android.flexbox:flexbox:3.0.0'
```
