### ISSUE TITLE
itemTouchHelper搭配交错列表瀑布流staggered拖拽问题

### ISSUE THREAD

**Issue by jsonlinlin7** [liangjingkanji/BRV#465]
请问一下，当使用itemTouchHelper搭配交错列表瀑布流staggered，当拖动第一项到其他位置时候，第一项会迅速滑动到最后面。如果使用grid则不会有这个现象发生。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jsonlinlin7** [comment]
这个问题和#200的Issues的问题一样，只是这个是使用瀑布流网格出现的，当前使用的brv版本是最新的1.6.0

**Comment by liangjingkanji** [comment]
使用自带的StaggeredLayoutManager看能否解决

**Comment by jsonlinlin7** [comment]
真是醉了，按照官方用ItemTouchHelper和StaggeredGridLayoutManager来写，没用任何第三方库还是会有这个问题。只有当数据超过一个屏幕后拖动第一个item才会迅速往下滑
