### ISSUE TITLE
staggered布局刷新问题

### ISSUE THREAD

**Issue by jsonlinlin7** [liangjingkanji/BRV#466]
东哥，网格瀑布流布局又有问题，在外层brv 的staggered布局中的onCreate中嵌套多一个brv的grid布局，点击这个grid中的控件时候把整个rv 的modes重新赋值，外层brv的onCreate会被重新调用刷新，而如果外层brv设置为liner 布局的话，外层brv 的onCreate不会重新调用。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by liangjingkanji** [comment]
那你使用自带的StaggeredLayoutManager看能否解决
