### ISSUE TITLE
用户手动修改时间导致的点击失效问题

### ISSUE THREAD

**Issue by mrzhangk97** [liangjingkanji/BRV#469]
## 描述
用户手动修改时间导致的点击失效问题
## 理由
当使用onClick()时，如果用户手动修改了客户端时间，改成过去的时间，会导致点击无法被执行
## 参考实现
建议将OnDebounceClickListener中的判断if (currentTime - lastDebounceClickTime > interval) 改为 abs(currentTime - lastDebounceClickTime) > interval
## 是否可以参与实现
> 由于本项目参与者的技术及精力有限无法满足大部分开发者的需求, 欢迎开发者参与贡献

**Comment by liangjingkanji** [comment]
这的确是早期遗留的坑, 以前就想修复下
不过方案是将 `System.currentTimeMillis()` 替换为 `SystemClock.elapsedRealtime()`

**Comment by liangjingkanji** [comment]
请升级至最新版本
