### ISSUE TITLE
增加数据新增时，滑动到新增数据位置的功能

### ISSUE THREAD

**Issue by HAHH9527** [liangjingkanji/BRV#48]
现在的实现方法是这样子的

```kotlin
recyclerView.setup{
    registerAdapterDataObserver(object : RecyclerView.AdapterDataObserver() {
        override fun onChanged() {
           recyclerView.smoothScrollToPosition(this@setup.modelCount)
           // 在收到onChanged后 直接滑动到最后一个
        }
    })
}
```

测试了`registerAdapterDataObserver`中的其他回调 都收不到任何通知

个人的一点思路(暂时没有多少时间完善代码，如采纳此需求可有空后提交pr)
```kotlin
/** 数据模型集合 */
var models: List<Any?>? = null
    set(value) {
        // TODO 在此处做一下数据的 Diff 判断,按需调用notify
         ......
    }
```

增加一个默认的`AdapterDataObserver`,通过开关管理在添加新数据后的动作

**Comment by liangjingkanji** [comment]
功能不错. 可以添加, 期待你的pr

但是提醒下`models`并不是添加数据的唯一办法. 使用`notifyDataChange`等函数或者`addData`都可以添加数据

**Comment by HAHH9527** [comment]
> 功能不错. 可以添加, 期待你的pr
> 
> 但是提醒下`models`并不是添加数据的唯一办法. 使用`notifyDataChange`等函数或者`addData`都可以添加数据

我是把数据通过BindingAdapter扔进去的😂
```kotlin
    @JvmStatic
    @BindingAdapter(value = ["initBRV", "brvData"])
    fun setRv(recyclerView: RecyclerView, initBRV: (RecyclerView) -> Unit, data: List<Any?>?) {
        if (recyclerView.adapter == null) {
            initBRV(recyclerView)
        }

        val adapter = recyclerView.adapter
        if (adapter is BRVAdapter) {
            adapter.models = data
        } else throw IllegalArgumentException("需要使用\"com.drake.brv.BindingAdapter\"才能设置此属性")
    }
```

**Comment by liangjingkanji** [comment]
![image](https://user-images.githubusercontent.com/21078112/134874638-fe1545be-39c0-4b66-b5ae-7e324e24e90d.png)



> > 功能不错. 可以添加, 期待你的pr
> > 但是提醒下`models`并不是添加数据的唯一办法. 使用`notifyDataChange`等函数或者`addData`都可以添加数据
> 
> 我是把数据通过BindingAdapter扔进去的😂（不过看起来这么用还是有点怪
> 
> ```kotlin
>     @JvmStatic
>     @BindingAdapter(value = ["initBRV", "brvData"])
>     fun setRv(recyclerView: RecyclerView, initBRV: (RecyclerView) -> Unit, data: List<Any?>?) {
>         if (recyclerView.adapter == null) {
>             initBRV(recyclerView)
>         }
> 
>         val adapter = recyclerView.adapter
>         if (adapter is BRVAdapter) {
>             adapter.models = data
>         } else throw IllegalArgumentException("需要使用\"com.drake.brv.BindingAdapter\"才能设置此属性")
>     }
> ```

**Comment by liangjingkanji** [comment]
使用rv函数即可
