### ISSUE TITLE
依赖的StateLayout能不能更新到最新版啊大佬

### ISSUE THREAD

**Issue by v1ncent9527** [liangjingkanji/BRV#52]
![image](https://user-images.githubusercontent.com/17847571/135373550-6bb29e4e-8bda-41d3-81d2-e4ff8ca66d15.png)

**Comment by liangjingkanji** [comment]
最新版本的BRV就是最新版本. 你没更新吧
```
api "com.github.liangjingkanji:StateLayout:1.2.0"
```
