### ISSUE TITLE
不愧是Android最强大的RecyclerView框架

### ISSUE THREAD

**Issue by XuanRanDev** [liangjingkanji/BRV#53]
确实是我用过最强大的RecyclerView框架，以后我使用到RecyclerView必将使用到这个框架，希望作者可以维护下去，我也会多写一些文章宣传的（虽然我是菜鸡😂）

**Comment by liangjingkanji** [comment]
多谢! 一直有在维护, 也欢迎你一起参与 🤓

**Comment by liangjingkanji** [comment]
建议配合网络请求框架一起食用

**Comment by XuanRanDev** [comment]
> 建议配合网络请求框架一起食用

会的😄
