### ISSUE TITLE
UpFetch功能下使用divider函数创建的分割线位置计算不对

### ISSUE THREAD

**Issue by v1ncent9527** [liangjingkanji/BRV#58]
![1EF237D1-874D-47A0-9B73-1546DB4980B0](https://user-images.githubusercontent.com/17847571/136652830-691698be-1c1e-4466-b6b2-c506bf028667.png)

code:
![E5A53CA0-46C2-4322-AEEE-6C1D2DD98794](https://user-images.githubusercontent.com/17847571/136652724-96d9c8c7-6707-44dd-9df4-b894183e572a.png)
)

**Comment by liangjingkanji** [comment]
等待修复

**Comment by v1ncent9527** [comment]
当不满一页的时候是不是得靠上呀？

![DA9B7888-7ED7-442F-A53B-7A9750DF70EB](https://user-images.githubusercontent.com/17847571/138385947-3da3a1ad-d265-410e-aea6-f3f0c194a1a3.png)
