### ISSUE TITLE
刷新闪烁问题

### ISSUE THREAD

**Issue by huqiangqaq** [liangjingkanji/BRV#6]
当我的recyclerView的Header里还有一个横向的recyclerView里时，两个recyclerview的数据还是通过两个接口获取时，这时候刷新两个列表都会闪一下。请问下作者是如何处理刷新闪烁问题的？谢谢。

**Comment by liangjingkanji** [comment]
那你单个列表存在闪烁吗? BRV本身不会发生闪烁?   请给我看看你的代码以及录屏给我看看你的闪烁

**Comment by huqiangqaq** [comment]
单列表是不会的。。好像我这种情况会，也不知道是不是我使用的方式不对

 rv.linear().setup {
            addType<News.Lists>(R.layout.item_news)
            addType<Header>(R.layout.header_service)
            onBind {

                when (itemViewType) {
                    R.layout.item_news -> {
                        ImageLoader.with(this@ServiceFragment)
                            .circle(4).load(getModel<News.Lists>().newsFile).into(findView(R.id.iv))
                    }
                    R.layout.header_service -> {
                        val banner = findView<ImageView>(R.id.banner)
                        findView<LinearLayout>(R.id.ll1).setOnClickListener {
                            toast("11111111111111")
                        }
                        ImageLoader.with(this@ServiceFragment).circle(4).load(R.drawable.topbanner)
                            .into(banner)
                        val rv_video = findView<RecyclerView>(R.id.rv_video)

                        rv_video.linear(LinearLayoutManager.HORIZONTAL).setup {
                            addType<Video.Body.Banner>(R.layout.item_video)
                            onBind {
                                ImageLoader.with(this@ServiceFragment)
                                    .circle(4).load(getModel<Video.Body.Banner>().picUrl).into(findView(R.id.iv_thumb))
                            }

                        }
                        getVideos(rv_video)
                        
                    }
                }
            }
            addClickable(R.id.ll_news_content)
            onClick{
                WebActivity.actionStart( context,"http://news-m.rys.com/newsdetail/?id=${getModel<News.Lists>().id}")
            }
        }
        val adapter = rv.bindingAdapter
        adapter.addHeader(Header(), animation = true)


        refresh.onRefresh {
            page = 1
            getNews(page)
        }


        refresh.onLoadMore {
            getNews(++page,isNeedLoading = false)
        }



private  fun getVideos(rv:RecyclerView) {
        rxLifeScope.launch {
            val result = RxHttp.get(HttpConfig.GET_VIDEO)
                .toClass<Video>()
                .await()
            rv.bindingAdapter.models = result.body.bannerList
        }

**Comment by liangjingkanji** [comment]
你可以尝试在onCreate{} 里面设置内嵌的Rv, 在onBind里面设置models试试, 你这个代码太厚重


另外不推荐使用RxHttp

**Comment by liangjingkanji** [comment]
可以直接配合Net: [自动分页](https://liangjingkanji.github.io/Net/auto-page/)

**Comment by huqiangqaq** [comment]
我想了一下，没太明白。我现在就是再onBind里面设置的models。。。

**Comment by liangjingkanji** [comment]
点击图标加群沟通吧,  
![image](https://user-images.githubusercontent.com/21078112/97112717-cebfca00-1720-11eb-9929-b553a332dfa0.png)

**Comment by huqiangqaq** [comment]
好的

**Comment by mtj956052456** [comment]
我在Android13的手机上也出现了闪烁问题，用的Demo的glide加载，QQ群搜不到

**Comment by liangjingkanji** [comment]
> 我在Android13的手机上也出现了闪烁问题，用的Demo的glide加载，QQ群搜不到

搜主页的，brv和图片加载没任何关系
