### ISSUE TITLE
我个人觉得如果不强制要求databinding，这个库用的人会更多

### ISSUE THREAD

**Issue by zjxckangkang** [liangjingkanji/BRV#65]

**Comment by liangjingkanji** [comment]
只是要求打开而已, 没说一定要用.  而且我不认为Android上目前有比DataBinding更好的MVVM解决方案

**Comment by liangjingkanji** [comment]
你如果用ViewBinding写一堆视图绑定的代码.  我认为那是垃圾代码

**Comment by liangjingkanji** [comment]
内部使用DataBinding自动绑定就会要求必须依赖, 否则编译错误. 
但是不要求使用DataBinding
