### ISSUE TITLE
Item类型非常多，addItem和onBind应该怎么写？

### ISSUE THREAD

**Issue by GoombaCN** [liangjingkanji/BRV#66]
老项目 还是用的ScrollView 有一百多Item 准备迁到RecyclerView 找库的时候发现了BRV
Kotlin泛型没有玩明白 写业务代码堪够 今天碰到一个问题

![image](https://user-images.githubusercontent.com/15976623/140447612-abcdcbdd-92a6-4ecd-9b96-4c84728ae70b.png)
这种写法 编译器报错

![image](https://user-images.githubusercontent.com/15976623/140447642-955ec4a8-9b5a-4841-acfc-3598f3ca7df5.png)
这种写法 编译器不报错 
有点没太玩明白这块

按照使用建议 应该是在onBind里加when判断 在不同分支去处理不同的逻辑 但写一百多个条件 再放上所有子Item的处理逻辑 是不是有点。。

所以分成多个类 来处理自己Item的逻辑是比较合理的 就用ItemBind的方式
我写了个BaseItem类 实现ItemBind接口 让Item1 Item2 Item100都继承BaseItem
想少写点代码 所以想用动态加载类的方式 因为不管是哪个Item类 调用的代码都一模一样的 只有具体实现不同

但受限于目前水平看来 只能是addType<Item1>(layoutId) addType<Item2>(layoutId) addType<Item3>(layoutId) 
或者 
onBind{
  when(layoutId){
    R.layout.item1->
    R.layout.item2->
    R.layout.item3->
}
}
这种方式了

想请教一下 有没有更好的实现方式呢

**Comment by GoombaCN** [comment]
@liangjingkanji

**Comment by liangjingkanji** [comment]
首先明确你的问题, 你是每个子item对应一个布局layout是吗?  觉得在onBind处理业务太复杂

**Comment by GoombaCN** [comment]
> 首先明确你的问题, 你是每个子item对应一个布局layout是吗?
> 
> * 如果layout一样只是数据不一样直接在model里面处理数据返回就好了
> * 如果layout也不一样就addType(R.layout.item_type)
> 
> 如果觉得在onBind处理业务太复杂可以选择[其他的方式](https://liangjingkanji.github.io/BRV/#2)

是每个Item对应不同的布局 
目前是每个Item内部都有一个setData方法 用来做setText之类的工作 
我原本以为：addType中泛型传入的是数据的实体类 参数传布局id 然后onBind作用是实例化那些实现了ItemBind接口的类 
后来发现 实现了ItemBind的类 内部的onBind自动回调 
然而addType的泛型 只能是确定的类型 而不能是继承了确定类型的所有子类 
或者您知道 在kotlin中 怎么动态化生成泛型的类型么
举个例子：

val targetType = getType()
addType<targetType>(layoutId)
类似这样。。

**Comment by liangjingkanji** [comment]
查看demo的`接口类型绑定`

**Comment by liangjingkanji** [comment]
或者你直接给每个子Item添加类型都行
