### ISSUE TITLE
点击事件，在快速刷新列表的时候失效了。

### ISSUE THREAD

**Issue by amosxb** [liangjingkanji/BRV#67]

**Comment by liangjingkanji** [comment]
什么叫快速刷新列表

**Comment by liangjingkanji** [comment]
那是正常的，不清楚你为什么频繁调用，这对性能也是不好的，建议你用databinding刷新数据

**Comment by amosxb** [comment]
在做蓝牙列表的时候需要不断的刷新列表，但是就会出现这种点击事件失效的情况。

**Comment by liangjingkanji** [comment]
位于刷新的Item会被重新设置ViewHolder, 而ViewHolder包含点击事件监听器

这里推荐两种解决办法

1. 使用DataBinding去刷新数据而不是刷新Item
2. 使用DiffUtils去只刷新需要刷新的Item而不是刷新全部

**Comment by liangjingkanji** [comment]
现在新增`setDifferModels`函数可以增量更新, 可以试试这个
