### ISSUE TITLE
关于删除相关的问题

### ISSUE THREAD

**Issue by greadking** [liangjingkanji/BRV#68]
我的代码
![Dingtalk_20211115185703](https://user-images.githubusercontent.com/26962322/141770150-ac5d62e5-0fa4-4679-8883-99e9001e99ca.jpg)

下面加了长安事件去删除  产生了问题 见图中
<img width="721" alt="9950CE94-3DD5-4602-8C5F-CF56A4671118" src="https://user-images.githubusercontent.com/26962322/141769654-2fdd95e6-c5f9-4a13-a7b1-bef6d1616301.png">

**Comment by liangjingkanji** [comment]
`notifyItemRemoved`只是显示删除动画, 实际上并未删除数据. 请你先删除数据再调用`notifyItemRemoved`

**Comment by greadking** [comment]
> `notifyItemRemoved`只是显示删除动画，删除数据。请你先删除数据再调用`notifyItemRemoved`

大佬费心了我做了改动
![Dingtalk_20211116091519](https://user-images.githubusercontent.com/26962322/141878445-57875f6f-4e0c-440f-85b3-328daeab66b0.jpg)
![Dingtalk_20211116091851](https://user-images.githubusercontent.com/26962322/141878478-a5333270-0a60-4691-85d7-4417ae670710.jpg)

**Comment by greadking** [comment]
> `notifyItemRemoved`只是显示删除动画, 实际上并未删除数据. 请你先删除数据再调用`notifyItemRemoved`

蟹蟹

**Comment by liangjingkanji** [comment]
你这是没有使用DataBinding吧, 一堆?问号
