### ISSUE TITLE
一个可能不太重要的建议

### ISSUE THREAD

**Issue by dlisagod** [liangjingkanji/BRV#69]
不过这个或许是特意设计的，可能单纯是我的需求冲突。
（MutableList简称ml，ViewModel简称vm）因为要在vm里更新页面显示数据，如共多少条数据之类的，给rcv.models设置了一个指定的vm里的ml对象。使用PageRefreshLayout刷新addData的时候，重新给rcv.models赋值了，就会导致最开始指定的ml失效了。不过我想了解决办法，给vm里的ml设置get方法用于获取rcv.models。

**Comment by liangjingkanji** [comment]
```
使用PageRefreshLayout刷新addData的时候，重新给rcv.models赋值了，就会导致最开始指定的ml失效了
```

在两种情况下会覆盖数据
- addData在加载更多的时候会调用`BidningAdapter.addModels`. 而addModels在models为nullOrEmpty时候的确会覆盖models
- 下拉刷新会直接覆盖

我感觉的确可以考虑保持唯一性, 将addData函数设置为不会强制覆盖models如何(一直保持第一次传入的集合)?

**Comment by dlisagod** [comment]
我看源码也看到了，所以就提了这个

**Comment by liangjingkanji** [comment]
那你改下提个pr吧

**Comment by dlisagod** [comment]
上班稍稍摸鱼写出来了，简单测试了一下，似乎没问题，东哥你再看看有么有什么遗漏的地方补上

**Comment by liangjingkanji** [comment]
我看下

**Comment by liangjingkanji** [comment]
我觉得还是不要用`clear`直接覆盖吧, 但是empty的集合还是可以使用addAll的

**Comment by dlisagod** [comment]
(adjustAdapter.models as? MutableList)?.also {
                    it.clear()
                    adjustAdapter.addModels(data)
                }

你是说这一部分吗，不使用clear的话怎么保证是同一个对象呢

**Comment by liangjingkanji** [comment]
我发出来了吗? 我都不知道. 
就使用`clear`, 我认为逻辑合理性比微乎其微的性能更重要
