### ISSUE TITLE
提个建议，适配Paging3

### ISSUE THREAD

**Issue by dingxiansen1** [liangjingkanji/BRV#73]
作者您好，因为我最近也在学习paging3的使用方式，毕竟它作为jetpack库的成员，paging3使用的人也越来越多，或许作者您可以尝试适配paging3并封装简化他，我不知道这是否会有难度，因为我是今年的应届生，还有很多需要学习的地方。我只是提个意见，希望能让这个库能更强大，让使用它的人有更多的选择。

**Comment by liangjingkanji** [comment]
BRV使用`addData`一个函数即可实现自动分页加载. 
我认为这比`paging3`方便太多. 并且扩展性还更好. 我没有在paging3身上看到优势. 

你可以看到我的函数设计哲学遵守的是简洁/扩展. 如果你能让paging的代码更少更方便我很愿意一起探讨适配问题.

**Comment by liangjingkanji** [comment]
这个框架是开源的, 就意味着每个人都是作者和使用者, 众人拾柴火焰高. 目的是提升大家的开发效率和幸福度. 

**我也一直是寻求的社区共同维护来保证更高的质量**

**Comment by dingxiansen1** [comment]
好的，多谢指教，看一下paging3确实还有一些缺点，主要是考虑到paging3对分页来说是不错的（指的是无等待时间提前加载下一页数据），对于用户来说可以做到无线下拉，而不需要等待，对于开发者来说确实不太友好，哈哈

**Comment by liangjingkanji** [comment]
BRV不仅支持提前加载. 还支持自定义倒数第几个开始预加载

**Comment by liangjingkanji** [comment]
我还反对上来就是一个ViewModel, 很多页面其实不需要使用ViewModel去恢复数据. 
高质量代码从不写多余的东西

**Comment by dingxiansen1** [comment]
尴尬，看到了有预加载，但demo好像没用，结果一看代码下才发现测试数据 用的postDelayed(runnable, 2000)，改了之后体验极佳，(๑•̀ㅂ•́)و✧棒

**Comment by dingxiansen1** [comment]
对的，对于我来说，如果是过于简单的页面其实MVC也是合理的

**Comment by liangjingkanji** [comment]
默认情况就会开启预加载(默认加载到倒数前三个就开始)

另外推荐另外一个网络框架[Net](https://github.com/liangjingkanji/Net)

**Comment by dingxiansen1** [comment]
好的，谢谢，稍后我看看
