### ISSUE TITLE
分组支持多类型吗，好像没有看到呢

### ISSUE THREAD

**Issue by YQcharlse** [liangjingkanji/BRV#77]

**Comment by liangjingkanji** [comment]
两者并不矛盾吧
两个不同的类都实现了ItemExpand不就是多类型分组了吗?

**Comment by liangjingkanji** [comment]
而且从Demo可以看到二级分组和一级分组不是一个类型

**Comment by YQcharlse** [comment]
哦哦哦，好的明白谢谢

**Comment by liangjingkanji** [comment]
已更新文档

**Comment by YQcharlse** [comment]
我好像问错了，我的意思是，分组中第一是线性，展开后是 网格布局这样

**Comment by liangjingkanji** [comment]
同样支持. 两种方案

- 使用GridLayoutManager. 然后使用`SpanLookSize`去判断就行了(比如分组为1, 嵌套分组为2)
- 使用嵌套rv

**Comment by YQcharlse** [comment]
1.是否可以添加这是item数量
2.刷新
  addData(data) {
            index < total // 判断是否有更多页
        }
是否考虑设置同item

**Comment by liangjingkanji** [comment]
没理解你说的什么东西

**Comment by YQcharlse** [comment]
不好意思，描述有点问题
1.就是可以设置item的数量    控制item 数量
2. 就是设置不同的 model     下拉刷新， 类似这样的方法setDifferModels

**Comment by liangjingkanji** [comment]
1. 自己写个if判断下超过指定数量就不执行添加操作就好了, 我封装反而限制了很多功能, 比如提示语
2. 这种需求很生僻, 而且这由数据集合自身过滤完成再设置更好

不要要求数据交给UI控件去处理, 耦合且不合理. 

2 这个需求完全可以不用addData函数自己每次去获取然后筛除掉重复元素然后rv.models. (因为你的下拉刷新和上拉加载实际上都是一个逻辑)

**Comment by YQcharlse** [comment]
好的感谢回复，就是遇到了想问问

**Comment by liangjingkanji** [comment]
提供的三种刷新数据方式可以灵活使用

- `models`
- `addData`
- `setDifferModels`

**Comment by YQcharlse** [comment]
好的文档里有看到，感谢

**Comment by liangjingkanji** [comment]
这是不是Android上最强rv库

**Comment by YQcharlse** [comment]
这目前是我用过最强的rv库！ 够强  大佬牛逼
