### ISSUE TITLE
使用分组功能出现崩溃

### ISSUE THREAD

**Issue by 6YK5** [liangjingkanji/BRV#79]
当使用分组时,某一分组的Item超出一屏后点击分组标题收缩分组时会导致崩溃。

错误信息：
![image](https://user-images.githubusercontent.com/69612992/146106686-fb6188fb-14a5-459d-afb2-f6d2df2f7097.png)

**Comment by TxcA** [comment]
1. 标注BRV版本
2. sample 是否存在该问题
3. 如果sample 正常，请提供相应可复现代码

**Comment by liangjingkanji** [comment]
我在sample无法复现

**Comment by 6YK5** [comment]
我下午用sample试试,看看能复现一下错误不能

**Comment by 6YK5** [comment]
我下午改一下sample代码 看看能复现错误不能

**Comment by 6YK5** [comment]
已解决,原因是分组里面的item对应的实体类未继承ItemExpand(看文档以为只有外部的组实体类需要继承ItemExpand),导致点击收缩时移除元素时把其他分组属性相同的item也一并移除了,导致下标计算错误。

**Comment by liangjingkanji** [comment]
`collapse`折叠的核心代码
```kotlin
(this@BindingAdapter.models as MutableList).removeAll(sublistFlat)
```
理论上不要求子列表一定实现`ItemExpand`. 存在子列表的item才要求实现ItemExpand
你debug查看下具体什么地方下标错误. 或者fork仓库复现发我

**Comment by 6YK5** [comment]
我的使用场景是一个通讯录,顶部是一个常用联系人分组,与下方的地区分组中存在相同的联系人。
现在的问题变成了,如果我折叠常用联系人分组,那么下方包含相同联系人的分组也会移除那个存在于常用联系人分组的联系人。

**Comment by 6YK5** [comment]
东哥,使用sample代码可以复现.

**Comment by 6YK5** [comment]
东哥,使用sample代码可以复现.
将GroupBasicModel改为DataClass
GroupModel中的itemExpand默认值改为true,finalList给定一个随机长度的list
然后点击分组进行折叠,就能复现我上面说的问题了

**Comment by liangjingkanji** [comment]
这属于Java自带函数`removeAll`问题

```kotlin
val element = Data()
val list = mutableListOf(element, Data())
println("size = ${list.size}") // output 2
list.removeAll(listOf(element))
println("size = ${list.size}") // output 0
```

数据类`data class` 会重写`equals`导致相等
```kotlin
data class Data(var name: String = "data")
```

**Comment by liangjingkanji** [comment]
这个问题等我确定下是BRV内部修改还是文档提示

**Comment by 6YK5** [comment]
> 

是的,我也想明白了
