### ISSUE TITLE
多类型能否支持SpanSize设置

### ISSUE THREAD

**Issue by xiaoxiaohaozai** [liangjingkanji/BRV#80]

**Comment by liangjingkanji** [comment]
SpanSize由GridLayoutManager控制, 多类型由BindingAdapter控制, 两者没什么关系可以一起使用

**Comment by xiaoxiaohaozai** [comment]
> SpanSize由GridLayoutManager控制, 多类型由BindingAdapter控制, 两者没什么关系可以一起使用

我想通过一个Recyclerview 来实现复杂布局,当布局类型是网格或者瀑布流时,可以通过spansize 或者fullSpan 来控制item的宽度 ,可以参考 https://www.jianshu.com/p/60aa2fc17870

**Comment by liangjingkanji** [comment]
支持

**Comment by xiaoxiaohaozai** [comment]
> > SpanSize由GridLayoutManager控制, 多类型由BindingAdapter控制, 两者没什么关系可以一起使用
> 
> 我想通过一个Recyclerview 来实现复杂布局,当布局类型是网格或者瀑布流时,可以通过spansize 或者fullSpan 来控制item的宽度 ,可以参考 https://www.jianshu.com/p/60aa2fc17870

另外,我发现当布局类型类特别多时(包含嵌套情况),需要写很多的if else 希望可以提供brvan Provider的形式,将某种类型的配置隔离开 

类似
adapter = createAdapter {
    withType(Item::class.java, R.layout.item_eyepetizer_home) {
        // Bind data with viewholder.
        onBind { helper, item ->
            helper.setText(R.id.tv_title, item.data.title)
            helper.setText(R.id.tv_sub_title, item.data.author?.name + " | " + item.data.category)
            helper.loadCover(requireContext(), R.id.iv_cover, item.data.cover?.homepage, R.drawable.recommend_summary_card_bg_unlike)
            helper.loadRoundImage(requireContext(), R.id.iv_author, item.data.author?.icon, R.mipmap.eyepetizer, 20f.dp2px())
        }
        // Item level click and long click events.
        onItemClick { _, _, position ->
            adapter?.getItem(position)?.let {
                toast("Clicked item: " + it.data.title)
            }
        }
    }
}

现在 我自己的写的demo
  adapter = binding.recyclerview.linear()
                .divider(R.drawable.divider_horizontal)
                .setupExt {
                    //设置支持的布局类型
                    addType<BannerUIModel>(R.layout.home_layout_banner)
                    addType<WxUIModel>(R.layout.home_layout_wx_grid)
                    addType<CategoryItemUIModel>(R.layout.home_layout_category_item)
                    addType<String>(R.layout.home_layout_project_title)
                    addType<HotProjectItemData>(R.layout.home_layout_project_item)


                    //onCreateViewHolder执行时回调
                    onCreate {
                        //嵌套在这里使用
                        when (it) {
                            R.layout.home_layout_banner -> {
                                val binding = HomeLayoutBannerBinding.bind(itemView)
                                binding.banner.setAdapter(object : BannerImageAdapter<BannerData>(emptyList()) {
                                    override fun onBindView(holder: BannerImageHolder, data: BannerData, position: Int, size: Int) {
                                        holder.imageView.load(data.imagePath)
                                    }
                                }).indicator = CircleIndicator(context)
                            }
                            R.layout.home_layout_wx_grid -> {
                                val binding = HomeLayoutWxGridBinding.bind(itemView)
                                binding.rv.grid(4).setup {
                                    addType<WxData>(R.layout.home_layout_wx_item)
                                    onBind {
                                        val itemBinding = HomeLayoutWxItemBinding.bind(itemView)
                                        itemBinding.tvName.text = getModel<WxData>().name
                                    }
                                }
                                binding.rv.isNestedScrollingEnabled = false
                            }
                        }
                    }

                    //onBindViewHolder执行时回调
                    onBind {
                        when (itemViewType) {
                            R.layout.home_layout_banner -> {
                                val binding = HomeLayoutBannerBinding.bind(itemView)
                                binding.banner.adapter.setDatas(getModel<BannerUIModel>().items)
                            }
                            R.layout.home_layout_wx_grid -> {
                                val binding = HomeLayoutWxGridBinding.bind(itemView)
                                (binding.rv.adapter as BindingAdapter).models = getModel<WxUIModel>().items
                            }
                            R.layout.home_layout_category_item -> {


                            }

                            R.layout.home_layout_project_title -> {

                            }
                            R.layout.home_layout_project_item -> {
                                val binding = HomeLayoutProjectItemBinding.bind(itemView)
                                val data = getModel<HotProjectItemData>()
                                binding.iv.load(data.envelopePic)
                                binding.tvName.text = data.desc
                            }
                        }
                    }

**Comment by liangjingkanji** [comment]
这就是和BRVAH一样的写法
![image](https://user-images.githubusercontent.com/21078112/147230961-54058917-a301-4eeb-bdfb-ecac506518c7.png)

但是我不推荐, 数据处理交由Model, 而创建内嵌rv我推荐还是在Activity中创建, 如果复杂化了你抽出函数即可

**Comment by xiaoxiaohaozai** [comment]
> 这就是和BRVAH一样的写法 ![image](https://user-images.githubusercontent.com/21078112/147230961-54058917-a301-4eeb-bdfb-ecac506518c7.png)
> 
> 但是我不推荐, 数据处理交由Model, 而创建内嵌rv我推荐还是在Activity中创建, 如果复杂化了你抽出函数即可

好的,我尝试一下,麻烦了

**Comment by xiaoxiaohaozai** [comment]
尝试后成功了,但是添加divider 会报错 ,不添加正常显示
![飞书20211223-191617](https://user-images.githubusercontent.com/14050369/147233004-6b32db1f-271e-4eac-997d-409198b23ca2.png)
![飞书20211223-191624](https://user-images.githubusercontent.com/14050369/147233011-52d1e4f3-1744-452c-8597-00dc5955adc4.png)
![飞书20211223-191620](https://user-images.githubusercontent.com/14050369/147233025-10ad91a6-700a-490c-97b1-747ab4f46a05.png)

**Comment by xiaoxiaohaozai** [comment]
提供的demo添加后也崩溃了

**Comment by liangjingkanji** [comment]
得在spanSizeLook里面判断不为-1

**Comment by liangjingkanji** [comment]
另外能item最好优先自己处理的分割线需求, 问题会少很多, 性能也更好
