### ISSUE TITLE
获取 ItemView

### ISSUE THREAD

**Issue by EndureBlaze** [liangjingkanji/BRV#82]
## 问题描述

我看到 `onClick` 方法需要传入一个 id，但是我已经使用了 `DataBinding` 了我就想能不能直接使用它的 id 字段<del>主要是强迫症</del>。但是我似乎没有找到可以在 `setup` 或者 `onBind` 里面拿到 `DataBinding` 的方法，只有一个 `getBinding` 的可以用，我不太确定我这样用是不是最优雅的，所以来问问。

### 期望行为

获取到 `DataBinding`

## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV: 1.3.40
- Gradle: 7.2
- Android Studio:  2021.2.1 Canary 6
- Android: 12

**Comment by liangjingkanji** [comment]
`R.id.item.onClick {}` 或者 在onBind{}里面使用`getBinding<ItemLayoutBinding>().setOnClick`
我推荐使用我说的前者

**Comment by EndureBlaze** [comment]
> 

多谢，我稍后去试一下

**Comment by liangjingkanji** [comment]
`onClick(R.id.item, R.id.item2){}` 可以为多个控件设置同一个点击事件

**Comment by EndureBlaze** [comment]
> `onClick(R.id.item, R.id.item2){}` 可以为多个控件设置同一个点击事件

另外我在任何地方使用 `models` 它的类型似乎都是 `List<Any?>?` 想要拿到数据的话还要强转一下，是我应该使用其他的方法还是这里本来就是这样

**Comment by liangjingkanji** [comment]
还有个`mutable `返回的是`MutableList<Any?>`,  
数据本身就是你穿进去的, 你自己已经有了不推荐使用BindingAdater再去取. 因为BindingAdapter接受`任意类型`, 所以你拿也只能手动转换

**Comment by EndureBlaze** [comment]
> 还有个`mutable `返回的是`MutableList<Any?>`, 数据本身就是你穿进去的, 你自己已经有了不推荐使用BindingAdater再去取. 因为BindingAdapter接受`任意类型`, 所以你拿也只能手动转换
好的，我明白了
