### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by hanqingkai** [liangjingkanji/BRV#83]
### 期望行为
  api 'com.scwang.smart:refresh-footer-classics:2.0.3'
    api 'com.scwang.smart:refresh-header-material:2.0.1'
这俩个包是否可以加在sample中而不是加在brv包中
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
我只是为了开箱即用, 为什么一定想要加到sample中?
这两个效果及时你不使用也不会占用多少空间

**Comment by liangjingkanji** [comment]
https://github.com/liangjingkanji/BRV/releases/tag/1.3.50

已经升级到最新的SmartRefreshLayout2.0.5了
