### ISSUE TITLE
强东哥，起来更版本了

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#84]
![image](https://user-images.githubusercontent.com/54784104/148645060-68340eae-24c9-4086-b358-791295493707.png)
![image](https://user-images.githubusercontent.com/54784104/148645077-d4775d45-174b-4766-9106-41de8233228f.png)
![image](https://user-images.githubusercontent.com/54784104/148645086-474628f9-a2c9-423e-bf20-5435db12e115.png)

**Comment by liangjingkanji** [comment]
[github.com/liangjingkanji/BRV/releases/tag/1.3.50](https://github.com/liangjingkanji/BRV/releases/tag/1.3.50)

**Comment by SaltedFish-Extreme** [comment]
> [github.com/liangjingkanji/BRV/releases/tag/1.3.50](https://github.com/liangjingkanji/BRV/releases/tag/1.3.50)

ojbk😁
