### ISSUE TITLE
缺省页用法？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#86]
我看了看net和brv的文档介绍，难道不是这么用的吗？
![image](https://user-images.githubusercontent.com/54784104/148668050-997c350c-e62b-4424-9ae5-c979b5367d34.png)
![image](https://user-images.githubusercontent.com/54784104/148668066-3c6c625b-6aa5-44d6-acd3-d2ac5aafeb13.png)
![image](https://user-images.githubusercontent.com/54784104/148668081-ec10bc39-ca39-4f6f-9892-16450e48bd97.png)
![image](https://user-images.githubusercontent.com/54784104/148668039-c6cf22a4-10b7-4a90-a59d-13d405d02d51.png)

**Comment by SaltedFish-Extreme** [comment]
我好像知道为什么了，全局搜了搜net的demo里有关缺省页的字段，发现在application里还要配置全局缺省页
````kotlin
//全局缺省页配置 [https://github.com/liangjingkanji/StateLayout]
        StateConfig.apply {
            emptyLayout = R.layout.layout_empty
            loadingLayout = R.layout.layout_loading
            errorLayout = R.layout.layout_error
        }
````
![image](https://user-images.githubusercontent.com/54784104/148669338-7993f4a6-be64-4ebc-b083-ddc3252467c8.png)
![image](https://user-images.githubusercontent.com/54784104/148669403-bdc4102f-b8c5-4832-af21-437199a986d0.png)
老哥你这东西不仔细找都找不到，也太坑了点啊，我看看给你改改文档使用说明吧😒

**Comment by liangjingkanji** [comment]
的确是漏写使用文档
