### ISSUE TITLE
老哥，这个主线程做耗时操作程序变卡是咋回事啊

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#88]
我这里只是调用page.onRefresh在作用域里请求数据然后填充adapter，难道这些不能在主线程做吗😢
![image](https://user-images.githubusercontent.com/54784104/149864564-254da2f3-4b58-4c23-b009-6da885e1e0d5.png)
![image](https://user-images.githubusercontent.com/54784104/149864766-98aab3f0-6e47-4b1c-9adf-8b37170613f8.png)
![image](https://user-images.githubusercontent.com/54784104/149864792-8cab6a05-ba81-4dba-af43-ddebdb7e7cef.png)
https://user-images.githubusercontent.com/54784104/149864828-19aa0493-10de-4004-865d-dda8b1008b1d.mp4

**Comment by liangjingkanji** [comment]
demo不就是在主线程吗?
你这个错误应该不是brv框架抛出

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 😂我也不知道，但是我这里也没做别的操作了😢

**Comment by liangjingkanji** [comment]
你先注释慢慢排查吧

```
The application may be doing too much work on its main thread.
```
这个错误明显不是说的不是不能在主线程运行. 你自己搜索下吧

**Comment by SaltedFish-Extreme** [comment]
> 这个错误明显不是说的不是不能在主线程运行. 你自己搜索下吧
>  😢好吧，我再看看吧
> > 你这个返回泛型有毛病吧? 套这么多层
没办法啊，玩安卓的接口是这样的😂

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 老哥，我好像知道是什么问题了，好像又是NestedScrollView嵌套的问题🤔把这个外层的布局删了就没出现过漏帧的问题了，这个坑太多了😢

**Comment by liangjingkanji** [comment]
NestedScrollView嵌套RV会导致RV复用视图功能失效, 造成卡顿

**Comment by SaltedFish-Extreme** [comment]
> NestedScrollView嵌套RV会导致RV复用视图功能失效, 造成卡顿

是这样，我想让banner和RecyclerView可以同时滚动，只能添加头布局了吗？

**Comment by liangjingkanji** [comment]
你搜下 CoordinatorLayout

**Comment by SaltedFish-Extreme** [comment]
> 你搜下 CoordinatorLayout

老哥，我记得这个是跟appbar用的吧，你是想让我把轮播图放在里面跟随RecyclerView滑动显示和隐藏吗？我是想要放在页面最顶上，RecyclerView在它底下，滑动页面就把轮播图滑走这样，按向上按钮时候滚动到顶部再显示🤔
