### ISSUE TITLE
老哥，这个添加头布局能不能像brvah一样添加一个view当作header啊？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#89]
![image](https://user-images.githubusercontent.com/54784104/149956896-ce7e3521-916d-4541-b346-b8ae0713b796.png)

**Comment by liangjingkanji** [comment]
不考虑, 觉得没必要

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 好吧，麻烦老哥了😂

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 但是老哥，我就想要在recyclerView上方加一个轮播图，就在页面顶部，下拉recyclerView就隐藏，当recyclerView拉到顶部时候才显示，这样要怎么用CoordinatorLayout，layout_behavior都是跟着一起recyclerView一起隐藏显示😢

**Comment by liangjingkanji** [comment]
"下拉RecyclerView隐藏?" 你确定你没说错吗?  上下方向你是不是搞反了

**Comment by SaltedFish-Extreme** [comment]
> "下拉RecyclerView隐藏?" 你确定你没说错吗? 上下方向你是不是搞反了

啊，我的意思就是recyclerView加载下面数据的时候😂手指是上拉😂

**Comment by liangjingkanji** [comment]
你可能不会使用CoordinatorLayout, 他支持控制隐藏的

你看下Demo里面的CoordinatorLayout演示代码. 看下是不是你要的效果

**Comment by SaltedFish-Extreme** [comment]
> 你看下Demo里面的CoordinatorLayout演示代码. 看下是不是你要的效果
跟这个不大一样，我是想在recyclerView拉到最上面第一条的时候再往上拉才显示轮播图，往下拉数据时候就隐藏，demo里这个是跟随recyclerView滚动来自动隐藏显示，我就是想实现NestedScrollView这种嵌套滚动的效果😢但是用这个跟recyclerView有冲突

**Comment by liangjingkanji** [comment]
demo我刚更新的, 你说的旧的效果吧

**Comment by liangjingkanji** [comment]
而且我都说了显示隐藏 CoordinatorLayout可以自己控制

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 是这样的效果了😂

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 唉，老哥，我主activity用的`CoordinatorLayout+AppBarLayout+Toolbar+FragmentContainerView+BottomNavigationView`
多fragment都是填充到FragmentContainerView里的，在fragment里再用CoordinatorLayout嵌套就冲突了，主activity里的layout_behavior就不管用了，而且页面还会显示不全，可能是被CoordinatorLayout遮挡住了，绞尽脑汁也解决不了，我刚才想用BRV的多布局还有用ConcatAdapter来实现一个recyclerView嵌套两个adapter也实现不了，感觉我还是用不明白这个框架，要不我就换成BRVAH来实现recyclerView头部布局吧，只用这个做不需要头部布局的😢

**Comment by liangjingkanji** [comment]
我都没搞懂你. 第一次见Coordinator还需要嵌套的. 
另外请求头就是多类型. BRVAH也是用的一个LinearLayout作为请求头. 你灵活思考下
至于你要怎么实现都行

**Comment by liangjingkanji** [comment]
另外这个框架就是实现了一个自定义的BindingAdapter. 不存在无法使用`ConcatAdapter`

**Comment by liangjingkanji** [comment]
写代码切记思想固化. 看界面布局灵活一点

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 好的老哥😂

**Comment by liangjingkanji** [comment]
基本上不存在需要你Coordinator嵌套情况.  
你也不要把Toolbar写到主页. Toolbar最好写到Fragment里面

**Comment by SaltedFish-Extreme** [comment]
> 基本上不存在需要你Coordinator嵌套情况. 你也不要把Toolbar写到主页. Toolbar最好写到Fragment里面

嗯，我当时没想过‘我的’页要隐藏或者不显示toolbar，只在‘我的’fragment恢复时把toolbar右边的菜单项隐藏了😂
我本来是打算直接用原来做第一行代码里的demo时的MaterialDesign的布局的，这样感觉用Navigation+FragmentContainerView填充单独的fragment比较方便，导航的代码也少，比较直观😂
等做完这一版之后下一版换ViewPage2试试🤔
因为我主activity需要指定布局行为让 标题栏 底部选项卡 悬浮按钮 根据填充的fragment滚动页面时联动，正好使用CoordinatorLayout这套，在填充的fragment里要指定布局行为确实只能嵌套了😂

**Comment by SaltedFish-Extreme** [comment]
我本来昨天找了个CoordinatorLayout和RecyclerView联动的自定义布局行为，但是因为嵌套的问题，actviity里面的就没有用了，现在就先给RecyclerView添加头布局看看效果能不能实现吧🤔

https://user-images.githubusercontent.com/54784104/150158493-d9f37bf8-5ad9-48cf-a58d-fb0440392fc2.mp4

**Comment by LillteZheng** [comment]
同问，如何在库中添加一个 bannerView 轮播图

**Comment by liangjingkanji** [comment]
TextView怎么添加BannerView就怎么添加
