### ISSUE TITLE
老哥，你的BRV和BRVAH一起用，使用PageRefreshLayout布局在page.onRefresh里面给adapter设置数据，不会走page.onLoadMore回调，没法加载数据，直接就显示没有更多数据🤔

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/BRV#92]

**Comment by SaltedFish-Extreme** [comment]
我试了一下午，感觉这俩库不怎么兼容，用BRVAH的话，只能用SmartRefreshLayout单独走刷新和加载的回调给adapter设置数据了🤔

**Comment by liangjingkanji** [comment]
PageRefreshLayout里面的`addData`函数要求使用BRV的BindingAdapter才有效. 其他的功能不影响

**Comment by liangjingkanji** [comment]
至于你说的`onLoadMore`不会执行我不清楚为什么

**Comment by SaltedFish-Extreme** [comment]
> 至于你说的`onLoadMore`不会执行我不清楚为什么

我也不清楚，只执行了onRefresh，第一页数据显示完往下拉只会出现没有更多数据，我给onLoadMore的每一行打断点都不会执行🤔我是直接在onRefresh和onLoadMore回调里使用adapter.addData/setList来设置数据的😂

**Comment by liangjingkanji** [comment]
我都没搞懂为什么要混用. 就为了addHeaderView吗?

**Comment by liangjingkanji** [comment]
你可以去检查什么地方设置了`hasMore`. PageRefreshLayout内部使用该字段判断是否有下一页

**Comment by liangjingkanji** [comment]
如果还不行你直接用SmartRefreshLayout就好了

**Comment by SaltedFish-Extreme** [comment]
> 不懂为什么要混用. 就为了addHeaderView吗? 任何View都可以通过layout添加吧?

是啊，目前就我重写了好几遍的demo来看，只有使用BRVAH的头布局可以实现我想要的效果，然后一和BRV一起用就出问题😂我是实在不会多类型了，感觉BRV的多类型还有点难用，这个bindingAdapter我也搞不明白怎么和concatadapter一起用，还有我这个banner还挺麻烦的，单banner布局要用adapter填充，adapter又要用另一个自定义的banner布局填充😂

> 如果还不行你直接用SmartRefreshLayout就好了

我目前只使用SmartRefreshLayout和BRVAH就没事了，能实现效果，调用autoRefresh和autoLoadMore还会出问题，但是这样做scopeNetLife和刷新加载监听里的重复代码就太多了，这样感觉下来还是你的BRV好用😂但是我这个地方只能用头布局😢

> 你可以去检查什么地方设置了hasMore. PageRefreshLayout内部使用该字段判断是否有下一页

这个我也不清楚，等我明天把这个demo再复制一遍再整合下BRV试试，实在不行，带banner的主页这块就只能单独用BRVAH了😢

**Comment by liangjingkanji** [comment]
brv就多类型最好用

实现多类型就两步

1. 添加类型addType
2. 添加数据

添加请求头也是两步
1. 添加类型addType
2. 是addHeader添加头数据

**Comment by SaltedFish-Extreme** [comment]
> brv就多类型最好用, 如果brv多类型你都不知道怎么实现我建议你别用brv了, demo界面不到50行代码都看不懂多少有点夸张了

我其实连setup函数都看不大懂😂感觉我还是更适合写java复制粘贴老项目😢我目前只看你文档写的，有点简要，大体根据添加类型判断传递的数据，根据layout填充我能明白些，但是到我这个demo就感觉整不上去了，我还是觉得直接把view贴头布局上方便😢

**Comment by SaltedFish-Extreme** [comment]
唉，果然BRVAH还是不能和PageRefreshLayout一起用，不走加载的回调，只能使用SmartRefreshLayout，监听智能刷新布局的刷新和加载的回调来设置添加数据，BRV就用来和不需要头布局RecycleView的一起用了🤔

**Comment by liangjingkanji** [comment]
你可以fork demo我可以帮你看看为什么不走loadMore回调

**Comment by liangjingkanji** [comment]
不过你的基础太差, 感觉在这到处copy代码

**Comment by SaltedFish-Extreme** [comment]
> 不过你的基础太差, 感觉在这到处copy代码

是这样，我本来就是自学的，半路出家😂把三方库缝缝补补就做出来个项目的😂

> 你可以fork demo我可以帮你看看为什么不走loadMore回调

我把代码上传到gitee仓库行吗，你拉下来看看😂

**Comment by liangjingkanji** [comment]
我的意思是让你fork BRV仓库, 给我看fork后的github仓库地址.

**Comment by SaltedFish-Extreme** [comment]
> 我的意思是让你fork BRV仓库, 然后你复现下问题, 给我看fork后的github仓库地址.

😢我还没弄过，只会写项目，那我试试吧

**Comment by liangjingkanji** [comment]
阅读代码能力比写项目重要多了

**Comment by SaltedFish-Extreme** [comment]
> 阅读代码能力比写项目重要多了

😂唉，我还愁着找工作，都快半年了，只想先做个小项目拿去面试😢这边技术也落后，kotlin都没多少用的，代码都是复制粘贴缝缝补补，感觉还是得先找着工作才行😢

**Comment by liangjingkanji** [comment]
越落后越凸显你会的牛逼. 都会的去面试也没啥好说的

**Comment by SaltedFish-Extreme** [comment]
> 越落后越凸显你会的牛逼. 都会的去面试也没啥好说的

😂唉，这边都是物联网和工业互联网，我只能写写小项目，他们都要的软硬件还有小程序😢我会的感觉也都是他们看不上的😂

**Comment by liangjingkanji** [comment]
你自己决定就好了

**Comment by SaltedFish-Extreme** [comment]
> 你自己决定就好了

嗯😢

**Comment by SaltedFish-Extreme** [comment]
> 我的意思是让你fork BRV仓库, 然后你复现下问题, 给我看fork后的github仓库地址.

https://gitee.com/SaltedFish-Extreme/BRV
老哥这样可以吗😢

**Comment by liangjingkanji** [comment]
你都不是github算什么fork. gitee我就不看了

**Comment by SaltedFish-Extreme** [comment]
> 你都不是github算什么fork. gitee我就不看了

😢我是fork到github然后再从gitee拉过去的，我这没有vpn，github的代码拉不下来也提交不了🤦‍♂️

**Comment by SaltedFish-Extreme** [comment]
> 你都不是github算什么fork. gitee我就不看了

我好不容易提交成功了一次，要不你看看😂
https://github.com/SaltedFish-Extreme/BRV

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 老哥，你看出来啥问题了吗😂不行的话我就只能单独用一个RecycleView库了，这个要是能加一个头布局就好了，我对这个库唯一的痛就是一个头布局😢

**Comment by liangjingkanji** [comment]
BRV Demo里面的添加头布局方式你看不懂吗

**Comment by SaltedFish-Extreme** [comment]
> BRV Demo里面的添加头布局方式你看不懂吗

唉，我这个不是多类型啊，只是把根本就没有一点关系的复杂布局塞进去😂

**Comment by SaltedFish-Extreme** [comment]
> BRV Demo里面的添加头布局方式你看不懂吗

这请求的数据都不是一样的，发的都是不同的请求😂也不是并发

**Comment by liangjingkanji** [comment]
BRV的models没说要一个类型的数据啊?

**Comment by liangjingkanji** [comment]
你把你的仓库的
```
this.finishRefresh()  // 改成 finish() 就会执行onLoadMore了
```

**Comment by SaltedFish-Extreme** [comment]
> 你把你的仓库的
> 
> ```kotlin
> this.finishRefresh()  // 改成 finish() 就会执行onLoadMore了
> ```

好了😂

> BRV的models没说要一个类型的数据啊?

唉，我这个布局麻烦啊，用另一个布局填充，还必须得用adapter😂

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 唉，老哥有意向加一个view当头布局的扩展方法吗😂  

话说老哥，你这个item点击事件也会出现这个
![image](https://user-images.githubusercontent.com/54784104/150632401-2b4b5c73-387e-4b95-8574-279d06d1eb5b.png)
就和我使用BRVAH时候的情况一样 https://github.com/AllenCoder/BRVAH_kotlin/issues/18

**Comment by SaltedFish-Extreme** [comment]
唉，本来我都打算不用BRV写了，但是缺省页分页加载和扩展的智能刷新是真的香😂只用BRVAH和智能刷新再加上StateLayout来做，代码又多又乱而且智能刷新嵌套StateLayout用会有些诡异的bug🤢没办法刚才我又加上BRV试了试，经过对finish()方法和page链式调用的函数反复尝试之后，这次终于可以说是稍微好用了些🤔onRefresh()和onLoadMore()都能走了，只是分页没有用了，还是要手动分页加载更多🤔还有链式调用的refreshing()和showLoading()方法没有用了，这两个会一直显示加载中的缺省页，不会加载数据显示showContent()的页面，只能使用refresh()和autoRefresh()来显示或者隐藏刷新动画了，没有网可以自动显示网络异常的缺省图🤔不过用来当作扩展的智能刷新还是香的，只是加载中缺省页要是也能用就好了，目前是不知道怎么用了😂

**Comment by liangjingkanji** [comment]
会考虑添加`addHeader(View)`, 但是改动有点多我暂时没空. 你可以暂时使用`layout`布局或者自己提交PR和我共同完成

**Comment by SaltedFish-Extreme** [comment]
> 会考虑添加`addHeader(View)`, 但是改动有点多我暂时没空. 你可以暂时使用`layout`布局或者自己提交PR和我共同完成

好的，麻烦你了老哥，话说这个PageRefreshLayout和BRVAH一起用的时候没法使用refreshing()或者showLoading()是咋回事，会一直显示加载中页面，我fork下来在demo复现了，你可以帮忙看看吗😂https://github.com/SaltedFish-Extreme/BRV

**Comment by liangjingkanji** [comment]
因为需要手动调用showContent(原本addData函数内部有调用)

**Comment by SaltedFish-Extreme** [comment]
> 因为需要手动调用showContent(原本addData函数内部有调用), 但是addData只支持BindingAdapter调用


手动调用的话是在哪调用😂我看在onRefresh回调最后调用的话，往下拉会直接显示没有更多数据🤔

**Comment by liangjingkanji** [comment]
```kotlin
fun showContent(hasMore: Boolean = false, tag: Any? = null)
```
第一个参数为是否有下一页

**Comment by SaltedFish-Extreme** [comment]
> 第一个参数为是否有下一页

好的，麻烦老哥了😂

**Comment by SaltedFish-Extreme** [comment]
> ```kotlin
> fun showContent(hasMore: Boolean = false, tag: Any? = null)
> ```

emmm...在demo里可以，但是在我这个项目中好像不行，不管是在net的作用域里写还是在刷新回调的最后写都不行🤦‍♂️要不一直显示加载中页面，要不就干脆不显示，缺省页就没用到😂原来光用BRV时候会正常显示的🤔
![image](https://user-images.githubusercontent.com/54784104/150712590-8cc042a0-5364-4ca9-8ac4-ed7922432ecd.png)
![image](https://user-images.githubusercontent.com/54784104/150712637-da583fd4-1dc2-4c37-8c89-5fc67b27899a.png)

**Comment by SaltedFish-Extreme** [comment]
实在不行，暂时就不在主页设置加载中缺省页了，其余不用轮播图的页面再单独用BRV🤔

**Comment by liangjingkanji** [comment]
要在请求完成后调用showContent(请求肯定在scope里面发生所以showContent也在里面).  showContent内部已经调用finish了无需再次调用.

查看`finish()`方法也可以看到也有个`hasMore`参数

**Comment by liangjingkanji** [comment]
```kotlin
page.onRefresh{
   scope {
      val response = Post<List<Model>>("api"){
      	    param("page", index)
      	}.await()
      if(response.isEmpty) { // 如果空显示空缺省页
      	showEmpty()
      }else {
      	if(index == 1) { // 如果为1表示下拉刷新
  			brvah.setData(response)
  		}else { // 上拉加载更多
  			brvah.addData(response)
  		}
  		showContent()    
      }
   }
}.showLoading
```

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 好的，麻烦老哥了😂话说不用BRV的addData方法的话，index分页就不能用吧🤔其实我还是挺喜欢用findviewbyid的，需要什么就写什么，databinding感觉有点麻烦，viewbinding原来用过，等后面再试试吧😂

**Comment by liangjingkanji** [comment]
的确不能用了, 那你自己判断来自增index吧

Databinding我是首推. 这个框架很简单的

**Comment by SaltedFish-Extreme** [comment]
> 的确不能用了, 那你自己判断来自增index吧

好的👌
> Databinding我是首推. 这个框架很简单的. fbi是最愚蠢的用法

好吧😂

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 唉，老哥，玩安卓的接口一会页码从0开始一会从1开始，这个`PageRefreshLayout.startIndex`只能在application里初始化一次吧，每次刷新数据都会把索引重置成这个，这样这个项目有很多页面也不能用index分页，只能用变量手动分页了吧🤦‍♂️

**Comment by liangjingkanji** [comment]
你单独开个issues
