### ISSUE TITLE
请问下这个库支持 Java 使用吗，首次接触 android 开发，看到的文档大部分是 kotlin 的，目前希望是使用 Java

### ISSUE THREAD

**Issue by danleechina** [liangjingkanji/BRV#93]

**Comment by liangjingkanji** [comment]
能不能用看java兼容性了, 反正用起来语法肯定是不太顺手, 我也没具体测试. 只能说纯java项目不推荐了, 混合kt项目还是可以经过二次封装正常使用的
kotlin兼容java, 但是java不是完美兼容kotlin. 
另外你首次接触android不建议使用java开发很多库或者官方框架不兼容java
