### ISSUE TITLE
可以不重写onbind然后加载图片吗

### ISSUE THREAD

**Issue by byning2012** [liangjingkanji/BRV#96]
现在我是重写onbind后获取iv控件再去加载图片的，有更优雅的方式吗

**Comment by TxcA** [comment]
百度、Google DataBinding @BindingAdapter Glide。
xml布局里可以直接赋值图片地址，不用在onBind处理。
这是DataBinding的知识点，不是BRV的。

**Comment by liangjingkanji** [comment]
使用DataBinding的`@BindingAdapter`来自定义属性是最优雅的

```xml
<ImageView
    android:id="@+id/ivImage"
    android:layout_width="100dp"
    android:layout_height="100dp"
    img="@{m.image}" />
```

可以参考或者引入[Engine](https://github.com/liangjingkanji/Engine/blob/HEAD/engine/src/main/java/com/drake/engine/databinding/GlideDataBindingComponent.kt)中的代码实现

**Comment by byning2012** [comment]
非常感谢两位的回复。
