### ISSUE TITLE
当我在viewmodel中 通过MutableLiveData 拿数据时  有点不会用了

### ISSUE THREAD

**Issue by bjy520** [liangjingkanji/BRV#98]
## 问题描述
 页面请求后  通过MutableLiveData 监听了数据  拿到后  如何加载更多页跟刷新 
  
mViewModel.getGame(1)    获取的数据传给了mViewModel.game
后面
 mViewModel.game.observe(this){
  数据都是在这里的   
}
mDatabind.page.onRefresh {
这里怎么控制刷新等操作呢
        }
目前我想到的方案是
mViewModel.getGame(){
在这里获取数据  不用MutableLiveData  
}

**Comment by liangjingkanji** [comment]
```kotlin
binding.page.onRefresh {
  vm.getGame().observer(activity){
      addData(it)
  }
}
```

顺带一提

1. 成员属性使用`m`开头前缀是Java的风格, kotlin不要使用
2. 强烈不推荐网络请求返回liveData. 建议直接使用协程

**Comment by bjy520** [comment]
确实多此一举了，因为以前用的别的请求的，没有用到协程，我这就把其换掉。最后谢谢东哥！

**Comment by liangjingkanji** [comment]
协程的网络请求我只推荐使用[Net](https://github.com/liangjingkanji/Net/)
