### ISSUE TITLE
大佬，BRV支持左滑出现布局么，就像QQ那样，左滑显示删除按钮。

### ISSUE THREAD

**Issue by amosxb** [liangjingkanji/BRV#99]
## 如何复现
建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频

## 版本
- BRV:
- Gradle: 
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
可以查看文档: [侧滑按钮](https://liangjingkanji.github.io/BRV/swipe/#_2)

这种效果属于iOS并不推荐Android使用, Android一般是长按菜单. 如果你要实现建议通过自定义View

**Comment by OJZen** [comment]
东哥说的没错，侧滑item是IOS的交互逻辑。例如在微信上，IOS向左滑动是操作item，Android左滑是切换tab，长按才是操作item。

**Comment by liangjingkanji** [comment]
是的. 而且现在几乎所有Android手机都是支持侧滑返回手势的. 这是基于系统的手势功能无法拦截.
